### ISSUE TITLE
Ratchet & Clank: Into the Nexus [NPUA80908] - Game does not reach title screen

### ISSUE THREAD

**Issue by CirkuitBreaker** [RPCS3/rpcs3#10636]
## Quick summary
Ratchet & Clank: Into the Nexus won't reach the title screen unless any of the following apply:
1) A save file for the game does not exist
2) The shader cache is deleted before running the game
3) "Disable On-Disk Shader Cache is checked"

## Details
The emulator will always make it through all of the splash screens and display the first loading screen, but unless any of the three above apply, after the first loading screen, the emulator displays a black screen and freezes.

Edit: I have discovered the game will never make it to the title screen if the SPU or PPU decoders are set to interpreter.

#### System configuration:
* OS: Manjaro Linux
* CPU: AMD Ryzen 5 3600
* GPU: AMD Radeon RX 5700
* Driver version: amdgpu/Mesa 21.1.5

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6910549/RPCS3.log.gz)

**Comment by JimScript** [comment]
From my experience, you can get into the main menu with a save file and a shader cache, but it is wildly inconsistent. It seems almost entirely random, so it might be a race condition. Here is a RSX capture and log.gz file for a working instance:

RSX capture:
[NPUA80908_20211119063501_capture.zip](https://github.com/RPCS3/rpcs3/files/7570984/NPUA80908_20211119063501_capture.zip)

Log.gz:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7570992/RPCS3.log.gz)

System:
- SYS: RPCS3 v0.0.19-13029-3d859a74 Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 471.68.0.0
- SYS: Firmware version: 4.85

**Comment by nitroos-ai** [comment]
Retest with latest master, it's working for me with some vulkan errors in "Strict Rendering Mode":

`·E 0:02:16.511540 {RSX [0x4e03f14]} RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdPipelineBarrier-dstStageMask-04092 ] Object 0: handle = 0xe058be0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xe9e09916 | vkCmdPipelineBarrier(): .dstStageMask includes VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT when the device does not have conditionalRendering feature enabled. The Vulkan spec states: If the conditional rendering feature is not enabled, pname:dstStageMask must not contain VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstStageMask-04092)`

`·E 0:02:16.511902 {RSX [0x4e03fb0]} RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdCopyQueryPoolResults-renderpass ] Object 0: handle = 0xe058be0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4d7322f4 | vkCmdCopyQueryPoolResults: It is invalid to issue this call inside an active VkRenderPass 0x9f9cc20000007519[]. The Vulkan spec states: This command must only be called outside of a render pass instance (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdCopyQueryPoolResults-renderpass)`

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7946495/RPCS3.zip)

**Comment by JimScript** [comment]
I've been able to get into the game after the first attempt for a while now. As in, after the black screen boot up I can load up the game normally for a while afterwards, even after I close and open the emulator. I change no settings whatsoever, it just works the second attempt and beyond for awhile.

**Comment by YuriNator557** [comment]
> I've been able to get into the game after the first attempt for a while now. As in, after the black screen boot up I can load up the game normally for a while afterwards, even after I close and open the emulator. I change no settings whatsoever, it just works the second attempt and beyond for awhile.

I have noticed that the issue doesn't appear to be consistent anymore but it does still happen sometimes, in my case at least

**Comment by JimScript** [comment]
To me, it almost always go black on first boot, then fine on all the rest. It feels like some file doesn't get there fast enough, and afterwards gets there because it was cached for the previous attempt.

**Comment by JimScript** [comment]
I think this has been fixed by #12678 or something, because now I can get to the main menu the first time and consistently.

**Comment by Jonathan44062** [comment]
Still black screen, you need to use "Disable On-Disk Shader Cache" in Advanced tab
![image](https://user-images.githubusercontent.com/78843189/193337304-37ed4559-6007-41ea-8938-15dd138b46d6.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9686959/RPCS3.log.gz)

**Comment by JimScript** [comment]
It's still a little inconsistent, I can get in it on the first try on my Windows computer every time, but not on my Steam Deck. With OGL, "Disable On-Disk Shader Cache" or deleting the shader cache doesn't even fix it. The Frontend of this game of this game seems _very_ sensitive.

**Comment by willemi89** [comment]
Hey fellas, question. 
Has it been fixed yet? 
I still can't load the game without having to delete my existing save game.

**Comment by JimScript** [comment]
No it's still finicky, but I've been able to get to the title screen but just running the game again after it fails the first time, but it's a real "your mileage may vary" kinda thing because my Steam Deck is different. It's like the data needs to be cached for it to be fast enough.

**Comment by JimScript** [comment]
I was wondering if #13492 fixed this since it altered the save data timings to fix race conditions, and after I tried today I got to the menu first try, I usually have to do it again to get in. So I wonder if anyone else can confirm this, I can't be sure since I always had a "try again" workaround.
