### ISSUE TITLE
Bug: Test Drive Unlimited 2 crashes when trying to press buy a car

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#10876]
When you try to buy a car in TDU2 BLES00884 (in my case a Touareg V10 TDI), the game crashes with:
![image](https://user-images.githubusercontent.com/1712979/133568723-9a2cf3d2-f1e0-4d7b-ac4e-328c60cc5dee.png)

Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7175663/RPCS3.zip)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/issues/10876

**Comment by Zangetsu38** [comment]
> 
> 
> Fixed by #10876

fixed by issue ? :D @kd-11 you have fail write pr number ? ^^

**Comment by kd-11** [comment]
Fixed :D

**Comment by Shoegzer** [comment]
@xddxd I wanted to confirm this is fixed but the game locks up during the title screen sequence.  I'm using BLUS30527 - perhaps it's something specific to the US version, or are you using a custom setting that permits going ingame?

**Comment by xddxd** [comment]
The game is very unstable on fresh cache. Try 1000us driver wakeup delay.

**Comment by Shoegzer** [comment]
Thank you.  You're right, the game always freezes the first time RPCS3 builds the shader cache.  After the first time, it gets to the Eden title screen at least, but then it freezes no matter how many further attempts are made.  Curiously, RPCS3's main menu toggles from "Pause" to "Play" upon freezing.  I tried setting driver wakeup delay to 1000us but it's still freezing at that point.  

Here's a log from my attempt: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/7180857/RPCS3.log.zip)
