### ISSUE TITLE
Many games showing as demo

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#10931]
Many games that were showing as full copies are now showing as demo, despite having .rap files installed in `~/.config/rpcs/dev_hdd0/home/00000001`.  I believe this was working with source from at least a month ago though not specifically sure which build this issue first occurred.  Willing to bisect if necessary.

**Information:**

* OS: Linux Mint 20.2 / kernel 5.11
* CPU: Intel i7-10870H
* Compiler: gcc 11.1.0
* Build tested: 269c4604aaecf433caeb9a427b835995b5cad956

**Comment by AniLeo** [comment]
You need to move files that are on subdirectories of dev_hdd0/home/00000001/exdata to the main exdata folder. Not an issue, old broken behaviour was fixed. This falls under support request.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by Shoegzer** [comment]
What do you mean by "main exdata folder"?  According to what's written [here](https://rpcs3.net/quickstart) this is correct:

> PSN .rap files must be placed in \dev_hdd0\home\00000001\exdata\ (or simply drag and drop them to the main emulator window)

Additionally, as suggested above, I've attempted to drag-and-drop the rap file into rpcs3 which also does not resolve this, and I think that behavior should at least work properly?

**Comment by AniLeo** [comment]
Unlocking trials usually requires .edat, not .rap. 
.rap files may then be optionally required to unlock .edat.

Again, ask for support on one of the support platforms.

**Comment by AniLeo** [comment]
If you had any trials that unlocked before by only having a ".rap" file, then what you had was an .edat file with the wrong extension.
.rap files decrypt full games or certain .edat files.

**Comment by Shoegzer** [comment]
Got it, thanks - and that seems more accurate to the console.  Is this documented anywhere, or is an update to the above link planned which reflects this change?  Before seeking support, would like to read a bit first to understand what types of titles should expect edat, vs. rap, where each should be located, etc.  

As for this setup, currently all files are in the main exdata folder (no subdirectories) and this still seems to be fine but some games (seems primarily psn games) show up as demo and I'm still not entirely sure what to do about that.

**Comment by AniLeo** [comment]
Applications that are trials that can optionally be activated to full games require .edat
The .edat file may be encrypted and require a .rap file to decrypt

Applications that are full games only require only a .rap file

Demo only games / free applications usually come unencrypted, but in rare cases may come encrypted (e.g. Crunchyroll) and require a .rap file to decrypt.

When you buy the activation for a trial, it usually comes with an unlock package. It will work correctly if you install said package directly on RPCS3, or whether you dump your console's exdata folder .edat files directly to RPCS3.

Check what files aren't 16 bytes and rename their extensions back to .edat

**Comment by Shoegzer** [comment]
Great explanation, thank you.  There are some 352-byte "rap" files in exdata root, which I believe are the encrypted license files (edats) you were referring to.  Renaming one of them to edat as you suggested worked, however the game has no corresponding rap file in exdata, so I guess in that case the license file was stored as unencryped?

From your first post above, I assume the required end-state is for all rap decryption keys and edat encryped license files to exist exclusively in the exdata root, just to be clear?

Not sure if this makes sense, but if I've got this right, a nice rpcs3 feature would permit the user to install edats as well as rap files (from the file menu) in the event the user only preserved the edat and not the unlock package itself.
