### ISSUE TITLE
Far Cry 3 [BLES01138]: Random Lighting and Shadow graphical errors

### ISSUE THREAD

**Issue by tech2c** [RPCS3/rpcs3#10998]
## Quick summary
Every time I run this game the graphical errors are different. See attached photos from 5 consecutive runs.
Usually the graphical errors are lighting and shadows. But in every case the player's skin is completely black (when in view) throughout the game.

#### 0. Make sure you're running with settings as close to default as possible
WCB must be active as this game won't render correctly without it.
I've tried many combinations of RCB, RDB, WDB, strict rendering, etc but no change in behaviour.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7338039/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a Renderdoc
 
I can provide renderdoc log but it is very large. If you need it I can upload somewhere.

Unfortunately when I attempt to capture RSX log RPCS3 crashes dead with purple text.

![RSX_Capture_Error](https://user-images.githubusercontent.com/92201819/137132698-ec73b3bf-1c11-47a0-97f5-31932d401c83.JPG)
I am also seeing lots of "Unimplemented warnings" as above.

#### 3. Please attach screenshots of your problem.
![vlcsnap-2021-10-13-20h22m06s418](https://user-images.githubusercontent.com/92201819/137133513-ccadce19-40a4-48a7-81d3-6341467c9d4b.png)
![vlcsnap-2021-10-13-20h22m32s652](https://user-images.githubusercontent.com/92201819/137133524-437a9236-43ef-4fb3-bcf5-ad9afcaa9c3f.png)
![vlcsnap-2021-10-13-20h22m58s921](https://user-images.githubusercontent.com/92201819/137133548-f2337ac5-05a9-4bff-8d90-db9e17df3913.png)
![vlcsnap-2021-10-13-20h23m24s797](https://user-images.githubusercontent.com/92201819/137133557-9e2ec618-f894-4683-b884-40abcdf838a7.png)
![vlcsnap-2021-10-13-20h23m48s213](https://user-images.githubusercontent.com/92201819/137133565-27688825-05e2-46ae-b500-cc76d57a25bd.png)

#### 5. Please provide your system configuration:
* OS: WIndows 10
* CPU: Ryzen 3700x
* GPU: 3060ti
* Driver version: nvidia 471.11

**Comment by Darkhost1999** [comment]
Honestly after escaping Vaas (Absolutely horrible experienc btw) I am supposed to wake up right there. I got the same issues with the same randomizations. Sometimes textures work other times they don't. However, because of
`·F 0:01:47.417698 {RSX [0x0052e44]} SIG: Thread terminated due to fatal error: Verification failed`
`(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:116[:4], in function src_rect)` as OP says I am inhibited from testing further. This fatal error is also in far cry 4.

![image](https://user-images.githubusercontent.com/60384196/183311302-f8f3f2ee-296c-456a-8af5-f03f63185485.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9277599/RPCS3.log)

If you do not use WCB. You do not get the issue above but you get:

![image](https://user-images.githubusercontent.com/60384196/183311702-ffe30ab0-36b3-4f43-a6a9-06cb517c3295.png)
E RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300400

Everything the user needs to play the game is in that tiny square in the top left. Obviously this isn't any fun and is near impossible to play with.

Without `·F 0:01:47.417698 {RSX [0x0052e44]} SIG: Thread terminated due to fatal error: Verification failed`
`(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:116[:4], in function src_rect)`  fixed that's about all we can do for this issue right now. Because of the intro and what grant looked like I suspect some sort of Zcull stuff but can't get in game frequently enough to verify.

**Comment by Darkhost1999** [comment]
I feel as if there is relation to these with this issue
https://github.com/RPCS3/rpcs3/issues/8901
https://github.com/RPCS3/rpcs3/issues/9133
https://github.com/RPCS3/rpcs3/issues/10208

**Comment by Darkhost1999** [comment]
Save file after the annoying cutscenes to benefit testing
[savedata.zip](https://github.com/RPCS3/rpcs3/files/9375035/savedata.zip)

**Comment by kd-11** [comment]
Adding to the short-term work queue. I'll try and look into this one soon.

**Comment by kd-11** [comment]
Update on the state of far cry 3:
- No longer crashes going ingame if safe settings are used.
- The shader swap issue was fixed. Visuals will flicker if you don't use host GPU labels but that is expected.
- The ground is black. This is a strange one as the data is being loaded from memory as 0 (black). The ground is rendered ok but brightness is 0 for some reason. If you hack the right shader it works ok.

**Comment by tech2c** [comment]
Thanks for your efforts kd-11.

I tested it again with latest master; it still looks random on each game load:
![Capture2](https://user-images.githubusercontent.com/92201819/197375573-e141783e-864d-4c52-845c-a1f68ad5905a.JPG)
![Capture1](https://user-images.githubusercontent.com/92201819/197375608-eeeba35d-1e4b-4b47-b74b-2e5ed95eb880.JPG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9845818/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
> - No longer crashes going ingame if safe settings are used.

Which settings are these "safe" settings to be used?

**Comment by corruptedcervid** [comment]
Confirmed still an issue as of RPCS3 v0.0.37-18110-d72f9567

<img width="1633" height="952" alt="Image" src="https://github.com/user-attachments/assets/2f799945-1e18-436f-a526-d41dd96565a4" />

[RPCS3.log.gz](https://github.com/user-attachments/files/21950159/RPCS3.log.gz)

9800X3D, RTX 4090, 64GB 6400CL32, Arch Linux

**Comment by AniLeo** [comment]
Can someone retest on the latest build?

**Comment by LuxiP7** [comment]
<img width="1631" height="947" alt="Image" src="https://github.com/user-attachments/assets/54efc869-8b9d-444a-b471-440e81f74923" />

Still an issue, RTX 4090, 7800x3D, Fedora Linux 44

EDIT: [RPCS3.log.gz](https://github.com/user-attachments/files/31563269/RPCS3.log.gz)

**Comment by AniLeo** [comment]
The game just needs "Write Depth Buffer" enabled. Any other issues with it enabled?

<img width="1280" height="747" alt="Image" src="https://github.com/user-attachments/assets/3ab801df-a696-4133-8847-b410c3fa6dd6" />

**Comment by Darkhost1999** [comment]
I'll check it out with current master I know old tests were not so simple.

**Comment by Darkhost1999** [comment]
Here is with Write Depth Buffers from a create default custom configuration. Which shows why Write Color Buffers is needed.

<img width="3840" height="2064" alt="Image" src="https://github.com/user-attachments/assets/32372840-80de-449f-a748-bd6ac4830707" />

So adding Write Color Buffers to expand the screen from the top left corner box to the full window, and allow host gpu labels ON to reduce flicker from every bush and grass.

<img width="3840" height="2064" alt="Image" src="https://github.com/user-attachments/assets/2162659d-eb45-49a7-ba34-9a76a18ab396" />

Current status is guns on AMD or igpu don't work without reflecting the appearance of things around them. The road chooses when to render inconsistently, and trees choose when to render, The glass of vehicles choose when to be see through or look like blobs of paint from epic mickey game, Fire from molotov's and camp fires choose when to render. If chosen not to then it makes the fire missions significantly harder especially when you light the entire jungle on fire.

[RPCS3.log.gz](https://github.com/user-attachments/files/31614058/RPCS3.log.gz)

Re-uploading my savedata again from earlier

[savedata.zip](https://github.com/user-attachments/files/31614183/savedata.zip)

My savedata is located here, obtained first gun.

<img width="3840" height="2080" alt="Image" src="https://github.com/user-attachments/assets/fc4aacb5-d7f3-48b9-b500-ebfe43557ed3" />

<img width="3840" height="2080" alt="Image" src="https://github.com/user-attachments/assets/22acd6a5-ff8b-422f-91b0-a2416a226dc9" />
