### ISSUE TITLE
LBP 2 and 3 Background Lighting

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#11317]
In both Littlebigplanet 2 and 3, lighting will only propagate around the playable lanes, leaving a strangely fuzzy but sudden falloff. I know this is an issue because lights can still affect the background in Littlebigplanet 1. Note how the tip of the grass only gets lit as it moves into the playable area in the video below.

https://user-images.githubusercontent.com/66685584/147806561-2071aef0-343c-429d-af1e-ff3e7c9fa0bd.mp4

RSX Caputre:
[BCUS98245_20211229194940_capture.zip](https://github.com/RPCS3/rpcs3/files/7795431/BCUS98245_20211229194940_capture.zip)

And this is a log of another instance of the game in the same place as enabling logging causes a big performance hit and produces a huge log file if left too long(#10497):
[RPCS3.log.gz.zip](https://github.com/RPCS3/rpcs3/files/7795448/RPCS3.log.gz.zip)

System:
- SYS: RPCS3 v0.0.19-13137-cb2748ae Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 471.68.0.0
- SYS: Firmware version: 4.85

**Comment by Tarek2013** [comment]
Try with Read Colors Buffers enabled

**Comment by JimScript** [comment]
Read Color Buffers alone does nothing to fix anything, but when combined with Write Color Buffers makes the lighting fog render correctly, unfortunately it also cause the emulator to crash on level exit. But none of this has to do with the fact that lighting just stops at the playing area. It is less noticeable in LBP3 as there are more playable lanes, but it still just stops there even in the middle of a polygon. But sometimes at certain angles the game even fails to render the lighting in general.

Here in LBP1, the lights can affect the background geometry:
![BCUS98208_screenshot_2022_01_02_14_57_19](https://user-images.githubusercontent.com/66685584/147891718-4f8636c6-bac1-4dfa-a39f-95e760cd216d.png)

But as you can see in the first post, the lights in 2 and 3 just stop outside the play area. Here is an example in LBP3:
![NPUA81116_screenshot_2022_01_02_15_06_23](https://user-images.githubusercontent.com/66685584/147891851-b6ea82a7-27b8-4592-8f5b-88b095e8d8c2.png)

**Comment by Yahfz** [comment]
This issue is very convoluted. Please post a simple PS3 vs RPCS3 comparison to make it easier to spot what the issue is.

**Comment by JimScript** [comment]
Okay here is is a comparison between a RPCS3 screenshot and an ingame capture with the photo feature, so sorry about the quality.

Ingame real ps3 photo:
![A Photo](https://user-images.githubusercontent.com/66685584/150617308-92fd4e22-4972-43c9-ac6e-aece0780594b.jpg)

RPCS3 screenshot:
![BCUS98245_screenshot_2022_01_21_16_26_27](https://user-images.githubusercontent.com/66685584/150617360-b9c6f5f7-24cc-43c4-98af-e3e8950b43bb.png)

With RSX capture:
[BCUS98245_20220121162703_capture.zip](https://github.com/RPCS3/rpcs3/files/7917298/BCUS98245_20220121162703_capture.zip)

As you can see, the shadow is missing from the box.

System:
- SYS: RPCS3 v0.0.20-13217-801e7f3c Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 511.23.0.0
- SYS: Firmware version: 4.85

**Comment by Asinin3** [comment]
Just a note on this, the MLAA patch changes the lighting so don't use it to compare vs PS3. And, the lighting on the PS4 versions of these LBP games is different than the PS4 release. Excuse the squished image:
![image](https://user-images.githubusercontent.com/15137035/164564165-f58a873e-4f28-4394-85bb-e5a4701854b2.png)


<details>
 <summary>PS3 VS RPCS3 VS RPCS3 with MLAA patch (Click to Expand)</summary>
PS3

![ps3](https://user-images.githubusercontent.com/15137035/164564190-1df49a16-43b2-4391-8c19-63c1a15b9d41.png)
RPCS3
![rpcs3](https://user-images.githubusercontent.com/15137035/164564393-418c8545-c010-4ec2-8cf8-2cdef2826666.jpg)
RPCS3 + MLAA patch
![rpcs3 mlaa patch](https://user-images.githubusercontent.com/15137035/164564399-61438254-f6f5-40e2-9cef-903817c1f763.jpg)
</details>

These images are a bit old though, would appreciate a retest.

**Comment by JimScript** [comment]
Yeah, as far as I can tell, the lighting fog uses the same rendering layer as MLAA. But the weird thing is if it's "disabled" it will appear in the background of the gardens theme at certain angles, rendering how it should in the front. You can see this in the video in the first post.

**Comment by JimScript** [comment]
In LBP3, I found a very helpful ingame function called "disable shadows" in the material tweaker. With it, I can better show what is missing and give a potential software lead on the problem.

PS3 enabled shadows:
![A Photo_1](https://user-images.githubusercontent.com/66685584/168511447-935834cb-d823-4f99-8240-7737623b9d4d.jpg)

PS3 disable shadows:
![A Photo_2](https://user-images.githubusercontent.com/66685584/168511521-93fe8c74-b326-4d33-8a34-27487827af43.jpg)

RPCS3 enabled shadows:
![NPUA81116_screenshot_2022_05_15_19_38_08](https://user-images.githubusercontent.com/66685584/168511643-df95d5be-22f3-49a4-9284-bbca3e7843b1.png)

RPCS3 disabled shadows:
![NPUA81116_screenshot_2022_05_15_19_38_12](https://user-images.githubusercontent.com/66685584/168511724-f90fb745-1116-415a-b2a2-e820e753785a.png)

As you can see, the "disable shadows" function works on a real ps3, but not on rpcs3 as it is already missing.

**Comment by TorutheRedFox** [comment]
this lighting is done through a volumetric slice of a selected chunk of the game, as described here by Media Molecule themselves: https://advances.realtimerendering.com/s2011/Evans,%20Kirczenow%20-%20Voxels%20in%20LBP2%20(Siggraph%202011%20Advances%20in%20Real-Time%20Rendering%20Course).pdf

perhaps this could give a clue on where it could be failing (MRT rendering maybe?)

**Comment by JimScript** [comment]
Wow, this has an explanation on to why LBP1 has weird bar issues with its transparent objects, 'dual layer transparency'. But yes, RPCS3 doesn't seen to utilize this volumetric lighting, or it does but it doesn't get any slices to compute shadows. I only skimmed through it, but I don't know why removing MLAA has the affect of removing all post-processing, like foggy lighting and vignette. This documentation is pretty informative on to how LBP1 and LBP2 work and differ from each other(I am just going to assume that LBP3 is just LBP2, but slightly modified).

**Comment by TorutheRedFox** [comment]
it does use this volumetric lighting, but has issues doing the voxelization step

and the patch to remove MLAA may be instead turning off all post fx, as I don't recall all post fx being removed when doing it using the debug menu toggle to turn MLAA off

**Comment by JimScript** [comment]
Last I saw #6348, disabling MLAA in the debug menu did get rid of the glow around the start gate and the darkening around the screen.

**Comment by JimScript** [comment]
Yeah, and when you increase the resolution scale the lighting fog gets 'dotted', as if there is a preset resolution from the CPU.

**Comment by TorutheRedFox** [comment]
the initial 4 AO slices do get rendered though, as they sometimes leak into the pause menu's render buffer
![BCET70023_screenshot_2022_10_08_16_09_42](https://user-images.githubusercontent.com/15708278/194714450-95b714bc-fcd2-4f7f-b356-77787969170b.png)

so there's something going wrong with decoding and combining those slices into the volumemap they use (maybe 3d textures are the issue here?)

**Comment by asxhun** [comment]
Any updates on this topic?

**Comment by Walid3810** [comment]
The Light fog Dosen't Work

**Comment by JimScript** [comment]
Again, you're not using the MSAA patch or the Force CPU Blit emulation debug setting to make the upscaling look better, are you? Because that's what causes the light fog to disappear, as the Anti-Aliasing and lighting effects seem to unfortunately be joined at the hip.

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by Aloquendiar** [comment]
Lbp3 still seems to have a problem with ambient occlusion/global illumination  when certain effects are activated, such as thrusters.
0.0.40-19089

https://github.com/user-attachments/assets/f4b48a50-5e23-476b-80bd-a549095fe601

**Comment by rleonever** [comment]
Can someone test again?

**Comment by asxhun** [comment]
Still happens on LBP2. Version: 0.0.42-19803

https://github.com/user-attachments/assets/ede428ef-ed4b-4fc7-a12b-34196f2f0c8a
