### ISSUE TITLE
SSX - Custom music is recognized but just plays loud buzzing

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11596]
## Quick summary
Custom music plays loud buzzing instead of the custom music.

## Details
As of PR 11560, SSX recognizes custom music in WAV/MP3 format as long as it's in an album, something that can be accomplished by putting tracks with metadata in dev_hdd0/music/albumnamegoeshere/.  Once in the menus, it'll detect your custom album.  However, once you get ingame, it'll play a constant ear-bursting buzzing noise.  This buzzing noise actually warps and fades depending on what you're doing in the game, just like custom music is supposed to do, so it's clearly trying to play it.  The log also spams "cellMusicDecode" messages and PR 11560 adds functionality for cellMusic, so it's likely something to do with that.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8181310/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![1](https://user-images.githubusercontent.com/58268914/156656992-b2a9a9ee-d6db-4057-9533-78c3a5fa5095.PNG)

![2](https://user-images.githubusercontent.com/58268914/156656999-c253e2a6-ed30-4f01-b301-915ca9a89d14.PNG)

![3](https://user-images.githubusercontent.com/58268914/156657006-60f24c71-9e30-44c0-88ff-81a5cda51402.PNG)

#### 4. Please provide comparison with real PS3.

Real consoles play your custom music without issues, applying its own effects as normal.

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 Super
* Driver version: 497.29
* RPCS3 version: v0.0.21-13331-e33b1306

**Comment by Megamouse** [comment]
Try with this:
#10579

**Comment by SlyCooperReloadCoded** [comment]
That PR eliminates the buzzing... and any music along with it.  No music at all, but the same messages are being spammed in the log.

**Comment by SlyCooperReloadCoded** [comment]
Interesting update on this.  Just for fun, I tried disabling Music Handler.  It was still able to find and "play" my custom music.  Seems this isn't related to the new feature?

**Comment by Megamouse** [comment]
The music handler has nothing to do with the decode

**Comment by Megamouse** [comment]
please try again with the latest build from https://github.com/RPCS3/rpcs3/pull/12324

**Comment by SlyCooperReloadCoded** [comment]
Still does not work, however, the error is different this time:

E SYS: 'cellMusicDecodeRead2' failed with 0x8002c10b : CELL_MUSIC_DECODE_ERROR_NO_LPCM_DATA [1]

This gets printed to the log instead of the old error.

**Comment by Megamouse** [comment]
Well then upload the log

**Comment by SlyCooperReloadCoded** [comment]
You'll see a pad being plugged in later than usual, that's because I still have to open the pad menu every time I boot games due to that other issue.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9163318/RPCS3.log.gz)

**Comment by Megamouse** [comment]
you weren't even using the PR build.
try again with latest master

**Comment by SlyCooperReloadCoded** [comment]
Oh oops.  Retested with latest master, new error is gone, this error is back:

E SYS: Stat: 'cellMusicDecodeRead2' failed with 0x8002c107 : CELL_MUSIC_DECODE_ERROR_DECODE_FAILURE [x2693]

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9167708/RPCS3.log.gz)

Custom music still not working.

**Comment by SlyCooperReloadCoded** [comment]
Tested again after most recent update since it improves cellMusic, no change.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9201050/RPCS3.log.gz)

**Comment by PandaPyre** [comment]
Any update on this? I would really appreciate being able to play SSX with a custom playlist, disappointing that it's still not working.

**Comment by SlyCooperReloadCoded** [comment]
Sorry about the duplicate issue, I completely forgot there was aleady one.

Now, I'm not sure when this improved, but on latest master, custom music does start playing.  Unfortunately, it's very broken and has numerous issues:

1.  Only the first song plays.

2.  When it reaches the end of the song, a loud audio corruption happens and then repeats the first song instead of moving to the next one.

3.  Exiting that event and going into another one, which would normally play the next song in the custom playlist, just stops music entirely.

4.  When the first song in the playist does play, it's 5x quieter than it should be, even when amplifying it in Audacity and turning both sound effect and voice volume down to zero.  Compare that to this video which uses the custom playlist feature.  Video uses the Xbox 360 release, but it's the same exact feature:

https://youtu.be/29vFty9FIro?t=144

**Comment by Megamouse** [comment]
test with #14999

**Comment by Megamouse** [comment]
I think I fixed some of the issues with files not playing.
I think I also fixed the audio pop at the end of a song.
The issue with music stopping when changing playlists is still under investigation.

**Comment by SlyCooperReloadCoded** [comment]
I tested that PR, unfortunately no change whatsoever.  Music still way too quiet, and going into another track kills the music, just like before.  I didn't hear the pop though, so that's progress.

**Comment by SlyCooperReloadCoded** [comment]
To clarify, my songs are not in any means quiet.  Here's the waveform of Track1 in Audacity:
![Capture](https://github.com/RPCS3/rpcs3/assets/58268914/5b8863c7-a5b6-4520-96f5-d840b2e0b7fa)

Super loud in anything that isn't the game, but the quietest sound element when playing the game.  That YouTube video showing the same feature shows it overpowering voice lines.

**Comment by PandaPyre** [comment]
The issues described above are still in the latest build. I would really like if this could get fixed!

**Comment by GlitcherOG** [comment]
Still an issue, Game only plays first song and then doesn't try to find the next song after.

**Comment by digant73** [comment]
maybe fixed the issue on playing only the first song. please retest

**Comment by GlitcherOG** [comment]
U cellMusicDecode TODO: cellMusicDecodeGetDecodeStatus2(status=*0xd024a770)
E SYS: 'cellMusicDecodeRead2' failed with 0x8002c10b : CELL_MUSIC_DECODE_ERROR_NO_LPCM_DATA [1]
E SYS: 'cellMusicDecodeRead2' failed with 0x8002c10b : CELL_MUSIC_DECODE_ERROR_NO_LPCM_DATA [2]
E SYS: 'cellMusicDecodeRead2' failed with 0x8002c10b : CELL_MUSIC_DECODE_ERROR_NO_LPCM_DATA [3]

When it tries to play the next song it says this in the log now

**Comment by digant73** [comment]
this issue could be related (maybe fixed) to PR https://github.com/RPCS3/rpcs3/pull/19478

**Comment by digant73** [comment]
please test PR #19478

**Comment by GlitcherOG** [comment]
Tested the PR, Doesn't fix the issue. It will play one song and then nothing after that. It will however loop that song with no issues in the menu

**Comment by digant73** [comment]
> Tested the PR, Doesn't fix the issue. It will play one song and then nothing after that. It will however loop that song with no issues in the menu

please attach the log
