### ISSUE TITLE
Regression: Strange artifacting in LittleBigPlanet [NPUA80472] (#11717)

### ISSUE THREAD

**Issue by Metraberryy** [RPCS3/rpcs3#11830]
## Summary
Some artifacts appear on the Pod's windows in the Vulkan renderer, a similar issue existed already in the OpenGL renderer.

This issue appears in v0.0.21-13399 (https://github.com/RPCS3/rpcs3/pull/11717)

### Regression
![regression](https://user-images.githubusercontent.com/30480654/163777146-9cfaec31-a9b0-41a2-866e-06ee7214cbe4.png)
https://drive.google.com/file/d/1iNJGkmdlJXwppH_PTOcWoPW-3EZXTYic/view?usp=sharing
This issue arose in a build affected by https://github.com/RPCS3/rpcs3/issues/11818, disabling the hack that caused that issue fixes that issue while this one persists. Both show up in the screenshot above.

### Previous behaviour
![correct](https://user-images.githubusercontent.com/30480654/163777097-8c2b67e5-e52e-428b-84a7-c70f582683da.png)
https://drive.google.com/file/d/1_FjHyzCXNP7RZ8z8dXbn661Fga-q3x9X/view?usp=sharing

### PS3 screenshot
Taken from a capture card
![Screenshot 2022-04-18 01-04-44](https://user-images.githubusercontent.com/30480654/163777512-0233ab7d-72a4-41cc-a58d-5165fe4f52cf.png)

## Reproduction
The screenshots are from the Pod, which you arrive in immediately after completing the introduction.

## System Specs
* Windows 10 10.0.19041
* Intel Core i7-9700K @ 3.60GHz
* NVIDIA GeForce GTX 1660 Ti
* Driver version 27.21.14.6089

**Comment by kd-11** [comment]
Unfortunately removing the workaround that causes this will break other games. My only option is to have some option to disable it in the config.yml.

**Comment by kd-11** [comment]
This should be fixed by just enabling strict rendering mode. It's a hardware limitation, not much we can do about it.
So why did it work before? Because we treated MSAA images the way they work under strict mode. It is also why MSAA was so slow on some hardware.

**Comment by metraberryy** [comment]
while enabling strict rendering mode does fix the issue, the game runs at 7fps with it enabled on my pc
having an option to disable the workaround would be nice

**Comment by capriots** [comment]
Sonic Unleashed also regressed, the entire image is really blurry now if MSAA is on. Strict rendering mode does _not_ fix it for me.

PS3:
![ps3](https://user-images.githubusercontent.com/29807355/169782285-6e4ee828-0cc3-46c4-a15d-653545e23ab1.png)

Before:
![before](https://user-images.githubusercontent.com/29807355/169782323-33e82c41-fe12-495e-b248-9d593555dc37.png)

After:
![after](https://user-images.githubusercontent.com/29807355/169782347-7ad6c982-7cc9-40f5-a1ac-534866e23940.png)

**Comment by Tarek2013** [comment]
Strict rendering mode doesn't fix the pb for me (AMD 5950X,RTX 3080TI,32gb RAM,Windows 10 21H1)

**Comment by Tarek2013** [comment]
Hi
With this settings, you can play LBP without using Strict Rendering mode At least,it works well for me) : 
CPU
- PPU Decoder : Recompiler
- SPU Decoder : Recompiler
- SPU XFloat Accuracy : Approximate Xfloat
- Additional Setting : Enable SPU Loop Detection
- SPU Block Size : Safe
- Preferred SPU Threads : Auto
- Thread Scheduler : Operating System

GPU
- Renderer : Vulkan
- Graphics Device : Your Graphic Card
- Aspect Ratio : Auto
- Frame limit : Auto
- Anisotropic Filter : x16
- Anti-Aliasing : Auto
- ZCull Accuracy : Precise
- Default Resolution : 1280x720 (Recommended)
- **Resolution Scale : 2560x1440 (up to this resolution making Artefacts and MLAA patch is needed to make to fix it)**
- Resolution Scale Threshold : 16x16
- Enable FSR Upscaling (with 100 RCAS Sharpening Strength is ok : down value if you meet issues)
- Shader Mode - ASync (multithread)
- Number of shader compiler threads : Auto
- Additional Settings : Write Color Buffer ON

Advanced
CORE
- Accurate RSX Reservation Access ON
- PPU LLVM Precompilation ON
- Silence All Logs ON

**Comment by ruvaldak** [comment]
> 

I can confirm this. It fixes the weird glitchy glass, however it's still not accurate. Strict Rendering Mode also fixes the issue, but NPUA80472 and all other versions of LBP1 seem to have massive slowdowns when that is enabled, causing 100% gpu usage even on a 2080ti.

**Comment by ruvaldak** [comment]
Commit 13176 is the last time that LBP1 looked like it should.

**Comment by kd-11** [comment]
If the issue is fixed with settings, why is this still opened? Is there something I'm missing?
The old way of doing MSAA was completely messed up, so while it looked great in some games, it completely broke others completely which is why I removed it. Strict mode restores the old method and adds a few other restrictions to ensure PS3 compatibility at the cost of removing upscaling and of course slower performance.

**Comment by capriots** [comment]
Sonic Unleashed is still blurry with AA on. Strict mode doesn't make a difference. It regressed with the same PR but I don't know if it's the same underlying issue.

I noticed I forgot to add logs and captures in my previous comment so I made some new ones.

Logs:
[Default settings](https://github.com/RPCS3/rpcs3/files/13759374/Sonic.Unleashed.default.log.zip)
[Strict mode on](https://github.com/RPCS3/rpcs3/files/13759375/Sonic.Unleashed.strict.log.zip)

RSX Captures:
[Default settings](https://github.com/RPCS3/rpcs3/files/13759378/Sonic.Unleashed.default.rrc.gz)
[Strict mode on](https://github.com/RPCS3/rpcs3/files/13759379/Sonic.Unleashed.strict.rrc.gz)

RenderDoc:
Since this is larger than 25MB, I uploaded it as video to trick GitHub.
<Details><Summary>Right click -> Download, then change the extension to .zip</Summary>

https://github.com/RPCS3/rpcs3/assets/29807355/5f7176cd-81b3-4a9a-bdcb-31e65c9ca5a2

</Details>

**Comment by TorutheRedFox** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/15708278/33ef52af-e05f-4264-9343-309e0a64f7b2)
the game used to be a little blocky due to MSAA but now it's just blurry and has artefacts on transparent objects (which rely on the MSAA buffer to be sampled correctly because of weird horizontal interlacing they do to hack around limitations of deferred rendering)

**Comment by kd-11** [comment]
The fix here is to hoist the strict mode MSAA behavior into a separate option. Something like "high quality MSAA" or something. Performance will be shit in AAA titles but it will close some of these tickets.

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/15000 using the option to force hardware resolve. The new toggle is in the advanced tab.
