### ISSUE TITLE
Custom Music Not Playing - Another Century's Episode: R [BLJS10081]

### ISSUE THREAD

**Issue by MasterRevan2015** [RPCS3/rpcs3#12369]
## Quick summary
In-game custom music not playing at all when selecting "custom".

## Details
Game runs perfectly except when I start to use custom BGM. It doesn't play at all. It'll require the music files to be placed under "ACER" subfolder (dev_hdd0\music\ACER) for it to be recognized or listed in-game.

This appears at the real-time log section whenever I try to play the custom mp3. Also the same entry when it starts playing in-game:

> 0, .context_option=0, .path='/dev_hdd0/music/ACER/ACERTestTrack.mp3' }
> U cellMusic TODO: cellMusicSetSelectionContext2(context=*0xd00ffd00)
> U cellMusic TODO: cellMusicSetSelectionContext2: failed. context = )
> 

#### RPCS3's log attached under here:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9143365/RPCS3.log.gz)

#### Comparison with real PS3.
I no longer have a working PS3 but it works fine back in 2010. And the music loops well too. No issues. Used MP3 files which are 320kbps too.

#### 5. Please provide your system configuration:
* OS: Windows 11 version 21HR (22000.651)
* CPU: AMD Ryzen 2600X at 4.050GHz
* GPU: MSI Ventus RTX 2060 Super OC 8gb
* Driver version: 516.59 (Game Ready Driver)

**Comment by Megamouse** [comment]
please try this #12370

if it doesn't work, upload a log

**Comment by MasterRevan2015** [comment]
> please try this #12370
> 
> if it doesn't work, upload a log

Appreciate the quick response. Will do when it gets compiled with the updated file/s. Or should I do something? Sorry, it's my first time reporting an issue lol.

**Comment by MasterRevan2015** [comment]
> please try this #12370
> 
> if it doesn't work, upload a log

Appreciate the quick response. Was able to test out the pull request build (rpcs3-v0.0.23-a1a7b4ac_win64) based on #12370. It plays fine now but the track is not looping. It'll play again after pausing the game though. 

Not sure if this is related but it I can see _.repeat_mode=0_. Possible fix if it's set to 1. But of course, you can debug better since you fully understand the codes more lol.

> S cellMusic: cellMusicSetSelectionContext2: new selection context = { .magic='SUS', .content_type=0, .repeat_mode=0, .context_option=0, .path='/dev_hdd0/music/ACER/09 - Steel Axe (With Wind SFX).mp3' }

Here's the log based on the pull request build:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9146530/RPCS3.log.gz)

Thanks again for the speedy response. Cheers!

**Comment by Megamouse** [comment]
I've been working on this loop issue for a while now.
But the fix isn't ready yet.
I've merged the other fix though. So I'll change the title of this issue to mention the loop

**Comment by MasterRevan2015** [comment]
> I've been working on this loop issue for a while now. But the fix isn't ready yet. I've merged the other fix though. So I'll change the title of this issue to mention the loop

Gotcha! No prob. I hope it'll get fully fixed so other games won't have a problem. Will wait patiently. But I'm so glad custom music plays now. Thanks again! o7

**Comment by Megamouse** [comment]
@MasterRevan2015 can you try with this? #12324

**Comment by MasterRevan2015** [comment]
> @MasterRevan2015 can you try with this? #12324

Heyo, @Megamouse! Sorry I recently just woke up late lol. Anyways, still the same. It doesn't loop. It'll play after pausing. Though I've noticed that the next song assigned won't play maybe because it was interrupted. This appears:

> E Music: Error event: "" (error=ResourceError)

Here's a video clip of that: https://bit.ly/3IU0t1O

But when it's not paused, it loads the next song fine. Here's the log file from pull build (rpcs3-v0.0.23-f88e3b5c_win64 / #12324):

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9156284/RPCS3.log.gz)

Cheers!

**Comment by Megamouse** [comment]
please try again with the latest build from #12324

**Comment by MasterRevan2015** [comment]
Howdy, @Megamouse! Was able to test build v0.0.23-490e1279. Same issue. Still not looping. This error also appears like last time after pausing the game to get the music playing again. The next assigned music won't play.

> E Music: Error event: "" (error=ResourceError)

Here's the log I got from the latest pull build.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9165195/RPCS3.log.gz)

Cheers!

**Comment by Megamouse** [comment]
So I found out why some of my MP3s aren't working.
It seems that the Qt media player uses some old backend that is not able to play certain mp3 if the ID3 tag is too large or has certain properties.

I got it to work with those MP3 once i copied the track and removed the album cover with a tool called Mp3Tag.

**Comment by Megamouse** [comment]
It might work with album art on linux since it should use a different backend.

**Comment by MasterRevan2015** [comment]
@Megamouse Whoa really? So glad the culprit was found. I didn’t there’s a Qt Media player. If only I’ve known about Qt before, we may have known sooner. Lemme give it a go again since I use MP3Tag anyway to organize my local songs. Will also try on Sims 4 and see if it stops the slight hangs and play issues by clearing the album art.

**Comment by MasterRevan2015** [comment]
Heyo, @Megamouse! Still the same on rpcs3-v0.0.23-18551713_win64 after clearing up the mp3 (including test mp3). _E Music: Error event: "" (error=ResourceError)_ still appears. At least we got to play it. 

Also, I found out that custom music also works with folder names other than ACER. Here's the log file of the pull build:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9173764/RPCS3.log.gz)

Right now, I'm good with the custom music playing in-game. I hope it gets fixed along with other games that uses custom music as well.

Cheers!

**Comment by Megamouse** [comment]
Can you try again?
The latest version should not use the old backend anymore, which means it may work with the ID3 tags now.

**Comment by digant73** [comment]
@MasterRevan2015 is that still an issue?
