### ISSUE TITLE
Warhawk BCUS98117 no in-game audio when using LLVM Recompiler for PPU Decoder

### ISSUE THREAD

**Issue by Snakeskiin** [RPCS3/rpcs3#12786]
### Quick summary

When playing Warhawk BCUS98117 using the LLVM Recompiler there is no in-game audio. There is sometimes audio for two of the four training missions Ground and Vehicle training, but never online or in flight training/practice. Static interpreter PPU decoder fixes this issue, but online performance is awful without recompiler (10-20 fps). Music is unaffected, only SFX issue.

### Details

As stated in the summary not much else to go over. Tweaking almost every single setting in RPCS3's configuration tab did not do the trick. The only way to get in-game audio back is to use the interpreter (static) for PPU decoder, which degrades performance to an unplayable level. There are other subtle issues with the game, too, but the audio issue is definitely the major one as of right now. No confirmed cases of this issue not existing in older versions of RPCS3. Confirmed no audio in 2018 and now from https://forums.rpcs3.net/thread-198581.html this forums post.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9742950/RPCS3.log)

### System configuration

in log

**Comment by NateDogg1232** [comment]
I'm also getting this problem. This is happening on the latest master as of posting this: 0.0.24-14319-4c8630d2 Alpha | master | local_build
[rpcs3.trimmed.log](https://github.com/RPCS3/rpcs3/files/9845822/rpcs3.trimmed.log)
The log has all "libnet" lines removed because otherwise the file was too large. I can provide the full .gz file if needed.

I notice that this problem is actually intermittent. It is something like 90% of the time. Sometimes the audio works fully with no problems. I've been noticing this problem for quite a while as well.
It's also worth noting that the audio is actually present for about 1 second at the beginning of the online match without fail, but then seems to cut out. Along with this, menu SFX and such still work outside of an online match.
Here is that audio:
https://user-images.githubusercontent.com/12480453/197376358-9c1b6f99-b211-49c9-b6e9-e6ac61091ea7.mp4

I also notice there's some reverb still happening as well, which is odd.

**Comment by Snakeskiin** [comment]
Hoping it might get fixed by #12747 whenever that gets finished

**Comment by Snakeskiin** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10475632/RPCS3.log.gz)
new log addition as recommended by Darkhost1999, this time using static interpreter (all SFX audio works)

**Comment by digant73** [comment]
@Snakeskiin is that still an issue?

**Comment by ManGuyNY** [comment]
@digant73 I can confirm, from my own testing, this is still an issue as of build 0.0.38-18435.

LLVM PPU (No SFX, music only):
[Warhawk \[BCUS98117\].log.gz](https://github.com/user-attachments/files/23892975/Warhawk.BCUS98117.log.gz)

Interpreter PPU(Works as expected):
[Warhawk \[BCUS98117\].log.gz](https://github.com/user-attachments/files/23892991/Warhawk.BCUS98117.log.gz)

EDIT: Interestingly, while testing this, I've found that the game will now fail to load in entirely if the PPU & SPU decoders are both set to LLVM. Attempting to load into the training will crash the emulator. Setting the SPU to ASMJIT will allow the game to load with no SFX, same as prior behavior. Setting the PPU decoder to the static interpreter allows the game to work with full sound on either LLVM or ASMJIT decoders for the SPU, with no crashing.
