### ISSUE TITLE
[Regression] Multiple games :- SELF file gets moved and renamed to a SAVESTAT file upon execution

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12878]
### Quick summary

When a game is booted, its SELF file gets mistakenly renamed to a SAVESTAT file and then moved to the `rpcs3\savestates` folder.

This causes all subsequent boots of the game to fail for obvious reasons. 

Known games affected include - MGS4 (Digital Version updated to v2.00), God of War: Ascension (Disc Version updated to 1.04), God of War Collection (Disc Version updated to 1.01), and others. 

### Details

First affected build is v0.0.24-14325-ee3e3667_win64 #12870 

Last working build is v0.0.24-14319-4c8630d2_win64 #12867 

### Build with regression

v0.0.24-14325-ee3e3667_win64

### Attach two log files

Broken in 14325
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9851078/RPCS3.log)

Working in 14319
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9851085/RPCS3.log)

### Attach capture files for visual issues

MGS4 SELF file in the original directory.
![image](https://user-images.githubusercontent.com/4345150/197510180-a69e217a-9f77-4ed4-b9bb-acb9bf22b5d4.png)

Which then gets renamed and moved to the savestates directory
![image](https://user-images.githubusercontent.com/4345150/197510402-8b5d9217-8f39-4d4b-ad99-fbd14de4fa11.png)

### System configuration

- SYS: RPCS3 v0.0.24-14325-ee3e3667 Alpha | master
- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 522.25.0.0
- SYS: Firmware version: 4.88

**Comment by AniLeo** [comment]
Updater will rollback now, marked all the builds after the last known good one as broken
The solution is now to move the file back to the game folder and rename it back to MGS4.SELF

**Comment by solarmystic** [comment]
Fixed by #12879.

**Comment by Darkhost1999** [comment]
This doesn't rename the files and restore their location right.

So P.S.A. all effected users are still effected even after this issue is fixed. Just either redump your games or rename and move the .self files back to where they belong originaly with their original names.

The fix fixes the issue occurring again in the future. Doesn't fix the issue occurring in the past by putting the files back because that's just not how it's supposed to work
