### ISSUE TITLE
Deadstorm Pirates sound issues

### ISSUE THREAD

**Issue by dante3732** [RPCS3/rpcs3#13168]
### Quick summary

Music disappears in many places. 
When I played the game previous time, about a year ago, the sound could disappear completely.

### Details

The music sometimes disappeared in those moments when someone started talking.

### Attach a log file

This is the log of the entire completed game.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10350995/RPCS3.log.gz)

### System configuration

Windows 11
AMD Ryzen R5 3600 
16 GB RAM 3200 Mhz
AMD Rx Vega 64 8 GB
GPU driver version 22.11.2

**Comment by dante3732** [comment]
https://github.com/RPCS3/rpcs3/issues/11816

**Comment by SeongGino** [comment]
Seems to be a similar issue to Tales of Xillia games' sound cutting off. Set PPU threads to 1 as a workaround.

**Comment by scju** [comment]
I had sound issues in Deadstorm Pirates when I set the frame limit to 50 (required for Time Crisis 4), but when I set it to 60, the sound issues were solved.

**Comment by dante3732** [comment]
> I had sound stuttering in cut scenes in Deadstorm Pirates when I set the frame limit to 50 (required for Time Crisis 4), but when I set it to 60, the sound stuttering were solved, although the back ground music could sometime disappear in mode selection.
You tried custom build? https://github.com/RPCS3/rpcs3/pull/15538

**Comment by scju** [comment]
> You tried custom build? #15538
No, I used the mainline build. :)

**Comment by digant73** [comment]
is that still an issue?

**Comment by SeongGino** [comment]
Still an issue when PPU Threads are set to 2, yes - just checked to be sure, `0.0.38-`b18a0830

Anecdotally, I've been running RPCS3 on the Steam Deck with fresh configs, and at least Tales of Xillia (the *other* game noted to be affected in the past) does not have this "music cutting off after three seconds sometimes" issue atm. Both of my active setups are Linux systems and happen to be Arch-based, no idea how much that might matter.

**Comment by dante3732** [comment]
It seems that Tekken 6 has an issue with missing music that occurs randomly.

**Comment by Trace6x** [comment]
> Still an issue when PPU Threads are set to 2, yes - just checked to be sure, `0.0.38-`[b18a083](https://github.com/RPCS3/rpcs3/commit/b18a0830f3be7b9a7368344c5e212b00dcf8a0a0)
> 
> Anecdotally, I've been running RPCS3 on the Steam Deck with fresh configs, and at least Tales of Xillia (the _other_ game noted to be affected in the past) does not have this "music cutting off after three seconds sometimes" issue atm. Both of my active setups are Linux systems and happen to be Arch-based, no idea how much that might matter.

Where is the PPU Threads setting located (I can't find it) and what should it be set to?

**Comment by SeongGino** [comment]
> > Still an issue when PPU Threads are set to 2, yes - just checked to be sure, `0.0.38-`[b18a083](https://github.com/RPCS3/rpcs3/commit/b18a0830f3be7b9a7368344c5e212b00dcf8a0a0)
> > Anecdotally, I've been running RPCS3 on the Steam Deck with fresh configs, and at least Tales of Xillia (the _other_ game noted to be affected in the past) does not have this "music cutting off after three seconds sometimes" issue atm. Both of my active setups are Linux systems and happen to be Arch-based, no idea how much that might matter.
> 
> Where is the PPU Threads setting located (I can't find it) and what should it be set to?

It's not in the GUI, but in the config file YAML itself:
```yml
Core:
  PPU Threads: 2 # <- change to 1
...
```

**Comment by digant73** [comment]
please provide an update on this issue

**Comment by SeongGino** [comment]
Still happens as of `0.0.40-19376` when `PPU Threads: 2`
