### ISSUE TITLE
NCAA Basketball 10 Simcast GlitchEnter a title here

### ISSUE THREAD

**Issue by Numberspy** [RPCS3/rpcs3#13284]
### Quick summary

Whenever you jump into a game when using simcast in NCAA Basketball 10 it freezes. 

### Details

The log reads unmapped memory. I have traced the problem back to the LLVM PPU Decoder Recompiler, and when you switch to any of the others it loads in but the game is extremely slow to the point where it is unplayable. I hope that my research can help correct this in the coming updates.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10484845/RPCS3.log)

**Comment by MJB52** [comment]
Also running into this issue

**Comment by evanknight11** [comment]
Have this problem too. Any fixes?

**Comment by Asinin3** [comment]
Needs info. Do you need a save file to launch a match with simcast or can you do it straight after launching the game for the first time without a save? If you need a save, post it. Also give instructions on how to reproduce the issue so if/when a dev tests it they can actually find the problem.

**Comment by NamedVenus6** [comment]
Still a problem.

**Comment by NamedVenus6** [comment]
@Asinin3 any new info on this issue? Anyway I can help I've experienced this as well. I help out with March madness legacy and making the mod for rpcs3. Hoping for a quick fix to this issue :)

**Comment by NamedVenus6** [comment]
@Asinin3 i would like to add. Yes a game file is needed it’s a dynasty mode inside the game.

**Comment by NamedVenus6** [comment]
Any save file in the dynasty mode causes this. I think the issue has to do with the recompiler from the ppu when you switch to interpreter it is fixed. But the game is unplayable on interpreter

**Comment by NamedVenus6** [comment]
It also does this in any mode with simcast.

**Comment by NamedVenus6** [comment]
Sorry about that should have sent it all in one message lol. I go to where save data is located (dev_hdd0/home/00000001/savedata/BLUS31159-dynasty-default) but it then says save file isn't a certain type.

**Comment by NamedVenus6** [comment]
@Asinin3 
[BLUS304440100.zip](https://github.com/RPCS3/rpcs3/files/14732032/BLUS304440100.zip)


This has all the files from my save which you experience the troubles.

crashing at joining a game from simcast and crashing while editing certain teams rosters. 


Seems to be caused by the PPU when switch over to the interpreter instead of recomplier issues are fixed but game is unplayable.

**Comment by MasonD552** [comment]
Is there any solution to this issue? I have been trying anything to not have the game crash when joining game from Sim cast. I want to be able to play how the game is intended.

**Comment by Breakfast101** [comment]
@MasonD552 

Did a solution come up in any testing you did after, I cant seem to get anything to work

**Comment by ChwaraeTeg** [comment]
Still an issue in RPCS3 v0.0.40-19252-96f73f44

Default settings (LLVM Recompiler) with the crash:
[NCAA10_Recomp.log.gz](https://github.com/user-attachments/files/27099421/NCAA10_Recomp.log.gz)
`Thread (SimulationThread) [0x00246820]} VM: Access violation writing location 0x5be20000 (unmapped memory)`

PPU Static Interpreter (no crash):
[NCAA10_PPUInterp.log.gz](https://github.com/user-attachments/files/27099428/NCAA10_PPUInterp.log.gz)

BTW it took me a while to figure out the steps to cause the crash - here's what I did for reference:
https://www.youtube.com/watch?v=fRJxt_ciy3I
