### ISSUE TITLE
[Regression] NARUTO Shippuden: Ultimate Ninja STORM 2 Graphical issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13686]
### Quick summary

The game suffers from a graphical issue

### Details

when testing this game I ran into an issue where kakashi chidori attack seems to have noticeable artefacts which started after happening when pr https://github.com/RPCS3/rpcs3/pull/13046 was merged
Masters:
![NPEB90241_screenshot_2023_01_21_00_42_02](https://user-images.githubusercontent.com/71127352/232556593-6fd11034-36d0-4fe3-894d-80394f0eaa22.png)

25-14454:
![NPEB90241_screenshot_2023_04_17_17_54_18](https://user-images.githubusercontent.com/71127352/232556604-9228208a-501b-4be1-bf8b-4373ace8c6b6.png)

### Build with regression

0.0.25-14465

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11253383/RPCS3.log.gz)
[RPCS3Masters.log.gz](https://github.com/RPCS3/rpcs3/files/11253465/RPCS3Masters.log.gz)

### Attach capture files for visual issues
[Masters](https://drive.google.com/file/d/1oxUo1UBs-6HtcdF-JZs-pHps3729T3Nc/view?usp=share_link)
[0.0.25-14454](https://drive.google.com/file/d/1JEy4kGAEyHxS8qbVJKIC-tNDV3PBfIT8/view?usp=share_link)

### System configuration
RPCS3 v0.0.27-14878-b7066586 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by kd-11** [comment]
Pretty sure the only solution is to switch precision to Low (or offer a toggle that essentially does the same thing). This is a hardware issue, nothing we do will ever fully work around it for all scenarios.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/13690

**Comment by kd-11** [comment]
I suppose a checkbox in advanced tab will have to do.

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/13798

**Comment by Triticum0** [comment]
Tested and the issue is still present on Ultra and high
High
![NPEB90241_screenshot_2023_05_02_15_35_43](https://user-images.githubusercontent.com/71127352/235701364-1ba1597a-4f43-4a0d-a6ab-a437dc2dfba1.png)


Ultra
![NPEB90241_screenshot_2023_05_02_15_39_04](https://user-images.githubusercontent.com/71127352/235701174-e0f5e8a7-0372-428f-8070-bc9f8ecdd3f9.png)

[NARUTO Shippuden: Ultimate Ninja STORM 2.log.gz](https://github.com/RPCS3/rpcs3/files/11374516/NARUTO.Shippuden.Ultimate.Ninja.STORM.2.log.gz)

**Comment by kd-11** [comment]
> Tested and the issue is still present on Ultra and high High ![NPEB90241_screenshot_2023_05_02_15_35_43](https://user-images.githubusercontent.com/71127352/235701364-1ba1597a-4f43-4a0d-a6ab-a437dc2dfba1.png)
> 
> Ultra ![NPEB90241_screenshot_2023_05_02_15_39_04](https://user-images.githubusercontent.com/71127352/235701174-e0f5e8a7-0372-428f-8070-bc9f8ecdd3f9.png)
> 
> [NARUTO Shippuden: Ultimate Ninja STORM 2.log.gz](https://github.com/RPCS3/rpcs3/files/11374516/NARUTO.Shippuden.Ultimate.Ninja.STORM.2.log.gz)

Use the PR build. Ultra doesn't do anything anymore (in the PR build). The code is not yet pushed to master.

**Comment by MSuih** [comment]
You can get the pr build by following [these instructions](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?)

**Comment by Triticum0** [comment]
That was the pr build. I retested it and no change with and without the shader cache.
[Ultimate Ninja STORM 2.log.gz.log.gz](https://github.com/RPCS3/rpcs3/files/11375573/Ultimate.Ninja.STORM.2.log.gz.log.gz)

`·W 0:00:00.132072 GUI: Experimental Build Warning! Build origin: RPCS3/rpcs3/pull/13798`

**Comment by kd-11** [comment]
Hmm. Indeed. Something is very wrong with this game.

**Comment by Triticum0** [comment]
Do you need a rsx capture?

**Comment by kd-11** [comment]
No, that's ok. I already have a capture from earlier.

**Comment by kd-11** [comment]
Ok, this is something different entirely. It also happens on AMD.

**Comment by Triticum0** [comment]
Retested with v0.0.30-15914-2a1af17f. No changes

**Comment by Triticum0** [comment]
retested no change

**Comment by digant73** [comment]
@kd-11 a reminder in case you forgot to test

**Comment by kd-11** [comment]
Thanks. I need to find a more precise version of fp16 conversion that matches PS3. Maybe for 'Ultra' shader precision only since performance loss is expected.

**Comment by digant73** [comment]
@Triticum0 please provide an update on this issue. maybe a z-fighting issue
