### ISSUE TITLE
[Regression] TLoU and GT6 bugs after #14104

### ISSUE THREAD

**Issue by Linear524** [RPCS3/rpcs3#14142]
### Quick summary

TLoU and GT6 have bugs after #14104
TLoU shadowmaps are screwed (projected shadows from dynamic light sources).
GT6 have weird green pixelated garbage at lower right corner.
Screensots attached.

### Details

![111](https://github.com/RPCS3/rpcs3/assets/84367301/806e6400-37b5-4c6e-a741-65c72815a15d)
![112](https://github.com/RPCS3/rpcs3/assets/84367301/065c0b20-0799-4a03-94c6-2076afd0cc39)
![113](https://github.com/RPCS3/rpcs3/assets/84367301/c63516e6-57fa-4141-912c-6dabe9d35876)
![114](https://github.com/RPCS3/rpcs3/assets/84367301/c4a3f047-33b0-42c5-904f-8dfea685e326)
![115](https://github.com/RPCS3/rpcs3/assets/84367301/b67da3dc-780f-4a1b-911e-70062bacd770)
![116](https://github.com/RPCS3/rpcs3/assets/84367301/b66e2a90-6cbd-4e8e-ad04-818565ce95eb)

### Build with regression

#14104

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11970312/RPCS3.log)

### Attach capture files for visual issues

https://drive.google.com/file/d/1eKeW9HAsyOLNFaEnsmFNYMFd_mlLtG5N/view?usp=sharing

### System configuration

    SYS: RPCS3 v0.0.28-15306-d41fe80b Alpha | master
    SYS: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz | 14 Threads | 31.83 GiB RAM | TSC: 2.594GHz | AVX+ | FMA3 | TSX disabled by default
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2023-07- 5T23:24:13
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1080' running on driver 531.61.0.0
    SYS: Firmware version: 4.87

### Other details

I use WCB + RCB + WDB + RDB and native 720p mode.
For TLoU I use only RSX lighting patch and no other patches.

**Comment by AniLeo** [comment]
Probably fixed by 14140, try again

**Comment by solarmystic** [comment]
Unable to reproduce this in TLOU using the latest master which has #14140 already merged, it is quite possible that this issue has already been resolved in that PR for TLOU. 

![image](https://github.com/RPCS3/rpcs3/assets/4345150/96bdb31e-54aa-4e98-a211-da00c0a1780b)

**Comment by Linear524** [comment]
![2364](https://github.com/RPCS3/rpcs3/assets/84367301/771f0fd9-2844-450d-8d29-428d176bf180)
![2365](https://github.com/RPCS3/rpcs3/assets/84367301/631f49d0-528b-48f9-a4d3-8ecfd302da72)
![2366](https://github.com/RPCS3/rpcs3/assets/84367301/317bcd5c-006f-43a6-8c7a-c146670433e6)
Sorry, but it still broken...
14140 have not fixed this...
@solarmystic
On your screen I see no dynamic shadows at all, that's why you don't see that issue...
Maybe you are using some MLAA skipping pathes or resolution scaling ?
Also I'm using all accuracy settings, like RCB+RDB+WCB+WDB to reproduce all effects...

**Comment by Megamouse** [comment]
Can you please upload a new log with logging enabled?
It seems you had set "Disable all logging" in your global config.

**Comment by Linear524** [comment]
Sure, here it is:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11981691/RPCS3.log)

**Comment by Linear524** [comment]
Also:
here is the screenshots from version 15277, which have all projected shadows propertly rendered
![BCES01585_screenshot_2023_07_07_17_54_05](https://github.com/RPCS3/rpcs3/assets/84367301/64f2bd33-132a-4d54-bf8a-ac60fb5ee00d)
![BCES01585_screenshot_2023_07_07_17_54_09](https://github.com/RPCS3/rpcs3/assets/84367301/c61dc844-bc1b-470f-ab86-e757f78d0707)
![BCES01585_screenshot_2023_07_07_17_56_07](https://github.com/RPCS3/rpcs3/assets/84367301/2b5d5d96-6bc1-48e8-8030-4d3fde561f0e)
![BCES01585_screenshot_2023_07_07_17_57_04](https://github.com/RPCS3/rpcs3/assets/84367301/dcecae67-8e70-4a9d-afde-eb437ca3b921)
![BCES01585_screenshot_2023_07_07_17_57_28](https://github.com/RPCS3/rpcs3/assets/84367301/a6e6b82f-88ee-41c1-86a3-c0f1de233b3a)

Please look how Sarah casts her shadows and how dynamic light sources are working... They are broken in latest revisions.

**Comment by Linear524** [comment]
And here is RSX capture from v.15277 with working shadows and lighting:
https://drive.google.com/file/d/1_HRCP0ht3ZmSeHMOc9tUkads8uOWTNFV/view?usp=sharing

**Comment by kd-11** [comment]
@Linear524 Let's start with the easy one - explain how to reproduce the green blotch on GT6. I'm not able to reproduce that one.

**Comment by Linear524** [comment]
I'm just using my regular max-accuracy settings:
WCB+RCB+WDB+RDB, also I using Antialiasing on Auto, Shader Quality always on Ultra on every game, Zcull Accuracy on Precise, and Native 720p resolution without any tweaks...
All latest builds shows this green pixelated mess on lower right corner for GT6...

**Comment by kd-11** [comment]
Could be a pascal-specific problem. Which track did you test with?

**Comment by Linear524** [comment]
Every track, but mostly Nurburgring, second option

**Comment by kd-11** [comment]
Verified the tlou bug, it's caused by projected coordinate scaling with the new setup. We need some more work around that special case.

**Comment by Clarke2131** [comment]
i've noticed something, on build 15277 tlou works fine but when i tested on 15302 and later builds the marks on the screen appears

issue https://youtu.be/jZq87fz0gLc
works fine https://youtu.be/hfzT6jznRrk

my specs are: ryzen 5 5600, 32GB, RX570 (23.5.2)

[RPCS3 15277.log](https://github.com/RPCS3/rpcs3/files/11987065/RPCS3.15277.log)
[RPCS3 15302.log](https://github.com/RPCS3/rpcs3/files/11987066/RPCS3.15302.log)

![1 0 0 28-15277](https://github.com/RPCS3/rpcs3/assets/24876699/611af8a5-048d-49c6-863f-bc8646627cd7)
![2 0 0 28-15277](https://github.com/RPCS3/rpcs3/assets/24876699/4a40361f-a575-4037-becc-2ebbd1b5b511)
![2 0 0 28-15302](https://github.com/RPCS3/rpcs3/assets/24876699/d6bbbb7e-8af0-43fb-93db-7ff3d29ec31b)
![1 0 0 28-15302](https://github.com/RPCS3/rpcs3/assets/24876699/8a8a0aa5-b362-4838-a04d-aeab8b8d9b36)

**Comment by kd-11** [comment]
TLOU shadow issue should be fixed by https://github.com/RPCS3/rpcs3/pull/14149

**Comment by kd-11** [comment]
@Clarke2131 There have been many fixes since 15302 specifically to fix those artifacts. The issue is only relevant if it still happens after 15311

**Comment by Clarke2131** [comment]
fair enough my bad 😅, here is the 15318

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11987178/RPCS3.log)


![FPS_ 29 99 _ Vulkan _ 0 0 28-15318 _ The Last of Us™  BCUS98174  07_07_2023 10_39_13 PM](https://github.com/RPCS3/rpcs3/assets/24876699/933d460e-fc44-4d87-88cb-2e57b4aea05f)


![FPS_ 29 92 _ Vulkan _ 0 0 28-15318 _ The Last of Us™  BCUS98174  07_07_2023 10_40_34 PM](https://github.com/RPCS3/rpcs3/assets/24876699/2b6041ae-616b-4df9-aadf-0370a6e3ea14)

**Comment by readywer** [comment]
The same pr caused a regression on GT5 too. But it only happens during b-spec default view and in the race menu where you see the track form above.
![Képernyőfelvétel (342)](https://github.com/RPCS3/rpcs3/assets/90259918/4c0c5afe-9383-4345-b499-409966a1eab9)
![Képernyőfelvétel (341)](https://github.com/RPCS3/rpcs3/assets/90259918/9b67b4dd-7880-4581-a621-b2a916ad3396)

**Comment by kd-11** [comment]
@Linear524 The PR got improvements and was merged. Please retest.

**Comment by Linear524** [comment]
Thanks KD-11 ! :)
TLoU shadows fixed )
Tonight I will retest GT6 and close this issue :)

**Comment by Linear524** [comment]
Hi KD-11 ! )
GT6 still have those green pixelated garbage on lower left part of screen, but if I disable WCB+RCB+WDB+RDB and enable Force CPU Blit instead = those green garbage is gone ! A lot of PostProcessing FX is gone too without WCB, but hey - it is still playable  :>
So I'm sure it is related to overall broken WCB function and I'm also sure it will be gone once you finish #10208...
I'm closing this current issue.

P.S. - is it possible for you to complete #10208 this year ?)) I know it is not so simple, but a lot of titles will benefit from this fix :)
