### ISSUE TITLE
Need for Speed: Rivals - Behaves differently when using OpenGL

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14797]
### Quick summary

Using OpenGL renderer behaves differently than Vulkan.

### Details

On OpenGL, the game shows a black screen before selecting the start button, which makes it harder to see during gameplay since it only shows black screen, and you can hear the audio functioning normally.

Using Vulkan doesn't have this issue.

OpenGL:
![Need for Speed Rivals OpenGL](https://github.com/RPCS3/rpcs3/assets/125112932/4acc1f38-4e02-4777-b2a3-a0c48ecee34b)

Vulkan:
![Need for Speed Rivals Vulkan](https://github.com/RPCS3/rpcs3/assets/125112932/6c839cbd-3ca3-4856-9b36-c0c4754f100d)

### Attach a log file

[OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/13257229/OpenGL.log.gz)

[Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/13257230/Vulkan.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 546.1.0.0 | Windows 10 Pro 22H2

**Comment by Ordinary205** [comment]
This issue also happens on Split/Second when enabling the OpenGL renderer.

OpenGL:
![Split-Second OpenGL](https://github.com/RPCS3/rpcs3/assets/125112932/3a9c39d8-d0d7-4048-8034-5c2e954f068f)

Vulkan:
![Split-Second Vulkan](https://github.com/RPCS3/rpcs3/assets/125112932/fe2fac23-32eb-4b65-9dd8-0c66461f1518)

[OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/13311137/OpenGL.log.gz)
[Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/13311138/Vulkan.log.gz)

**Comment by kd-11** [comment]
I found a nasty OGL bug that is fixed in https://github.com/RPCS3/rpcs3/pull/14834. Try that, maybe it fixes this problem.

**Comment by kd-11** [comment]
I cannot reproduce this one.
![image](https://github.com/RPCS3/rpcs3/assets/15904127/b7a96798-46a5-4b50-8189-4b088f17416b)

**Comment by kd-11** [comment]
We don't control windowed and fullscreen behavior, rpcs3 uses the same code regardless. Whether you're in windowed/borderless/fullscreen is superficial, with the real differences being controlled by the OS and GPU drivers. You should reinstall your drivers and see if it goes away.

**Comment by Ordinary205** [comment]
> We don't control windowed and fullscreen behavior, rpcs3 uses the same code regardless. Whether you're in windowed/borderless/fullscreen is superficial, with the real differences being controlled by the OS and GPU drivers. You should reinstall your drivers and see if it goes away.

I've tried reinstalling my NVIDIA driver, but sadly it's still an issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13626689/RPCS3.log.gz)

**Comment by digant73** [comment]
@Ordinary205 is that still an issue?
