### ISSUE TITLE
[Pinball Arcade] Broken lighting with default resolution (720p), but the bug is fixed by using any other resolution (480p, 1080p)

### ISSUE THREAD

**Issue by Zach-star1** [RPCS3/rpcs3#14858]
### Quick summary

In the Pinball Arcade the lighting effect on the table is a crucial part of the experience. When starting the game using the default resolution, the lighting effects are broken and the tables look very dark.
By changing the resolution to any other value (480p, 1080p...) the bug is completely fixed and the tables look bright as they should

### Details

This bug occurs with both OpenGL and Vulkan in the exact same way

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13518198/RPCS3.log.gz)

I first opened the application at default resolution (720p), I started a game on "Tales of the Arabian Night" and then I closed it
--> the table looked dark

So, I changed the resolution to 480p, then opened again Pinball arcade and started a game on "Tales of the Arabian Night"
 --> the lighting on the table was completely fixed

### Attach capture files for visual issues

<img width="960" alt="normal ex" src="https://github.com/RPCS3/rpcs3/assets/139509866/09eb52df-d7c4-45e6-bac0-4242181d72cf">
game at default resolution, the table looks dark

<img width="960" alt="low res ex" src="https://github.com/RPCS3/rpcs3/assets/139509866/6b4909ba-4cf0-44cc-bc7a-f8a65c148d8f">
game at 480p, the table lighting is completely fine

### System configuration

CPU: i7-8565u
GPU: NVIDIA Geforce MX130
GPU Drivers: 537.13

### Other details

Thanks to all the developers for the hard work :)

**Comment by AniLeo** [comment]
Missing .rrc capture file

**Comment by Zach-star1** [comment]
I've been testing the game for a while and I found a solution to the broken lighting.
It needs to be enabled both "Write color buffers" and "Read color buffers", so that even at standard res the game looks just fine.

Do you it should be added to the recommended settings in the wiki?
If needed I can provide screenshots and the .rcc file of the gameplay

**Comment by digant73** [comment]
here main developers can provide an answer and possibly close the issue

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by Zach-star1** [comment]
I'm terribly sorry if I couldn't update you but I've started working and I've had very few spare time. I've just tried the game with the new update and there are some mixed news.
When playing the game at standard settings the lighting is still broken, but when enabling write color buffers + read color buffers (in the advanced setting) the colors and the lights get much better.
It's still not completely fixed, but it's definitely an improvement. To me, it looks like the game provides color/light information in ways that the emulator doesn't capture yet. Enabling the color buffers helps capturing some of this info, but not all.


Now I don't have time, but in the next days I can upload some photos of how it looks now and how it should look on the real hardware. + properly testing the game and attaching the .rrc capture file

**Comment by smbhax** [comment]
_The Pinball Arcade_ - U/C region (NPUB30713)

### Details

The visual glitches manifest differently at 720p and 1080p (the PS Store entry for the game says it supports "HDTV screen resolution 720p, 1080i, 1080p"). And there are two partial workarounds: one that works well for 720p, and one that works pretty well for 1080p.

**Video showing the issue and workarounds**: https://youtu.be/X7Uw5MN559k

**720p**

1) Create a new default custom configuration (I then have to set "Configuration - Advanced - Exclusive Fullscreen Mode - Prefer borderless fullscreen" to get an OBS video capture)
2) Start the game (I'm using the plain demo version, no additional downloaded DLC)
3) Press X twice to pass the title/intro screens, again to choose "Previous Seasons," and again to choose "Season One"
4) Press Up once, then X once to select "Ripley's Believe It or Not" table, then X again to skip the intro screen
== At the Ripley's demo flyover screen, notice that the table is dark, as if in shadow:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/65046f06-e25d-4b33-ab63-5cebf039f3ae" />

720p log file:

[Pinball Arcade \[NPUB30713\].log_720.gz](https://github.com/user-attachments/files/28622466/Pinball.Arcade.NPUB30713.log_720.gz)

720p RCC file:

[NPUB30713_20260604200944_capture.720.rrc.gz](https://github.com/user-attachments/files/28622474/NPUB30713_20260604200944_capture.720.rrc.gz)

**720p workaround (noted by OP above)**

1) Check the boxes for "Configuration - GPU - Write Color Buffers" and "Configuration - Advanced - Read Color Buffers"
2) Save custom configuration and start the game, etc
== The table is no longer dark:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/203ad400-3f4b-497d-9e43-f55cd46c6927" />

**1080p**

1) Create a new default custom configuration
2) Set "Configuration - GPU - Default Resolution - 1080p"
3) Follow steps 2-4 for 720p above
== At the Ripley's demo flyover screen, notice that although the table is no longer dark, there is a dark bar along the bottom of the screen, and a bright flickering effect over the lower third of the screen (this flickering varies by table, and on some tables--such as the Gottlieb DLC "Big Shot" table--is significantly distracting during gameplay):

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6cb2b270-9add-4bb0-a609-fa7e227bbb9a" />

Actual PS3:

<img width="1920" height="1083" alt="Image" src="https://github.com/user-attachments/assets/3bc28eb7-61e5-40f0-900b-bd1ef2046c5b" />

1080p log file:

[Pinball Arcade \[NPUB30713\].log_1080.gz](https://github.com/user-attachments/files/28622479/Pinball.Arcade.NPUB30713.log_1080.gz)

1080p RCC file:

[NPUB30713_20260604201133_capture.1080.rrc.gz](https://github.com/user-attachments/files/28622487/NPUB30713_20260604201133_capture.1080.rrc.gz)

**1080p workaround**

The "Read Color Buffers" / "Write Color Buffers" settings used for the 720p workaround above cause the game to run in slow motion at 1080p. However, a different setting, which has no apparent effect at 720p, resolves the flickering at 1080p, without noticeable performance impact:

1) Check the box for "Configuration - Advanced - Allow Host GPU Labels (Experimental)"
2) Save custom configuration and start the game, etc
== Although the dark bar at the bottom of the screen remains, the flickering in the lower left third of the screen is gone:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e1eb14bf-2309-4d1a-9f95-5e95fb63afee" />

### System configuration

Operating System:
Windows 11

CPU:
i7-10750H

GPU:
GTX 1660 Ti
Driver version 596.49

Other:
16 GB RAM
S271HL NVIDIA High Definition Audio

**Comment by digant73** [comment]
please an update on current build
