### ISSUE TITLE
Warhawk Clouds Are Flickering Black Squares

### ISSUE THREAD

**Issue by ManGuyNY** [RPCS3/rpcs3#15872]
### Quick summary

This appears to be the same issue as shown in #14365 . Seems to still be present for me after #15743 .

### Details

The clouds in-game are giant black squares that flicker as the camera is turned.

### Attach a log file

**Log file:**
[RPCS3.log.gz](https://github.com/user-attachments/files/16423252/RPCS3.log.gz)

### Attach capture files for visual issues

**RSX Capture:**
[BCUS98117_20240730025735_capture.rrc.gz](https://github.com/user-attachments/files/16423463/BCUS98117_20240730025735_capture.rrc.gz)

### System configuration

AMD Ryzen 7 7700X 8-Core Processor | 16 Threads | 31.22 GiB RAM | TSC: 4.500GHz | AVX-512+ | FMA3
AMD Radeon RX 6800 XT Running the latest driver (24.7.1)
Windows 11

**Comment by kd-11** [comment]
Is this a regression? Please check if it ever ran correctly and let me know when it broke if so. The other ticket was listed as having been working fine in 0.0.28-15303 but broke in the next build, so that's a place to start.
Running your capture locally shows a very different output (with streaks running across the sky). The input data is cursed as well which makes me question it's validity. Try with MSAA off for comparison as well.

**Comment by ManGuyNY** [comment]
Ok, something is definitely weird on my end. I cleared shader cache just for the hell of it before testing again, and it seems this causes the game to crash upon trying to load into a match. However, running the game again after the crash allows it to load in, but with the messed up clouds.

Log for that crash: 
[Warhawk [BCUS98117]_crash.log.gz](https://github.com/user-attachments/files/16567641/Warhawk.BCUS98117._crash.log.gz)


MSAA off exhibits the same behavior on the latest build. I will try 0.0.28-15303 later this evening when I have some more time.

**Comment by ManGuyNY** [comment]
I can confirm both issues, the crash & the black clouds, are not present on 0.0.28-15303.

**Log:**
[RPCS3_15303.log.gz](https://github.com/user-attachments/files/16568034/RPCS3_15303.log.gz)

**RSX Capture:**
[BCUS98117_20240809212105_capture.rrc.gz](https://github.com/user-attachments/files/16568051/BCUS98117_20240809212105_capture.rrc.gz)

**Comment by kd-11** [comment]
Ok, so this is a regression investigation. Thanks for confirming.

**Comment by nelinnemann** [comment]
Can confirm that build 15227 has no issues with black boxes, whereas both 16882 and 16932 shows same black flickering boxes.

**Comment by SecularSteve** [comment]
> Can confirm that build 15227 has no issues with black boxes, whereas both 16882 and 16932 shows same black flickering boxes.

What about with Starhawk?

#11877

That game seems to have much of the same issues.

**Comment by jeremybris** [comment]
I am also getting the crashing regression, and as mentioned [here](https://github.com/RPCS3/rpcs3/issues/8440#issuecomment-1074504602), the black boxes was previously fixed by [#11665](https://github.com/RPCS3/rpcs3/pull/11665).

**Comment by DaveKap** [comment]
I've got the same black box issue in 0.0..34-17170

**Comment by kd-11** [comment]
This never worked properly. The glitch was just invisible due to a bug in MSAA wrapping code that was fixed. You can confirm by enabling SRM or forcing hardware MSAA resolve or disabling MSAA altogether even in the fixed builds.
A second bug has been identified, fixed in https://github.com/RPCS3/rpcs3/pull/16540. However, this addresses an internal MSAA problem and does not make the boxes go away.
The boxes seem to be at least partially caused by completely broken lookup table data, though this could just be a side-effect of doing RSX capture. I need to look deeper at the broken shader to figure it out.

**Comment by digant73** [comment]
is that still an issue?

**Comment by ManGuyNY** [comment]
@digant73 I can confirm I still experience this on build 0.0.38-18406 

<img width="2560" height="1397" alt="Image" src="https://github.com/user-attachments/assets/c2407c9a-6f6f-4af9-bad2-b4a1aaa27761" />
