### ISSUE TITLE
gl: Low resolution scale crash due to too many mipmaps on a small texture

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#15985]
NieR Replicant crashes on OpenGL with `Unhandled GL format 0x80E1` ([GL_BGRA_EXT](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_format_BGRA8888.txt))

https://github.com/RPCS3/rpcs3/blob/1c16ada670bb396e98b33ec4510c1b3efb534724/rpcs3/Emu/RSX/GL/glutils/image.cpp#L118

Call to the function has the following parameters:
`texture(target=0xDE1, width=194, height=194, depth=1, mipmaps=9, sized_format=0x80E1)`

GL validation layers output before the crash:
`RSX: [DEBUG_OUTPUT] [API] [ERROR] [2]: GL_INVALID_ENUM in glDisable(GL_DEPTH_CLAMP)`
`RSX: [DEBUG_OUTPUT] [API] [ERROR] [2]: GL_INVALID_OPERATION in glTexStorage2D(too many levels for max texture dimension)`

How to reproduce:
1. Set Resolution Scale to 38%
2. Boot NieR Replicant on OpenGL
3. Once you reach the title screen, press start and the game crashes

Driver tested: V3D 7.1.7 (OpenGL ES 3.1) with overrides `MESA_GLSL_VERSION_OVERRIDE=4.5 MESA_GLSL_VERSION_OVERRIDE=450`

**Comment by kd-11** [comment]
We don't actually pass GL_BGRA8 to any OpenGL functions. Because it is not widely supported enough, it is emulated as GL_RGBA8. The real culprit here is that for whatever reason, the image has been created but calling the glGetTextureParameter calls are returning 0 for channels. That needs investigation on it's own. Maybe the texture is too small? Like 0x0 or something.

**Comment by AniLeo** [comment]
GL validation layers output:
`RSX: [DEBUG_OUTPUT] [API] [ERROR] [2]: GL_INVALID_ENUM in glDisable(GL_DEPTH_CLAMP)`
`RSX: [DEBUG_OUTPUT] [API] [ERROR] [2]: GL_INVALID_OPERATION in glTexStorage2D(too many levels for max texture dimension)`

Function call is:
`texture(target=0xDE1, width=194, height=194, depth=1, mipmaps=9, sized_format=0x80E1)`

**Comment by kd-11** [comment]
@AniLeo I can't reproduce this one. Maybe I fixed it somewhere along the way?

**Comment by AniLeo** [comment]
Can't boot the game at all with OpenGL with radeonsi at the moment, discussing internally to see what's going on

However, I can see the issue manifest through the validation layers in Vulkan, which does not crash despite the issue

- E RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkImageCreateInfo-mipLevels-00958 ] | MessageID = 0xc481e464 | vkCreateImage(): pCreateInfo pCreateInfo->mipLevels must be less than or equal to floor(log2(max(pCreateInfo->extent.width, pCreateInfo->extent.height, pCreateInfo->extent.depth)))+1. The Vulkan spec states: mipLevels must be less than or equal to the number of levels in the complete mipmap chain based on extent.width, extent.height, and extent.depth (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageCreateInfo-mipLevels-00958) x8

**Comment by AniLeo** [comment]
This issue is currently blocked by #16943 as the game doesn't boot on OpenGL when using Linux (x64/arm64) regardless of GPU vendor

**Comment by AniLeo** [comment]
I can still reproduce, tested with v0.0.40-19167-c1fed1eb `PR #18522`. Game crashes on title screen using OpenGL and radeonsi.

AMD Radeon RX 7900 XTX (RADV NAVI31) running on driver 26.0.2

**Comment by AniLeo** [comment]
Can still reproduce on v0.0.42-19803

AMD Radeon RX 7900 XTX (RADV NAVI31)' running on driver 26.1.6
