### ISSUE TITLE
Resistance: Fall Of Man Demo [BCES00001] Vulkan looks a lot more blurry vs OpenGL 

### ISSUE THREAD

**Issue by Iordan-Iulian-Bogdan** [RPCS3/rpcs3#16055]
### Quick summary

There is a visual disparity between Vulkan and OpenGL

### Details

The game looking significantly more blurry on Vulkan whereas on OpenGL it looks much sharper, looks like some kind of scaling issue of the final output. 

Vulkan : 
<img width="1280" alt="Vulkan" src="https://github.com/user-attachments/assets/9a94a1da-0f44-47ab-8528-5441d056cf0f">
OpenGL : 
<img width="1280" alt="OpenGL" src="https://github.com/user-attachments/assets/99fe345c-6f51-4ddb-94a3-a38e733d062b">

Using nearest or bilinear scaling doesn't seem to make a difference, neither does trying to run the game at a higher resolution it always looks ever so slightly more blurred out on Vulkan.

### Attach a log file

[Resistance Fall of Man [BCES00001].log.gz](https://github.com/user-attachments/files/16917425/Resistance.Fall.of.Man.BCES00001.log.gz)

### System configuration

- SYS: RPCS3 v0.0.33-16904-9385f067 Alpha | master
- SYS: AMD Ryzen 9 7900 12-Core Processor | 24 Threads | 31.12 GiB RAM | TSC: 3.693GHz | AVX-512+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 26120, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2024-09-07T12:53:45
- RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 7900 XT' running on driver 2.0.302
- RSX: Found Vulkan-compatible GPU: 'AMD Radeon(TM) Graphics' running on driver 2.0.302
- SYS: Firmware version: 4.91

**Comment by Hamof1** [comment]
Are you sure that's not just the anti-aliasing?

**Comment by Iordan-Iulian-Bogdan** [comment]
Nope, every setting is default except for the renderer.

**Comment by Hamof1** [comment]
When you switch from Vulkan to OpenGL, it grays out the anti-aliasing option. I'm not sure if it's locked on or off though.

**Comment by Iordan-Iulian-Bogdan** [comment]
OK so it does seem to be the anti aliasing option, on OpenGL it becomes greyed out but it says disabled, on Vulkan the default setting is "Auto" but when disabled the game looks the same as on OpenGL.

I still think something is wrong here, the game looks abnormally blurry, I don't remember this game having any form of anti aliasing but maybe I am wrong, it certainly doesn't look like MSAA to me. It also shows some weird artifact outlines on transparency effects like smoke : 
![image_2024-09-07_144025285](https://github.com/user-attachments/assets/9ab5f8e3-9c66-4a9a-8a92-5ed187850632)

I am not sure what the "Auto" setting does, it says it emulates multisampling layout, so I guess this is not how the game is originally meant to look like ? It's confusing that this is the default option if that's the case.

**Comment by kd-11** [comment]
Go into advanced tab and force MSAA hardware resolve. It should solve the issue but may have a massive performance cost.

**Comment by Iordan-Iulian-Bogdan** [comment]
It looks exactly the same with MSAA hardware resolve checked.

**Comment by kd-11** [comment]
In that case it means our software MSAA is hardware-accurate. Game's just blurry by default I guess. Try upping the resolution scaling to something higher is your only option.

**Comment by Iordan-Iulian-Bogdan** [comment]
It definitely looks better if I run it at 1440p for example but to my eyes it still looks sharper and no weird outlines when AA is disabled on the same resolution especially on my native 1440p display.

I suppose this issue can be closed, I can just disable the AA as I didn't understand why the game looked blurrier on Vulkan, it's still not clear to me if this option is meant to emulate MSAA on top of/or overwrite what the game original uses. Perhaps the description should make this more clear.

**Comment by kd-11** [comment]
>  if this option is meant to emulate MSAA on top of/or overwrite what the game original uses

Nope, it emulates the original PS3 game's MSAA behavior. We do not yet support replacing the MSAA sample count. Without the hardware resolve we do a software approximation of the filtering, with hardware we let your GPU do it instead.
MSAA is blurry in general due to blending of the render planes if the developer is not careful, so some softness is not unexpected. Such is the price of typical AA solutions.
