### ISSUE TITLE
MGS4 water effect incorrect

### ISSUE THREAD

**Issue by Mr-Beacon00** [RPCS3/rpcs3#16841]
### Quick summary

every area with water got graphics problem, water wave is not correct, also too bright.

### Details

water don't have correct brightness and wave effect. i can't find any way to fix this.
I set the emulator according to rpcs3 wiki
I tried NPUB31633 and 25th version BLUS30109, they're no different on water

here's settings i tried and not working:
Write Color Buffer: OFF or ON
Strict Rendering Mode: ON or OFF
ZCULL Accuracy: Precise
All 4 Shader Mode
Renderer: OpenGL
Accurate XFloat
Uncheck all patches even Canary patches
Delete cache folder

here's emulator's graphics
![Image](https://github.com/user-attachments/assets/a460ad1a-c2f9-4435-a1c0-a1ca8a60a18b)
![Image](https://github.com/user-attachments/assets/508b7fa3-1cd1-4cfb-a2b0-2ae02ade4f1e)

here's on real ps3
![Image](https://github.com/user-attachments/assets/55b668b5-c4f2-4ba7-bc37-fdb1f751b163)
![Image](https://github.com/user-attachments/assets/08791845-e059-43f7-9a2f-a9eae1bf51f3)

### Attach a log file

[METAL GEAR SOLID 4 GUNS OF THE PATRIOTS \[NPUB31633\].log.gz](https://github.com/user-attachments/files/19157059/METAL.GEAR.SOLID.4.GUNS.OF.THE.PATRIOTS.NPUB31633.log.gz)

### Attach capture files for visual issues

[NPUB31633_20250310144434_capture.rrc.gz](https://github.com/user-attachments/files/19157064/NPUB31633_20250310144434_capture.rrc.gz)

### System configuration

OS: Windows 10 LTSC 21H2 19044.5487
CPU: AMD Ryzen 5 4600H with Radeon Graphics
GPU: NVIDIA GeForce GTX 1650
GPU Driver: 572.70.0.0

**Comment by JimScript** [comment]
This looks like it could be similar to the Insomniac games water issue(#12439).

**Comment by cipherxof** [comment]
For the record, this has always been an issue in RPCS3. I don't recall any build where the water ever rendered correctly.

**Comment by kd-11** [comment]
It's a understood issue, but hw tests don't align with what the games seem to want. Usually just means we're missing something but these same games have no PC version to compare to.

**Comment by cipherxof** [comment]
> It's a understood issue, but hw tests don't align with what the games seem to want. Usually just means we're missing something but these same games have no PC version to compare to.

There actually is a PC version of the MGS4 engine with Metal Gear Arcade, which is a spinoff of Metal Gear Online. MGO also exhibits the same water rendering issue in RPCS3, and we can directly compare it against MGAC. Although, I am having trouble attaching RenderDoc to MGAC without it crashing.

![Image](https://github.com/user-attachments/assets/7776169a-ff97-466f-9ebc-81eb19a416a9)

![Image](https://github.com/user-attachments/assets/bb4a9c13-4a91-4a03-934a-198ec9ce8e39)

Furthermore, the exact same stage displayed in the original post also renders incorrectly in MGO, however there is a separate game mode that loads a different set game data than the rest of the game modes, and somehow the water seems to render differently there. It's possible it's just missing a texture or something, as it still doesn't look correct.

**Broken Rendering:**
![Image](https://github.com/user-attachments/assets/14415a5c-cf50-4436-8c0f-f9f3de61d365)

**Specific game mode where water seems to render differently for some reason:**
![Image](https://github.com/user-attachments/assets/08396ae7-4c8b-48d4-bc13-0b4a748f5879)

**Comment by Pipi86** [comment]
Could also be related to #15949 and #15422

**Comment by cipherxof** [comment]
> Could also be related to [#15949](https://github.com/RPCS3/rpcs3/issues/15949) and [#15422](https://github.com/RPCS3/rpcs3/issues/15422)

No, I don't think. This isn't a regression as MGS4's water has never rendered correctly, as far as I can tell. The game started booting in 0.0.7 and since then I've never seen it render properly.

**Comment by digant73** [comment]
surely still an issue, but please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by KieronJ** [comment]
> surely still an issue, but please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

Still present as of https://github.com/RPCS3/rpcs3/commit/ed3d2a096c5545d9a99ab47582eaec899dbbf8f3.
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/f0ad3989-6c12-4998-9649-83db5759b4ff" />

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/18216 should fix this

**Comment by KieronJ** [comment]
> [#18216](https://github.com/RPCS3/rpcs3/pull/18216) should fix this

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/64ab7136-fb2e-4f6f-a889-f0ea948f8540" />
It seems unchanged unfortunately.

**Comment by kd-11** [comment]
> > [#18216](https://github.com/RPCS3/rpcs3/pull/18216) should fix this
> 
> It seems unchanged unfortunately.

Please attach the log file.

**Comment by KieronJ** [comment]
[RPCS3.log.gz](https://github.com/user-attachments/files/25462081/RPCS3.log.gz)

**Comment by Mr-Beacon00** [comment]
> [#18216](https://github.com/RPCS3/rpcs3/pull/18216) should fix this

sorry man, still have problem. 
only savedata is from old emulator, cache is new created

<img width="1602" height="939" alt="Image" src="https://github.com/user-attachments/assets/a114cbe6-909c-4ee5-b6f7-b1ab27711d90" />

rsx capture:
[BLUS30109_20260222215025_capture.rrc.gz](https://github.com/user-attachments/files/25468975/BLUS30109_20260222215025_capture.rrc.gz)

log:
[METAL GEAR SOLID 4 GUNS OF THE PATRIOTS \[BLUS30109\].log.gz](https://github.com/user-attachments/files/25468976/METAL.GEAR.SOLID.4.GUNS.OF.THE.PATRIOTS.BLUS30109.log.gz)

**Comment by AniLeo** [comment]
Can you test with #18522

**Comment by Jonathan44062** [comment]
Still the same, no changes in the PR
<img width="2559" height="1389" alt="Image" src="https://github.com/user-attachments/assets/df6ce100-fcc1-48db-b462-81aaae7e7da4" />

**Comment by Mr-Beacon00** [comment]
> Can you test with [#18522](https://github.com/RPCS3/rpcs3/pull/18522)

still same, only savedata is from old emulator.
<img width="1602" height="939" alt="Image" src="https://github.com/user-attachments/assets/1d4569e1-57d7-4457-8cd5-4e6cef1260ee" />

Log:
[METAL GEAR SOLID 4 GUNS OF THE PATRIOTS \[BLUS30109\].log.gz](https://github.com/user-attachments/files/26504119/METAL.GEAR.SOLID.4.GUNS.OF.THE.PATRIOTS.BLUS30109.log.gz)

RSX Capture:
[BLUS30109_20260406163930_capture.rrc.gz](https://github.com/user-attachments/files/26504123/BLUS30109_20260406163930_capture.rrc.gz)

**Comment by digant73** [comment]
please try if latest build 0.0.41-19450 fixes this issue

**Comment by Mr-Beacon00** [comment]
still no

<img width="1602" height="939" alt="Image" src="https://github.com/user-attachments/assets/db26d78a-13dc-47db-a9dd-e5b018e50dee" />

[METAL GEAR SOLID 4 GUNS OF THE PATRIOTS \[NPUB31633\].log.gz](https://github.com/user-attachments/files/29137199/METAL.GEAR.SOLID.4.GUNS.OF.THE.PATRIOTS.NPUB31633.log.gz)

[NPUB31633_20260619201601_capture.rrc.gz](https://github.com/user-attachments/files/29136623/NPUB31633_20260619201601_capture.rrc.gz)
