### ISSUE TITLE
[Regression] God of War: Ascension - Horizontal Screen Tearing

### ISSUE THREAD

**Issue by LoweysLitsman** [RPCS3/rpcs3#17879]
### Quick summary

Horizontal Screen Tearing bug has been introduced in #17508 for God of War: Ascension

### Details

I've found out a new regression was introduced to God of War: Ascension that causes a wacky horizontal screen tearing in certain parts of the game, this can be noticed at the first real-time rendered cutscene in the game.

I've found out using CPU Blit fixes this issue but, that is not a proper way to fix it as it is a Debug option.

Video Example:

https://github.com/user-attachments/assets/8202dde7-1b18-4ee8-9e8b-33e03d622e23

### Build with regression

v0.0.37-18143-335ed8d9

### Attach two log files

Working - [GOWA - 18142 - Good Previous Build.gz](https://github.com/user-attachments/files/24178921/GOWA.-.18142.-.Good.Previous.Build.gz)

Regression - [GOWA - 18143 - Regression.gz](https://github.com/user-attachments/files/24178923/GOWA.-.18143.-.Regression.gz)

Latest (19175 - 7th April 2026) - [God of War Ascension \[NPUA80918\].log.gz](https://github.com/user-attachments/files/26542323/God.of.War.Ascension.NPUA80918.log.gz)

### Attach capture files for visual issues

RSX Capture - https://drive.google.com/drive/u/0/folders/1I6ie7LKPrLkiN48AFGs1cc4DAhDPO1sq

### System configuration

OS: Windows 11 25H2
CPU: i9-13900K
GPU: RTX 3080
RAM: 2x16GB 8000MHz

### Other details

This issue is not present in OpenGL. OpenGL is fine!

**Comment by digant73** [comment]
pretty much sure I also saw this regression on other games affected by the AMM bug and iirc it was fixed enabling `Disable Asynchronous Memory Manager` in `Debug` tab. You could also try that option

EDIT: forget it. It was fixed by updating nvidia drivers

**Comment by Pipi86** [comment]
I've been seeing this exact graphical bug on Shadow of the Colossus for over a year, but i never opened a issue for it because i thought it was well known, but after seeing this issue it seems i was wrong. I easily reproduce it with default settings (no patches enabled) + vsync so it's easier to see and not be mistaken for regular screen tearing + accurate rsx reservations (because it's almost impossible to trigger it without it, also game is literally unplayable performance-wise if disabled; wiki should be updated to add this setting as recommended when playing unpatched) and increasing vblank to 120hz to get over 30fps limit. There's actually 2 graphical bugs in this video, if you look at wander's coat everytime i choose the bow weapon, it changes color to full bright if i change camera angle. I've been avoiding this screen tearing bug all this time by enabling allow host gpu labels but i remember cpu blit also does the trick.
https://youtu.be/QoSV0ZAZwCU?si=qdNcIvNQgG8ZmoHi

**Comment by LoweysLitsman** [comment]
I am unable to reproduce the issue anymore and I even tested the build that supposedly regressed it, it was actually fine now.
The things that have changed in my system are:
- Various Windows Updates
- Removed the GTX 1070
- Updated GPU Drivers to 591.86

I am not willing to test older drivers, closing since I no longer can reproduce.
**If anyone can reproduce, be sure to post the log and an image or video of the issue.**

**Comment by LoweysLitsman** [comment]
Re-opening again. Re-tested recently and the issue is still occurring, I cannot determinate why it randomly stopped happening before.
I've added new RSX Captures and added a new log.
Alongside that, the tearing can actually be worse now too, its included in the [rsx captures](https://drive.google.com/drive/folders/1yLxIB7Bfh-QG3re3ShNNR2dvGskPHpVD?usp=drive_link).


![Image](https://github.com/user-attachments/assets/01166ce0-eb0a-48d1-a575-78196e0c2418)

**Comment by digant73** [comment]
@LoweysLitsman a similar issue on NFL Tour is fixed with Allow Host GPU Labels . You can try it

**Comment by digant73** [comment]
#17508 also worsened tearing in GT6 (in game) and is responsible for corrupted graphics in menu (e.g. on car selection)

**Comment by LoweysLitsman** [comment]
> [@LoweysLitsman](https://github.com/LoweysLitsman) a similar issue on NFL Tour is fixed with Allow Host GPU Labels . You can try it

Allow Host GPU Labels does unfortunately not help and causes visual flickering. [Host GPU Labels - God of War Ascension \[NPUA80918\].log.gz](https://github.com/user-attachments/files/30945070/Host.GPU.Labels.-.God.of.War.Ascension.NPUA80918.log.gz)
My GPUs drivers are now on 610.88

[God of War Ascension \[NPUA80918\].log.gz](https://github.com/user-attachments/files/30945190/God.of.War.Ascension.NPUA80918.log.gz)

<details><summary>Video examples</summary>
<p>

Host GPU Labels **(EPILEPSY WARNING)**

https://github.com/user-attachments/assets/b8dd2652-7842-4de3-b866-7e42b73c35ee

Wiki settings (no patches)

https://github.com/user-attachments/assets/9036f190-de51-41ad-ba9d-8fd846a92638

</p>
</details>

**Comment by digant73** [comment]
is the issue present on OpenGL?

**Comment by LoweysLitsman** [comment]
No, it hasn't happened before and it still doesn't happen on the latest. Only Vulkan has been affected so far.

**Comment by digant73** [comment]
@LoweysLitsman please try the attached bin (rename to rpcs3.7z and unzip)

[rpcs3.7z.zip](https://github.com/user-attachments/files/30963166/rpcs3.7z.zip)

**Comment by kd-11** [comment]
It's a race condition between CELL and RSX seen in other games like GT6. The vertical glitching in the original video though is blit engine errors, I assume it is long fixed and only the horizontal tear remains.
OpenGL is a different type of renderer so such issues wouldn't appear there. It executes commands inline instead of recording, giving CELL time to catch up.
It's a good candidate to test with https://github.com/RPCS3/rpcs3/pull/19013 though I expect it would likely still be tearing. The problem should get worse the faster RSX gets. Options like "host GPU labels" should help but that feature is also incomplete.

EDIT: I just checked on my PC and as expected, "Allow host GPU labels" significantly improves the situation. This isn't even a regression, I have the tearing on all builds and reverting the blamed commits does not show any difference. In my case, the CPU is wide enough that it is a single tear line (horizontal). What has the biggest impact however is just overclocking my CPU from 3.7 to 4.6GHz (it runs downclocked by default for power and heat reasons) which is in line with my expectations.

**Comment by digant73** [comment]
in #19013 the issue in car selection (I refer to pink color; the interleaved horizontal black bars were always present) is still present. see also the grey vertical line separating the area were the issue is present (left part of screen) . Below a video. That issue is present since #17508

EDIT: the grey vertical line was due to Blit Engine Upscaling and RS 200%. It is not present if Blit Engine Upscaling is disabled

https://mega.nz/file/DzAkSapR#VivL6pILtVFKcZMI34saZ3f1LAKCjVCpVk19i24ZVWo

**Comment by digant73** [comment]
> EDIT: I just checked on my PC and as expected, "Allow host GPU labels" significantly improves the situation. This isn't even a regression, I have the tearing on all builds and reverting the blamed commits does not show any difference. In my case, the CPU is wide enough that it is a single tear line (horizontal). What has the biggest impact however is just overclocking my CPU from 3.7 to 4.6GHz (it runs downclocked by default for power and heat reasons) which is in line with my expectations.

well Host GPU Labels kills performance (1 fps) on my RTX 5090. this happens on both master and #19013

**Comment by LoweysLitsman** [comment]
@digant73 Your local build seems to have solved the issue for me. 19013 PR doesn't seem any different from master.

[Digant localbuild - God of War Ascension \[NPUA80918\].log.gz](https://github.com/user-attachments/files/30978699/Digant.localbuild.-.God.of.War.Ascension.NPUA80918.log.gz)
[PR 19013 - God of War Ascension \[NPUA80918\].log.gz](https://github.com/user-attachments/files/30978698/PR.19013.-.God.of.War.Ascension.NPUA80918.log.gz)

<details><summary>Video of the issue solved</summary>
<p>

https://github.com/user-attachments/assets/d1674136-f663-4351-9e32-0ad6b3e64901

</p>
</details>

**Comment by kd-11** [comment]
@LoweysLitsman @digant73 That fix just hides the issue. The root cause is a quirk in the  nvidia drivers.
The PR made it so that we remove old textures (e.g after a cutscene) from the cache instead of holding them forever which keeps VRAM usage low. But on nvidia drivers removing textures is extremely slow for no good reason even when they have not been used for more than 8 frames which is a lifetime in GPU programming terms. You can check this by enabling MTRSX on master and watch the problem disappear because MTRSX forces the driver to remove the textures on a separate thread.

**Comment by kd-11** [comment]
Maybe I should keep some parts of MTRSX always active because of such issues. At least I can force the garbage collector to a separate thread regardless of the setting.

**Comment by digant73** [comment]
@kd-11 it seems your analysis is similar to what AI provided after doing many tests to isolate the issue. See below for a quick recap made by AI

the issue on GT6's menu was identified (and fixed by AI; see link below) as due to:

Cause

Going through the GC, the surface holds on to its GPU resources for an extra frame. Releasing one group at a time shows that the MSAA  resolve target, the device memory and the image_view cache are each harmless on their own: it is releasing the VkImage handle (vkDestroyImage) that restores correct rendering — at an identical VRAM figure and identical counters otherwise.

PR link: https://github.com/digant73/rpcs3/commit/6c8b48d21c50c64b23b8810d67078f8a7cbedec0

**Comment by digant73** [comment]
> [@LoweysLitsman](https://github.com/LoweysLitsman) [@digant73](https://github.com/digant73) That fix just hides the issue. The root cause is a quirk in the nvidia drivers. The PR made it so that we remove old textures (e.g after a cutscene) from the cache instead of holding them forever which keeps VRAM usage low. But on nvidia drivers removing textures is extremely slow for no good reason even when they have not been used for more than 8 frames which is a lifetime in GPU programming terms. You can check this by enabling MTRSX on master and watch the problem disappear because MTRSX forces the driver to remove the textures on a separate thread.

using MTRSX seems to fix the pink issue (I saw just one of it in some minutes when moving at full screen) on GT6's menu but it creates a lot of artefacts on car

**Comment by kd-11** [comment]
> Going through the GC, the surface holds on to its GPU resources for an extra frame. Releasing one group at a time shows that the MSAA resolve target, the device memory and the image_view cache are each harmless on their own: it is releasing the VkImage handle (vkDestroyImage) that restores correct rendering — at an identical VRAM figure and identical counters otherwise.

Pure AI slop response.

**Comment by kd-11** [comment]
> using MTRSX seems to fix the pink issue (I saw just one of it in some minutes when moving at full screen) on GT6's menu but it creates a lot of artefacts on car

That's because right now MTRSX toggles several things internally including asynchronous DMA operations. It's one setting doing too many things, which is why I propose to split it into DMA part and other internal routines.
So after the PR, MTRSX will be always on for some things like GC, but the big part of asynchronous DMA will remain tied to the setting.

**Comment by digant73** [comment]
> > Going through the GC, the surface holds on to its GPU resources for an extra frame. Releasing one group at a time shows that the MSAA resolve target, the device memory and the image_view cache are each harmless on their own: it is releasing the VkImage handle (vkDestroyImage) that restores correct rendering — at an identical VRAM figure and identical counters otherwise.
> 
> Pure AI slop response.

Surely not the proper fix but apparently fixing the pink colors in GT6's menu and tearing in GoW Ascension (as reported by @LoweysLitsman). Below the link to the changes, just in case something could be correct and useful

PR link: https://github.com/digant73/rpcs3/commit/6c8b48d21c50c64b23b8810d67078f8a7cbedec0

**Comment by kd-11** [comment]
> Surely not the proper fix but apparently fixing the pink colors in GT6's menu and tearing in GoW Ascension. Below the link to the changes, just in case something could be useful
> 
> PR link: [digant73@6c8b48d](https://github.com/digant73/rpcs3/commit/6c8b48d21c50c64b23b8810d67078f8a7cbedec0)

It just undoes the PR in a sneaky way, but that makes sense because you probably just pointed it at the PR and asked it to find a solution. It is intentionally delaying removal of the stale resources just as before which causes the improved performance behavior due to avoided GC stall. It just goes about it in a really long-winded way. Either way, the approach itself is wrong.

One thing that it gets right is that when memory is very low, we may have stale FBO references. This really only happens when VRAM is full and we're about to crash anyway, but it is something I will fix properly in the PR.
