### ISSUE TITLE
[BLUS30485] RAGE - Graphical Bugs

### ISSUE THREAD

**Issue by alexconsole04** [RPCS3/rpcs3#17931]
### Quick summary

In RAGE, there are some graphical bugs on geometry and broken lights.

### Details

RAGE has plentiful of graphical issues that are seen as flickering artifacts on geometry that quickly flicker in and out while moving. Weird light artifacts appear as opposed to a real PS3. No settings fix both of these issues it seems.

Video of the issue. https://youtu.be/RwdYfxeI54c

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/24356027/RPCS3.log.gz)

### Attach capture files for visual issues

https://www.mediafire.com/file/d4b45xsctlt00nd/BLUS30485_20251227115019_capture.rrc.gz/file

### Other details

OpenGL is more broken than Vulkan and does not fix the mentioned issues.

**Comment by kd-11** [comment]
@alexconsole04 You need to enable strict mode for most id tech 5 bugs.

**Comment by alexconsole04** [comment]
Strict Rendering Mode fixes the broken lights, however the flickering still persists, Probably something else unrelated.

**Comment by kd-11** [comment]
The flickering is new, so maybe "async memory manager" is the culprit.

**Comment by alexconsole04** [comment]
> The flickering is new, so maybe "async memory manager" is the culprit.

Disabling it only makes the game run worse, the flickering is still there regardless.

<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/3aec1dd5-6927-4cf3-8ba1-13755f4f8cce" />

<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/e7382d1f-ddf7-4d09-ac10-3850a04ec22a" />

[RPCS3.log.gz](https://github.com/user-attachments/files/24356670/RPCS3.log.gz)

**Comment by digant73** [comment]
Same issues on my HW. It is also a shame RS doesn't work in this game

**Comment by digant73** [comment]
Weird light artefacts is a regression since #16350. @alexconsole04 could you please confirm?

EDIT: The light artefacts regressed by #16350 seems due to the following change in `texture_cache.h`:

`invalidate_range_impl_base(cmd, rsx_range, invalidation_cause::cause_is_write | invalidation_cause::cause_uses_strict_data_bounds, {}, std::forward<Args>(extras)...);
`

It is fixed by restoring the previous code (so removing strict constraint):

`invalidate_range_impl_base(cmd, rsx_range, invalidation_cause::write, {}, std::forward<Args>(extras)...);
`

**Comment by alexconsole04** [comment]
The light artifacts is indeed a regression. However the flickering geometry still persists. Game also ran way worse than latest, but that's not related. 

[Working Build](https://github.com/user-attachments/files/24402472/RPCS3.log.gz)

[Broken Build](https://github.com/user-attachments/files/24402473/RPCS3.log.gz)

**Comment by digant73** [comment]
yes flickering geometry is still there, though they are worse on latest versions compared to old versions. I also saw bad perf on old builds (so a good news that perf have been improved on latest versions).

EDIT:
- flickering geometry depends on camera. It seems flickering (so a temporary transition) but it is a broken texture (e.g. black) that remains on screen until you move the camera (and the proper texture is loaded)
- I confirm the flickering geometry was a lot less frequent (almost absent) on old builds (e.g. even on #16350)

**Comment by digant73** [comment]
the flickering geometry has worsened since #16352 (AMM). It improved a lot performance but made flickering geometry a lot worse. As I said on previous post, the geometry artefacts depends on camera. Below a screenshot with a blue artefact on top left corner. It will be properly replaced by correct texture when slightly rotating the camera on the left.

On current build, with AMM disabled flickering geometry is a lot reduced. IIRC Rage was reported by Digital Foundry as affected by texture streaming issue. Maybe this issue I see with AMM disabled is more related to a game issue than an rpcs3 issue. But here only kd-11 can provide feedbacks about issue with AMM enabled and a possible permanent issue on texture streaming with AMM disabled.

<img width="3834" height="2156" alt="Image" src="https://github.com/user-attachments/assets/2e14b525-9a4c-4235-b7cb-7f1fc44fc3fa" />

**Comment by ghost** [comment]
> the flickering geometry has worsened since [#17195](https://github.com/RPCS3/rpcs3/issues/17195) (AMM). It improved a lot performance but made flickering geometry a lot worse. As I said on previous post, the geometry artefacts depends on camera. Below a screenshot with a blue artefact on top left corner. It will be properly replaced by correct texture when slightly rotating the camera on the left.

https://github.com/RPCS3/rpcs3/issues/17195 Is a feature request post.

**Comment by digant73** [comment]
ops, I reported the build version instead of PR #16352. Previous post updated

**Comment by digant73** [comment]
@kd-11 anti-aliasing is not applied at all in the game. Is this something you know with id engine or maybe an issue that could be fixed?

**Comment by kd-11** [comment]
No idea. Maybe it wasn't enabled at all on the PS3 version to save performance.

**Comment by kd-11** [comment]
As for the flickering squares - those are just megatexture page sections. The whole world is subdivided into a grid of small squares and visible slices are loaded in dynamically to build a mega-atlas by CELL. They're usually copied in via blit engine and/or CELL writes which makes me wonder if it is just a performance/race-condition thing. It needs testing on some different hardware combinations. I would definitely check if host GPU labels or accurate RSX reservations have an effect on this.

**Comment by digant73** [comment]
> No idea. Maybe it wasn't enabled at all on the PS3 version to save performance.

I asked that because on PS3 AA is present while on RPCS3 is completely absent. Also RS does nothing. Just in case it is something that could be checked. Rage has also a demo version

**Comment by alexconsole04** [comment]
I have been using host gpu labels since it massively improves performance, however textures still flicker. Accurate rsx reservation access doesn't seem to help at all.

While i do not like using yt videos, this is the more recent yt benchmark of the game from October. Much powerful hardware than mine and also has said issue. I believe this is some sort of race condition 
https://youtu.be/KB9CanhNSkY

**Comment by digant73** [comment]
> As for the flickering squares - those are just megatexture page sections. The whole world is subdivided into a grid of small squares and visible slices are loaded in dynamically to build a mega-atlas by CELL. They're usually copied in via blit engine and/or CELL writes which makes me wonder if it is just a performance/race-condition thing. It needs testing on some different hardware combinations. I would definitely check if host GPU labels or accurate RSX reservations have an effect on this.

in my case (as previously reported) disabling AMM minimize a lot the artefacts (almost absent I would say). Artefacts are clearly visible with AMM enabled. Tested also host GPU labels with no success

**Comment by digant73** [comment]
Checked the ps3 version and it is clearly a lot more crisp than on rpcs3. On rpcs3 the game seems to run at very low resolution. Below a screenshot on rpcs3. The text is perfectly crisp and readable on ps3 while on rpcs3 it seems like a 640x480. Same for the overall env. AA is not good also on ps3 but probably the bad resolution on rpcs3 makes it even more noticeable,

I also verified that the same artefacts (with AMM disabled) are present also on ps3. I refer to the white textures that are displayed for a fraction of second, e.g. when you rotate the camera towards the door, see second screenshot (the issue is not displayed because it's not permanent as the more annoying artefacts frequently displayed with AMM enabled).


EDIT: ASMJIT completely fixes the annoying artefacts more frequently displayed with AMM enabled. Surprisingly, performance are not impacted even disabling AMM (while they drop with LLVM).

<img width="3836" height="2150" alt="Image" src="https://github.com/user-attachments/assets/323cff0b-d0fa-498d-b4db-ea2641bb61ce" />

</br>
</br>

<img width="3809" height="2095" alt="Image" src="https://github.com/user-attachments/assets/c4921665-d4cc-4399-991d-e578347d41e6" />

**Comment by digant73** [comment]
light issue is fixed by 0.0.42-19872 (#19013). flickering artifacts are almost absent on my HW enabling Allow Host GPU Labels and WCB.
@alexconsole04 could you also verify on your side?
