### ISSUE TITLE
PPU: Discrepancies between Interpreter and Recompiler

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2909]
List of broken games with PPU recompiler (LLVM):

- [x] **AlienSpidy** - Fixed in #5749
- [x] **Amy** - Fixed in #5749
- [x] **Arthur and the Revenge of Maltazard** - Fixed as of September 29, 2018 [Forum thread](https://forums.rpcs3.net/thread-178418.html).
- [x] **Batman Arkham Asylum** (broken animations) - Fixed in #4732
- [x] **Burn Zombie Burn!** - Fixed in #5749
- [x] **Cash Guns Chaos DLX** - Fixed in #5749
- [x] **Castlevania: Harmony of Despair** - Relocation issue fixed in #4278
- [x] **Constant C** - Fixed in #5749
- [x] **Cosmophony** - Fixed in #5749
- [x] **CounterSpy** - Fixed in #5749
- [ ] **Dare to Fly!**
- [ ] **Daytona USA** (Broken ingame textures)
- [x] **Dead Nation** - Fixed in #5749
- [x] **Deus Ex Human Revolution Director's Cut** (Broken vertices when characters are talking.) - Fixed in #4732
- [x] **Entwined** - Fixed in #5749
- [x] **Escape Dead Island** - Fixed in #5749
- [x] **Fallout 3** - Fixed in #5749
- [x] **Fallout New Vegas** - Fixed in #5749
- [x] **Farming Simulator 15** - Fixed in #5749
- [x] **FIFA games** - FIFA 12 is fixed in #4278
- [x] **Fuse** - Fixed in #4842
- [ ] **Gauntlet 2**
- [x] **Harry Potter and The Order of The Phoenix** - Fixed in #5749
- [x] **Helldivers** - Fixed in #5749
- [x] **History: Great Battles - Medieval** - Fixed in #5749
- [x] **History Channel's Civil War: Secret Missions** - Fixed in #5749
- [x] **History Channel: Battle for the Pacific** - Fixed in #5749
- [x] **Hyperballoid HD** - Fixed in #5749
- [x] **Infamous franchise** (broken textures) - Fixed in #4732
- [x] **Initial D Extreme Stage** - Fixed in #5749
- [x] **Jak and Daxter Collection** - Fixed in #5749
- [x] **Malicious** - Fixed in #5749
- [x] **Max Payne 3** (With PPU interpreter fast, it can go ingame, but crashes randomly. With PPU LLVM crashes just before going to main menu) - Fixed in #4732. Now behaves the same as PPU interpreter fast.
- [x] **Metal Gear Solid Peace Walker HD** - Fixed in #5749
- [x] **Metro Last Light** (Broken graphics and crash) - Fixed in #4732
- [x] **Motorcycle Club** - Fixed in #5749
- [ ] **My Aquarium** (Black screen)
- [x] **Never Alone** - Fixed in #5749
- [ ] **Ninja Gaiden 3: Razor's Edge**
- [x] **Oddworld: New 'n' Tasty** - Fixed in #5749
- [x] **Overlord Raising Hell** - Fixed in #5749
- [x] **Overlord II** - Fixed in #5749
- [x] **Pid** - Fixed in #5749
- [x] **Portal 2** - Fixed in #4278
- [x] **Pro Baseball Spirits 2015** - Fixed in #5749
- [x] **Pro Evolution Soccer games** - Fixed in #5749
- [x] **Pro Yakyuu Spirits 2014** - Fixed in #5749
- [x] **Rain** - Fixed in #5749
- [x] **Revenant Saga** - Fixed in #5749
- [x] **Rochard** - Fixed in #5749
- [ ] **Rocketbirds: Hardboiled Chicken**
- [x] **Rugby World Cup 2015** - Fixed in #5749
- [x] **Saints Row 2** (Broken graphics) - Fixed in #4732
- [x] **Sid Meier's Civilization Revolution** (Freezes after intro) - Fixed in #5749
- [x] **Silent Hill Homecoming** - Fixed in #5749
- [x] **Singularity** - Fixed in #5749
- [x] **Skate 3** (Broken vertices. See #4447 for details.) - Fixed in #4732
- [x] **Sky Force Anniversary** - Fixed in #5749
- [x] **Soldier of Fortune: Payback** - Fixed in #5749
- [ ] **Sonic Adventure** (Freezes in savegame selection.)
- [x] **Sonic Unleashed** (See #4087 for details) - Fixed in #5749
- [x] **Space Hulk** - Fixed in #5749
- [ ] **Splatterhouse**
- [x] **SSX** - Fixed as of December 31, 2017 [Forum thread](https://forums.rpcs3.net/thread-178586.html).
- [x] **Stick it To The Man** - Fixed in #5749
- [x] **Tales from Space: About a Blob Demo** - Fixed in #5749
- [x] **Teslagrad** - Fixed in #5749
- [x] **The Bridge** - Fixed in #5749
- [x] **The Cursed Crusade** - Fixed in #5749
- [x] **The Elder Scrolls IV: Oblivion** - Fixed in #5749
- [x] **The Evil Within** - Fixed in #5749
- [x] **The Lord of the Rings: Conquest** - Fixed in #5749
- [x] **UEFA Euro 2016** - Fixed in #5749
- [x] **UFC Undisputed 2010** - Fixed in #5749
- [x] **Vessel** - Fixed in #5749
- [x] **Way of the Samurai 3** - Fixed in #5749
- [x] **Yakuza 1 & 2 HD Edition** - Fixed in #5749
- [x] **Zombeer** - Fixed in #5749

**Comment by AniLeo** [comment]
@Zangetsu38 Can you post that game you had with broken graphics on LLVM but not Interpreter?

**Comment by digitaldude555** [comment]
LLVM issues.
Yakuza 1-2
`F {PPU[0x1000000] Thread (main_thread) [0x003194a0]} class std::runtime_error thrown: Unregistered PPU function`

Silent Hill Homecoming
`F {PPU[0x1000000] Thread (main_thread) [0x0004032c]} MEM: Access violation writing location 0x0`

Initial D and Batman Arkham Asylum just don't open any windows with LLVM.

**Comment by Zangetsu38** [comment]
Burn Zombie, Yes wait

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/27723056-544808f4-5d6b-11e7-9e1f-2c30096231cc.png)
Fixed by https://github.com/RPCS3/rpcs3/commit/77c4982dd98aa56b40d2bd9d9d39962b84b20f29.

**Comment by 16bitblastprocessing** [comment]
Fallout 4 GOTY Edition only throws out the unregistered PPU function when using PPU LLVM.

·F 0:00:48.967350 {PPU[0x1000005] Thread (Miles Thread) [0x00cd9e14]} class std::runtime_error thrown: Unregistered PPU function


[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/1254731/RPCS3.txt)

**Comment by Asinin3** [comment]
**Gauntlet 2**
Game displays black screen with LLVM (Freezes with mem access violation regardless though)

**Comment by Renusek** [comment]
Game is not working with LLVM

Tales from Space: About a Blob (Playable Demo) NPEB00388
`F {PPU[0x1000000] Thread (main_thread) [0x007c24e0]} class std::runtime_error thrown: Unregistered PPU function`

**Comment by jjsat** [comment]
Deus Ex Human Revolution Directors Cut (BLES01928) has some broken graphics with LLVM. It is not present with the fast or precise interpreter. Some characters are drawn horizontally and vertices are messed up when characters talk.

![grafik](https://user-images.githubusercontent.com/1445782/31248349-bbf74222-aa13-11e7-83b5-dd308b3542cf.png)
![grafik](https://user-images.githubusercontent.com/1445782/31248401-e217f1c2-aa13-11e7-9556-efaa6b171184.png)

**Comment by zekesonxx** [comment]
Fallout 3 (BLUS30185) also affected, loads and mostly functional on either of the PPU interpreters, but crashes on the LLVM recompiler:

```
{PPU[0x1000005] Thread (Miles Thread) [0x010a9bd8]} St13runtime_error thrown: Unregistered PPU function
```

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1363657/RPCS3.log.gz)

**Comment by Nezarn** [comment]
Initial D Extreme Stage (BLJM60055)

If loading savegame:
`F {PPU[0x1000022] Thread (load_data) [0x0032ba60]} MEM: Access violation reading location 0x40fe007c`
If starting new game:
`F {PPU[0x1000000] Thread (main_thread) [0x0032ba60]} MEM: Access violation reading location 0x552a422e`

**Comment by D8174** [comment]
Civilization Revolution (BLES00238)

After intro video with PPU recompiler:
`F {PPU[0x100000a] Thread (Miles Thread) [0x00f6678c]} class std::runtime_error thrown: Unregistered PPU function`

Gets further with interpreter but
After selecting a civilization:
`F {PPU[0x1000000] Thread (main_thread) [0x00ab6088]} MEM: Access violation reading location 0x0`

**Comment by lif3mau5** [comment]
Tom Clancy's Splinter Cell Triology HD Part 1 working but Pandora Tomorrow and Chaos Theory bring the same Error: MEM: Access violation writing location 0xd0128ff0 ... Game is broken in EUR Version

**Comment by D8174** [comment]
Update to Civilization Revolution (BLES00238):
With interpreter it gets in game (past choosing a civ) but still no change with recompiler.

**Comment by Subarasheese** [comment]
Daytona USA (NPUB30493) also has problems on LLVM. It has flickering textures, regardless of GPU settings. The graphics are perfect on Interpreter, though. 


![new](https://user-images.githubusercontent.com/35178075/34654905-d484e0ee-f3e0-11e7-9a33-1af452599897.gif)



If the game is paused, the graphics are rendered correctly:

![new](https://user-images.githubusercontent.com/35178075/34655109-8f37b50e-f3e3-11e7-98f4-cd0ed00948fb.gif)

**Comment by JackONeill12** [comment]
Portal 2 also doesn't work on LLVM.

E PPU: LLVM: [0x1825d0] Unsupported relocation(11) in 'tier0_ps3.sprx'. Please report.

**Comment by Megamouse** [comment]
Malicious can be added

**Comment by Asinin3** [comment]
Majority of Fifa games require PPU fast as well as many other games I ran into so many that i just gave up on listing them all.

**Comment by Asinin3** [comment]
Fifa 12:
``E PPU: LLVM: [0x2789374] Unsupported relocation(11) in 'powdllzf.sprx'. Please report.
E PPU: LLVM: [0x2749064] Unsupported relocation(11) in 'powdllzf.sprx'. Please report.``

Also I'll continue to update my post earlier but this issue seems more serious and easier to debug so made a new post. I did have Numan look into this in January and after giving me a test build he was unable to fix the issue and said it needed much more investigation.

**Comment by Zangetsu38** [comment]
no forget problem alkso with Infamous serie on llvm, texture glitched, but fine in ppu fast

**Comment by Megamouse** [comment]
add Cosmophony

**Comment by LukeUkk** [comment]
Jak and dexter collection
E {PPU[0x1000007] Thread (fios mediathread 2) [0x0172c090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/Jak2/jak2/game/dgo1/iso.txt” [1]

F {PPU[0x100000d] Thread (GOAL) [0x0001858c]} class std::runtime_error thrown: Unregistered PPU function

**Comment by markcagatandavis** [comment]
God Of War [NPUA80490] - Unregistered PPU function 
[GOW - Error Log.txt](https://github.com/RPCS3/rpcs3/files/2074932/GOW.-.Error.Log.txt)

**Comment by creeperjedi** [comment]
#4732 Fixed the Infamous 1 (and probably Infamous 2) textures.
Before:
<img width="641" alt="infamous before" src="https://user-images.githubusercontent.com/38361979/41205232-709e31b0-6cbd-11e8-8594-444804db82cc.png">
After:
<img width="641" alt="infamous after" src="https://user-images.githubusercontent.com/38361979/41205233-731e60ae-6cbd-11e8-9dcb-aec4219c2e2c.png">

**Comment by Xcedf** [comment]
Not listed in this issue but this PR also fixed Saints Row II with LLVM
before:
![5](https://user-images.githubusercontent.com/7060586/41206100-6f73c030-6d07-11e8-9044-1e7e193f1954.jpg)

after:
![4](https://user-images.githubusercontent.com/7060586/41206099-6f547a9a-6d07-11e8-9df6-ca36c6a0167b.jpg)

and Metro Last Light LLVM broken graphic and crash fixed
before:
![6](https://user-images.githubusercontent.com/7060586/41206159-755caa1a-6d08-11e8-94e5-6ff84a899b9c.jpg)
after:
![12](https://user-images.githubusercontent.com/7060586/41206160-757d6ebc-6d08-11e8-80ad-16d65537a4db.jpg)

**Comment by stride21** [comment]
**Killzone 3:**
{PPU[0x1000000] Thread (main_thread) [0x00abbc94]} class std::runtime_error thrown: Unregistered PPU function

**Comment by jcapsule** [comment]
Teslagrad [BLES02134]

Game starts with "Interpreter (fast)", but is not working with LLVM.

{PPU[0x1000005] Thread (UnityMain) [0x011cfebc]} class std::runtime_error thrown: Unregistered PPU function

Version: rpcs3-v0.0.5-7510-7f1cbb11_win64

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2612249/RPCS3.log.gz)

**Comment by Xcedf** [comment]
I believe Condemned 2 also here, the known issue flickering geometry in Condemned 2 almost never hapens on PPU Interpreter and happens always on LLVM i noticed even in places where both Interpreter and LLVM show the same framerate

**Comment by stride21** [comment]
Beyond Two Souls needs PPU Fast to continue or load chapters.

{SPU[0x2000003] Thread (QDSpursCellSpursKernel3) [0x0451c]} MEM: Access violation reading location 0x3c0
{SPU[0x2000001] Thread (QDSpursCellSpursKernel1) [0x0451c]} MEM: Access violation reading location 0x210
{SPU[0x2000000] Thread (QDSpursCellSpursKernel0) [0x0451c]} MEM: Access violation reading location 0x210
{SPU[0x2000002] Thread (QDSpursCellSpursKernel2) [0x0451c]} MEM: Access violation reading location 0x1f80

**Comment by toccata10** [comment]
Sky Force Anniversary [NPUB31813] stops with
F {PPU[0x1000005] Thread (UnityMain) [0x0156febc]} St13runtime_error thrown: Unregistered PPU function
Another Unity game. Hopefully someone will improve all these games in one nice PR.
rpcs3-v0.0.5-7678-52ac0a90_linux64
[RPCS3-SkyForce.zip](https://github.com/RPCS3/rpcs3/files/2730296/RPCS3-SkyForce.zip)

**Comment by Krusher97** [comment]
Dead Nation does not boot in PPU LLVM, stopping with an unregistered PPU function error.
![rpcs3_2019-01-28_16-02-12](https://user-images.githubusercontent.com/25664221/51830731-8dfe0b80-2316-11e9-99d6-d3c07012864f.png)
[Dead Nation.gz](https://github.com/RPCS3/rpcs3/files/2802511/Dead.Nation.gz)

**Comment by Krusher97** [comment]
Add Vessel to the list
![rpcs3_2019-02-02_17-04-36](https://user-images.githubusercontent.com/25664221/52163754-b0c06380-270c-11e9-8db0-0c580426f150.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2824361/RPCS3.log.gz)

**Comment by Krusher97** [comment]
[NPUB31184] NINJA GAIDEN 3: Razor's Edge 
Crashes after the Tecmo logo in PPU LLVM Recompiler
Goes ingame with Interpreter fast
![rpcs3_2019-02-03_16-04-31](https://user-images.githubusercontent.com/25664221/52175701-c77abf00-27cd-11e9-987d-f34795599a8e.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2825412/RPCS3.zip)

**Comment by yugi1408** [comment]
pls fix unleashed

**Comment by GreatApo** [comment]
> Dead Nation does not boot in PPU LLVM, stopping with an unregistered PPU function error.
> ![rpcs3_2019-01-28_16-02-12](https://user-images.githubusercontent.com/25664221/51830731-8dfe0b80-2316-11e9-99d6-d3c07012864f.png)
> [Dead Nation.gz](https://github.com/RPCS3/rpcs3/files/2802511/Dead.Nation.gz)

[NPEA00143] Dead Nation (v1.08)
Up until loading the first level it works with Interpreter fast/precise

Log PPU LLVM Recompiler:
`S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 17718 functions.
U {PPU[0x1000000] Thread (main_thread) [0x0146fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x014700bc]} sys_prx TODO: _sys_prx_register_library(library=*0x14726a0)
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v1-tane-1z3Pyu8YVnnorJiQ2hfu1e-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x014b3d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v1-tane-XCgQWMc1s99n1WTwrpWvw4-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v1-tane-TP3c8YsdNggjaG5WRjcboe-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v1-tane-LWAKW9c35vXJad6uHkwzhK-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v1-tane-fLV79QqHgPi90UziTsWrHo-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0147061c]} sys_prx TODO: _sys_prx_register_module()
F {PPU[0x1000000] Thread (main_thread) [0x01464f78]} class std::runtime_error thrown: Unregistered PPU function`

Log with Interpreter precise:
`S HLE: MMJOY Device 0 reconnected.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime initialized...
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 16287 functions.
U {PPU[0x1000000] Thread (main_thread) [0x0146fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x014700bc]} sys_prx TODO: _sys_prx_register_library(library=*0x14726a0)
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x014b3d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0147061c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libhttp.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libat3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libatxdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libatrac3plus.sprx
E {PPU[0x1000000] Thread (main_thread) [0x014b3e0c]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/data/bootflag.dat” [1]
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/liblv2dbg_for_cex.sprx
U {PPU[0x1000000] Thread (main_thread) [0x016a0038]} HLE TODO: Unimplemented syscall sys_dbg_disable_floating_point_enabled_exception -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libpamf.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsail.sprx
U {PPU[0x1000000] Thread (main_thread) [0x017241c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libssl.sprx
U {PPU[0x1000000] Thread (main_thread) [0x014f7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x0146ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0146ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000000] Thread (main_thread) [0x01440b90]} 'cellKbClearBuf' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [1]
E {PPU[0x1000000] Thread (main_thread) [0x01440b90]} 'cellKbClearBuf' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [2]
E {PPU[0x1000000] Thread (main_thread) [0x01440b90]} 'cellKbClearBuf' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [3]
U {PPU[0x1000000] Thread (main_thread) [0x014408b8]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0100760, option=*0x0, waitForEvent=0)
S {RSX [0x0000000]} RSX: New program compiled successfully x45
U {PPU[0x1000000] Thread (main_thread) [0x01442340]} cellGameExec TODO: cellGameGetBootGameInfo(type=*0xd0100940, dirName=“”, execdata=*0xd0100944)
S {cellAudio Thread} XAudio 2.9 initialized
U {PPU[0x1000000] Thread (main_thread) [0x01445558]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
U {PPU[0x1000000] Thread (main_thread) [0x01444fb0]} cellUserInfo TODO: cellUserInfoGetList(listNum=*0x0, listBuf=*0x0, currentUserId=*0xd0100520)
U {PPU[0x1000000] Thread (main_thread) [0x014458f0]} sceNp TODO: sceNpManagerGetCachedInfo
U {PPU[0x1000000] Thread (main_thread) [0x01445e80]} sceNp2 TODO: sceNpMatching2Init2(poolsize=0x0, priority=0, param=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01440ba8]} 'cellKbRead' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [1]
E {PPU[0x1000000] Thread (main_thread) [0x01440ba8]} 'cellKbRead' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [2]
E {PPU[0x1000000] Thread (main_thread) [0x01440ba8]} 'cellKbRead' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [3]
E {PPU[0x1000000] Thread (main_thread) [0x01531ee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/debug.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01531ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEA00143/USRDIR/debug.edat” [1]
E {PPU[0x100000f] Thread (_sys_MixerChStripMain) [0x014654ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x100000f] Thread (_sys_MixerChStripMain) [0x014654ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x100000f] Thread (_sys_MixerChStripMain) [0x014654ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x0026c2c4]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x0026c2c4]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x0026c2c4]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x1000000] Thread (main_thread) [0x01531ee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/reg.edat” [1]
E {PPU[0x1000016] Thread (Trophy thread) [0x01440398]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x10a45b8, arg=*0x358d7b70, options=0x0)
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300d100, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300d000, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bc00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxSetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxDisableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxReleaseAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxEnableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxClose' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStreamAndWaitDone' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenExt' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxFlushEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenEx' in module 'cellDmux'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x28B2B7B2' in module 'cellDmuxPamf'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x9728A0E9' in module 'cellDmuxPamf'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x1A5B72DD' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x32DA1344' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x3B95270D' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x4A1964A6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x52BB9416' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x540B43AE' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x5A0355CF' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x60D0F4FA' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6B49A7C7' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6D1F7D3F' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x96C2A2D9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xA0D447EB' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD09740F6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD8D930BC' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xDC6F4FF1' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE3072DF9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE36F2A6C' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE9FFF717' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF007F937' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF4E8D559' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xFF05DD1F' in module 'libsmvd2'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300de00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300dd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bc00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxSetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxDisableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxReleaseAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxEnableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxClose' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStreamAndWaitDone' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenExt' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxFlushEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenEx' in module 'cellDmux'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x28B2B7B2' in module 'cellDmuxPamf'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x9728A0E9' in module 'cellDmuxPamf'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x1A5B72DD' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x32DA1344' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x3B95270D' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x4A1964A6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x52BB9416' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x540B43AE' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x5A0355CF' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x60D0F4FA' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6B49A7C7' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6D1F7D3F' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x96C2A2D9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xA0D447EB' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD09740F6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD8D930BC' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xDC6F4FF1' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE3072DF9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE36F2A6C' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE9FFF717' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF007F937' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF4E8D559' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xFF05DD1F' in module 'libsmvd2'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
E {PPU[0x1000000] Thread (main_thread) [0x01531ee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/reg_road.edat” [1]
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300d100, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300d000, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bc00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxSetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxDisableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxReleaseAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxEnableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxClose' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStreamAndWaitDone' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenExt' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxFlushEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenEx' in module 'cellDmux'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x28B2B7B2' in module 'cellDmuxPamf'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x9728A0E9' in module 'cellDmuxPamf'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x1A5B72DD' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x32DA1344' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x3B95270D' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x4A1964A6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x52BB9416' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x540B43AE' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x5A0355CF' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x60D0F4FA' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6B49A7C7' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6D1F7D3F' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x96C2A2D9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xA0D447EB' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD09740F6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD8D930BC' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xDC6F4FF1' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE3072DF9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE36F2A6C' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE9FFF717' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF007F937' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF4E8D559' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xFF05DD1F' in module 'libsmvd2'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x01464c14]} '_sys_interrupt_thread_disestablish' failed with 0x80010005 : CELL_ESRCH [1]
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300d100, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300d000, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bc00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxSetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxDisableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxReleaseAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxPeekAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAuEx' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxGetAu' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryEsAttr2' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStream' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpen' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxEnableEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxClose' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxQueryAttr' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxResetStreamAndWaitDone' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenExt' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxFlushEs' in module 'cellDmux'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function 'cellDmuxOpenEx' in module 'cellDmux'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x28B2B7B2' in module 'cellDmuxPamf'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked variable '0x9728A0E9' in module 'cellDmuxPamf'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x1A5B72DD' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x32DA1344' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x3B95270D' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x4A1964A6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x52BB9416' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x540B43AE' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x5A0355CF' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x60D0F4FA' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6B49A7C7' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x6D1F7D3F' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0x96C2A2D9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xA0D447EB' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD09740F6' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xD8D930BC' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xDC6F4FF1' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE3072DF9' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE36F2A6C' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xE9FFF717' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF007F937' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xF4E8D559' in module 'libsmvd2'
E {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} LDR: Already linked function '0xFF05DD1F' in module 'libsmvd2'
S {PPU[0x1000012] Thread (_libsail-control) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300e000, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300df00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000012] Thread (_libsail-control) [0x01471038]} sys_prx TODO: _sys_prx_unload_module(id=0x2300bc00, flags=0x0, pOpt=*0x0)
E {RSX [0x08620d4]} RSX: GL format mismatch (data cast?). Sized ifmt=0x88F0 vs Src ifmt=0x8058 x347
E {PPU[0x1000000] Thread (main_thread)} Stat: 'cellKbClearBuf' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [x7]
E {PPU[0x1000000] Thread (main_thread)} Stat: 'cellKbRead' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [x13426]
E {PPU[0x1000001] Thread (SpursHdlr1) [0x014fb604]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000007] Thread (Streamer unpack thread) [0x0054fcf0]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000006] Thread (Streamer loader thread) [0x0054fcf0]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000003] Thread (spu_printf_handler) [0x001a5b20]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (_gcm_intr_thread) [0x014d833c]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100000b] Thread (AK::BankManager) [0x0029becc]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000a] Thread (AK::IOThread) [0x0030e35c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000005] Thread (Task_Bagger_Impl::Worker thread) [0x0054fcf0]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000008] Thread (Streamer loader thread) [0x0054fcf0]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000009] Thread (Streamer unpack thread) [0x0054fcf0]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000f] Thread (_sys_MixerChStripMain) [0x00270c80]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000f] Thread (_sys_MixerChStripMain)} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x198600]
E {PPU[0x1000010] Thread (_sys_mixerSurBusReq) [0x00269424]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000c] Thread (AK::EventManager) [0x002d6704]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100000d] Thread (User_PS3) [0x00258448]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x100000e] Thread (Network_Connection_Manager) [0x00258448]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000013] Thread (_libsail-adec_copy) [0x017214ec]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000014] Thread (_libsail-adec_copy) [0x017214ec]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x0026c704]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000011] Thread (_cellsurMixerMain)} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x24825]
E {PPU[0x1000012] Thread (_libsail-control) [0x017128fc]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000015] Thread (_libsail-vdec_copy) [0x01723284]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000016] Thread (Trophy thread) [0x0054fcf0]} 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001a] Thread (_libsail-source_fs) [0x01465ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000028] Thread (hkSpuUtil Helper) [0x00572634]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread (SpursHdlr0) [0x014f948c]} 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]`

![image](https://user-images.githubusercontent.com/9620510/52540300-fbcb1e00-2d7f-11e9-8dbc-0bcec4ea5859.png)

**Comment by uaqlover** [comment]
Pro Evolution Soccer 2014
Pro Evolution Soccer 2015
Pro Evolution Soccer 2016
Pro Evolution Soccer 2017
Pro Evolution Soccer 2018

Game starts with "Interpreter (fast)", but is not working with LLVM.
[RPCS3 2014.log.gz](https://github.com/RPCS3/rpcs3/files/2976140/RPCS3.2014.log.gz)
[RPCS3 2015.log.gz](https://github.com/RPCS3/rpcs3/files/2976141/RPCS3.2015.log.gz)
[RPCS3 2016.log.gz](https://github.com/RPCS3/rpcs3/files/2976144/RPCS3.2016.log.gz)
[RPCS3 2017.log.gz](https://github.com/RPCS3/rpcs3/files/2976145/RPCS3.2017.log.gz)
[RPCS3 2018.log.gz](https://github.com/RPCS3/rpcs3/files/2976146/RPCS3.2018.log.gz)

**Comment by uaqlover** [comment]
CounterSpy™ [NPUA80870]

Game starts with "Interpreter (fast)", but is not working with LLVM.

[RPCS3 CounterSpy™ [NPUA80870].log.gz](https://github.com/RPCS3/rpcs3/files/2976657/RPCS3.CounterSpy.NPUA80870.log.gz)

**Comment by elad335** [comment]
Retest with #5749 games which die with "unregistered ppu function" (most of the games here).
Also report performance changes compared to interpreter.

**Comment by digitaldude555** [comment]
With elad pr cash gun chaos goes ingame now, probably playable.

**Comment by D8174** [comment]
With the PR, Sid Meier's Civilization Revolution [BLES00238] now goes ingame with **LLVM + OpenGL** where it didn't before.

However I get this with **LLVM + Vulkan** when going ingame:
![error](https://user-images.githubusercontent.com/5130800/54715764-1dbc7b00-4b4c-11e9-9999-f2e92cb045b9.png)


**LLVM + OpenGL**
Ingame FPS: 3-6 idling (5-11 with Lower SPU priority)
**Interpreter (fast) + OpenGL**
Ingame FPS: 2-4 idling (3-6 with Lower SPU priority)
**Interpreter (fast) + Vulkan**
Ingame FPS: 2-4 idling
**Interpreter (precise) + Vulkan**
Ingame FPS: 2-4 idling

**Comment by legend800** [comment]
Unfortunately, Splatterhouse mem error with PPU LLVM not impacted. Still get it at the beginning of the levels. You can load a lvl with PPU Inter., save and then load save with PPU LLVM as a workaround. 

F {PPU[0x1000000] Thread (main_thread) [0x00df5054]} MEM: Access violation reading location 0x11e

![2019-03-20 18_20_26-Window](https://user-images.githubusercontent.com/20983844/54728730-dbd80880-4b3c-11e9-96c8-29c2c8c7dc33.png)

**Comment by Zangetsu38** [comment]
it is fixed for me, Like AMY/Killzone 3/the evil within
![image](https://user-images.githubusercontent.com/5261759/54730171-ba503e80-4b87-11e9-9a8b-c72ca00cfd7e.png)

**Comment by elad335** [comment]
Initia D Extreme Stage is fixed in #5749

**Comment by elad335** [comment]
I won't bump llvm cache version again so for testing you must delete rpcs3/cache dir contents manually.
Can someone test Sonic Unleased issue with my pr?

**Comment by Emulator-Team-2** [comment]
Now these games work with PPU LLVM.  #5749  👍 
-Silent Hill: Homecoming  
-Initial D Extreme Stage
-Way of the Samurai 3

![1](https://user-images.githubusercontent.com/38318848/54782979-82490a00-4c20-11e9-8882-48cb527c0927.png)
![2](https://user-images.githubusercontent.com/38318848/54782854-2b433500-4c20-11e9-8d69-1edd3e4bdf85.png)
![3](https://user-images.githubusercontent.com/38318848/54782868-31391600-4c20-11e9-9db7-2aafdba57365.png)

**Comment by elad335** [comment]
@legend800 Whats the current status of splatterhouse with the pr?

**Comment by legend800** [comment]
@elad335 Thanks for asking. Checked latest build, cleared cache but still no change. :(

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2997137/RPCS3.zip)

Let me know if there's anything else you need. 

This game is so close to being playable (PPU Inter. = 10 fps). It's just something screwy at the start of levels. Fingers crossed you can figure out this long standing issue to make this (awesome) game fully playable in this PR.

**Comment by scribam** [comment]
I would be interested to know if PR https://github.com/RPCS3/rpcs3/pull/5797 also helps some games to run with PPU LLVM. Let me know if you notice any changes.

**Comment by digitaldude555** [comment]
@scribam  unity games and cash gun chaos are unchanged with your pr.

**Comment by digitaldude555** [comment]
Close issue or...?

**Comment by elad335** [comment]
Retest and report what has changed, if there are only handful of games left here can close and repopen new issue.

**Comment by digitaldude555** [comment]
Alright, I can test mariosonics unchecked games. So far alienspidy, constant c and cosmophony work with LLVM.

**Comment by MarioSonic2987** [comment]
Due to there's only a few games which still don't work with PPU LLVM, I'll close this issue and reopen a new one.
