### ISSUE TITLE
Subloaded elf issues

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#2969]
Multipart games such as NPEB01186 (Zone of enders HD Collection) which allow you to boot 2 or more subgames don't currently function properly.

When the subgame elf is loaded the emulator stops after this (log)
```
·W 0:01:06.777472 {PPU[0x1000000] Thread (main_thread) [0x00c4f140]} sys_lwmutex: _sys_lwmutex_create(lwmutex_id=*0xd0010488, protocol=0x2, control=*0x20032640, arg4=0x80000001, name=0x616964656d5f73, arg6=0x0)
·W 0:01:06.777481 {PPU[0x1000000] Thread (main_thread) [0x00c499e0]} cellGame: cellGameBootCheck(type=*0x185b424, attributes=*0x185b428, size=*0x1234680, dirName=*0xd00106d0)
·E 0:01:06.777540 {PPU[0x1000000] Thread (main_thread) [0x00c499e0]} cellGame: cellGameBootCheck(): Unknown CATEGORY: 
·W 0:01:06.777546 {PPU[0x1000000] Thread (main_thread) [0x00c499f8]} cellGame: cellGameContentPermit(contentInfoPath=*0x185b322, usrdirPath=*0x185b3a2)
·E 0:01:06.777551 {PPU[0x1000000] Thread (main_thread) [0x00c499f8]} 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE
·W 0:01:06.777569 {PPU[0x1000000] Thread (main_thread) [0x00751318]} sys_memory: sys_memory_container_create(cid=*0x1b59164, size=0x4c00000)
·W 0:01:06.777612 {PPU[0x1000000] Thread (main_thread) [0x00751344]} sys_memory: sys_memory_allocate_from_container(size=0x4c00000, cid=0x1, flags=0x200, alloc_addr=*0x1b59168)
·W 0:01:06.777898 {PPU[0x1000000] Thread (main_thread) [0x00c496d0]} sys_io: cellPadInit(max_connect=7)
·S 0:01:06.799993 {PPU[0x1000000] Thread (main_thread) [0x00c496d0]} HLE: [DS4] Controllers found: 1
```

I assume its meant to inherit the parent game sfo or something along those lines.

Also booting of the subgames manually will result in them attempting to read files from this location
```
/dev_hdd0/game/NPEB01186/USRDIR/data/
```
This location does not physically exist, and from what i can tell
```
/dev_hdd0/game/NPEB01186/USRDIR/%subgameFolder%
```
is meant to be mounted to the data directory.

Moving all of the files around manually and booting the sub game will allow it to load (this game has terrible rsx issues however)

The subgame itself seems to be loaded by this
```
·W 0:01:04.796176 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sceNp: sceNpDrmProcessExitSpawn2() -> sys_game_process_exitspawn2
·W 0:01:04.796197 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sceNp: klicensee: 0xd001076d
·! 0:01:04.821441 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sceNp: npDrmIsAvailable(): KLicense key 66113e697a8a65ec5d58b1f62cc62606
·! 0:01:04.856423 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} LDR: Loading RAP file EP0101-NPEB01186_00-ZOEHDMAINGAME001.rap
·W 0:01:04.865345 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: sys_game_process_exitspawn2()
·W 0:01:04.865365 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: path: /dev_hdd0/game/NPEB01186/USRDIR/ZoE2/ZoE2_ProjectFinal_HDD.ppu.self
·W 0:01:04.865370 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: argv: 0xd0010764
·W 0:01:04.865375 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: envp: 0x0
·W 0:01:04.865378 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: data: 0xd0010980
·W 0:01:04.865381 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: data_size: 0x12c
·W 0:01:04.865385 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: prio: 1001
·W 0:01:04.865388 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: flags: 32
·S 0:01:04.865404 {PPU[0x1000000] Thread (main_thread) [0x001e0740]} sysPrxForUser: Process finished
```

The argument passed is ```ZoELauncher0```

[zoe2.log.txt](https://github.com/RPCS3/rpcs3/files/1132878/zoe2.log.txt)

**Comment by Dangles91** [comment]
I had a similar problem with BLUS30754  (Prince of Persia Trilogy 3D) which was resolved by retaining the calling games' app_home location when loading via `sys_game_process_exitspawn2` . However, the file and folder structure for these two multi-game discs are completely different. The only problem with BLUS30754 was a critical error when loading trophy data.

I did some further testing with NPEB01186 which has lead me down a rabbit hole of attempting to launch the child games with the provided argv and envp values. My hypothesis (which is likely incorrect) is that though game developers are supposed, this game launcher may be using the `ZoELauncher0` argument to access files or offset the system path directly.

**Comment by scribam** [comment]
@clienthax Is it still an issue? I think Devil May Cry: HD Collection had the same problem and it was fixed (see https://rpcs3.net/blog/2017/09/01/progress-report-august-2017/)

**Comment by AniLeo** [comment]
Needs retesting

**Comment by Lemiru** [comment]
@AniLeo Tested Zone of the Enders HD Collection and the problem is still present. (Propably) the only game collection that works is DMC HD collection and it's propably because in this collection (unlike Zone of the Enders HD Collection) .SELF files of each game are located in the same folder as EBOOT.BIN instead separate folders for each game.

**Comment by clienthax** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1416335/RPCS3.log)

Still an issue

**Comment by clienthax** [comment]
Ok, the problem appears to be that in cellGameBootCheck, as the catagory is blank, the content_permission is never made.
If i return cell_ok in cellGameContentPermit instead of the error, the game 'loads'
Tryed creating the fxm in bootcheck but it seems to just hang but thats prob because im not sure what its meant to be anyway ;)

**Comment by scribam** [comment]
I think this issue is fixed in master, I can boot the two games from Zone Of Enders HD Collection by selecting them in the menu.
Can someone else confirm?

@Dangles91 What is the status for Prince of Persia Trilogy 3D with the latest build?

**Comment by Asinin3** [comment]
ZoE collection, gow collection (volume 1 & 2) DMC collection, KH 1.5 and 2.5 remix collections, sly cooper trilogy and more all have working boot menu's. Can't think of too many more off the top of my head.

I think it's pretty safe to close this, although there may be a few that are edge cases.
