### ISSUE TITLE
Geforce v390.65: No vulkan device was created

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#4036]
![gpu_setting](https://user-images.githubusercontent.com/31347274/34721611-a97945ac-f543-11e7-9800-4bee0cca6368.png)

Hi,
since hi have installed this version of driver i've this error: 

·F 0:00:06.870879 {rsx::thread} class std::runtime_error thrown: No vulkan device was created

with every games .

Regards .
 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1615083/RPCS3.zip)

**Comment by yxmline** [comment]
Under "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers", create a new REG_DWORD, its has to be named "C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5601d21ccd639df9\nv-vk64.json", and the value is 0.
- -new driver install bug

**Comment by kd-11** [comment]
Confirmed to be a driver installation bug. Deregistering the manifest kills vulkan including the diagnosis tools provided by khronos like vulkaninfo.

**Comment by nex86** [comment]
It's C:\Windows\System32\DriverStore\FileRepository\nvmii.inf_amd64_463ff046fd545b4a\nv-vk64.json
for Notebook graphic cards.

**Comment by RiotDX** [comment]
Can confirm that the issue is present, and yxmline's solution works, BUT... the specific folder name will differ based on the particular GPU chip and driver version you have installed, so don't use the exact folder he suggests. Instead, navigate to C:\Windows\System32\DriverStore\FileRepository and search for the file named nv-vk64.json.  If there are multiples, choose the one that was created most recently. Then use the full path of that file as the registry value as stated by yxmline.

**Comment by cybertronicgames** [comment]
Thanks for the info @yxmline! I had to find the right folder path which was "C:\Windows\System32\DriverStore\FileRepository\nvdmi.inf_amd64_423cc2fecd1c7121\nv-vk64.json" & opened regedit location "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers" & then created the new REG_DWORD & set the value to 0. This worked for me.
![screenshot 70](https://user-images.githubusercontent.com/14711758/34791098-8953e180-f609-11e7-879d-51781a8f2fde.jpg)

**Comment by cybertronicgames** [comment]
Navigate to C:\Windows\System32\DriverStore\FileRepository and search for the file named nv-vk64.json to get the right path for the new REG_DWORD file.

**Comment by isshininu** [comment]
![_2018_01_10_23_48_39_713](https://user-images.githubusercontent.com/6324523/34792240-cfa5322c-f660-11e7-83c0-6f20860771ec.png)

Is this value OK?

**Comment by cybertronicgames** [comment]
@isshininu The path is wrong! You might have to rename it to the correct path for it to work. Navigate to C:\Windows\System32\DriverStore\FileRepository and search for the file named nv-vk64.json.
![screenshot 71](https://user-images.githubusercontent.com/14711758/34792668-65885f9c-f60e-11e7-8ad9-3e8d63888058.png)
![screenshot 72](https://user-images.githubusercontent.com/14711758/34792674-69124b64-f60e-11e7-8597-a0f292800175.png)

**Comment by cybertronicgames** [comment]
@isshininu My path was "C:\Windows\System32\DriverStore\FileRepository\nvdmi.inf_amd64_423cc2fecd1c7121\nv-vk64.json" but, will be different for you because your GPU is different. You will have to search for the nv-vk64.json file.

**Comment by isshininu** [comment]
B-but i didn't change anything in registry by myself!
I have a laptop, nvidia driver version is 390.65.

vulkaninfo works, Vulkan device present in RPCS3.

**Comment by cybertronicgames** [comment]
@isshininu OK, that's good then! Yours is working properly.

**Comment by cybertronicgames** [comment]
@isshininu The value "0" zero is OK.

**Comment by Zangetsu38** [comment]
i don't have this probleme with my build compilled myself, but i have this with build appveyor, @kd-11 archive vulkan with lib inside have never update, maybe need update archive lib submodule for appveyor

**Comment by kd-11** [comment]
No version will ever work without an icd registered. This is very easy to show - delete the icd key and boot any vulkan application. Most applications will fall back to opengl or d3d if the icd key is missing since the runtime cannot see the hardware driver.

**Comment by Zangetsu38** [comment]
Fixed, with update Vulkan.7z
https://ci.appveyor.com/project/Zangetsu38/rpcs3/build/0.0.4-6709/artifacts

**Comment by redxehanort** [comment]
It worked for me, my location is C:\Windows\System32\DriverStore\FileRepository\nvpcdi.inf_amd64_72fbac6575d684e6\nv-vk64.json

Be sure to take the nv-vk64.json file with the most recent date

**Comment by AniLeo** [comment]
@Zangetsu38 that's because new vulkan versions have detection other than using icd register key. Applications/games compiled against old vulkan versions will not work and fall back to OGL/D3D as kd-11 said above. kd-11 opened a PR to update Vulkan, but this is still a problem with NVIDIA and Intel drivers, since they should be registering the icd key, otherwise they're breaking compatibility with applications compiled for older Vulkan libraries.

**Comment by Zangetsu38** [comment]
@redxehanort don't needed change that, this probleme is now fixed, soon on master

**Comment by Dani1977** [comment]
I have removed regedit key, and with 0.0.4-7626 works perfectly .
Thanks, regards .

**Comment by cybertronicgames** [comment]
Rpcs3 runs without the key but, can Xenia emu run with the key removed?

**Comment by msh4izee** [comment]
i tried the regedit method C:\Windows\System32\DriverStore\FileRepository\nvpcdi.inf_amd64_72fbac6575d684e6\nv-vk64.json
but still not working.....
plz give me another ssolution for this

**Comment by AniLeo** [comment]
This is no longer an issue for a long time, don't dig up old issues to ask for support, use the appropriate support channels. You have broken video entries.

**Comment by msh4izee** [comment]
what do you mean by appropriate support channels???
i am having this issue right now..
i tried all these methods but still cant get vulkan option in rpcs3..
can u help me or not?

**Comment by AniLeo** [comment]
Read the issue guidelines. The appropriate support channels are either Discord or the Forums, this is not a helpdesk.

**Comment by azrabrijer** [comment]
the problem is still relevant for my r5 m330 on manjaro
