### ISSUE TITLE
Warhawk background video playback eventually corrupts

### ISSUE THREAD

**Issue by zekesonxx** [RPCS3/rpcs3#4167]
Tested on cce0ad0c35499697b45b3fd2fbbc5d2fdce19e98

Warhawk plays a video in the background of the main menu. If you leave the game running long enough (amount of time varies), it will eventually get corrupted, with accompanying visual artifacts and ffmpeg errors.

Happens regardless of interpreter/recompiler settings. Even tried LLEing `libvdec`, no change.

Example:

![](https://i.imgur.com/2RcEtAm.png)

The video file in question (`$WARHAWK/PS3_GAME/USRDIR/movies/clouds_avc_ac3.avi`):

```
$ ffprobe -hide_banner clouds_avc_ac3.avi
Invalid return value 0 for stream protocol
    Last message repeated 1 times
Input #0, avi, from 'clouds_avc_ac3.avi':
  Duration: 00:00:36.97, start: 0.000000, bitrate: 12292 kb/s
    Stream #0:0: Video: h264 (Baseline) (H264 / 0x34363248), yuv420p(progressive), 1280x720, 12296 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc
```

Plays fine with no errors in both VLC and mpv.

Logs:
* [rpcs3-stderr.txt](https://github.com/RPCS3/rpcs3/files/1713993/rpcs3-stderr.txt)
* [RPCS3-Warhawk-corruption.log.gz](https://github.com/RPCS3/rpcs3/files/1713994/RPCS3-Warhawk-corruption.log.gz)
* [RPCS3-Warhawk-corruption-LLElibvdec.log.gz](https://github.com/RPCS3/rpcs3/files/1714010/RPCS3-Warhawk-corruption-LLElibvdec.log.gz)
* [TTY.log](https://github.com/RPCS3/rpcs3/files/1714000/TTY.log)

**Comment by zekesonxx** [comment]
It's also worth noting that the corrupted playback does not impact the game itself, the menus continue functioning and you can enter a game fine.

**Comment by dio-gh** [comment]
Needs retesting, though I think this is probably still a valid issue.

**Comment by RainbowCookie32** [comment]
Tested on latest master. The issue seems to be fixed with LLE libvdec now, otherwise it still breaks after a while.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3721962/RPCS3.log.gz)
[RPCS3_llevdec.log.gz](https://github.com/RPCS3/rpcs3/files/3721977/RPCS3.log.gz)

**Comment by elad335** [comment]
So it's an HLE cellVdec issue, should keep open.
ideally HLE load should be working properly.

**Comment by digitaldude555** [comment]
@RainbowCookie32 can we get an update friend.

**Comment by benderscruffy** [comment]
still an issue

**Comment by NateDogg1232** [comment]
I can attest that this is still an issue. The video will just stop playing as well over time.

**Comment by Megamouse** [comment]
Please test with #11754

**Comment by RainbowCookie32** [comment]
Still happens on that PR
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8477457/RPCS3.log.gz)

**Comment by Megamouse** [comment]
try again please

**Comment by RainbowCookie32** [comment]
Seems fixed. Left the game running for 10 minutes and the video kept playing, it'd freeze in less than 5 minutes before.
