### ISSUE TITLE
Regression: God of War III [BCES00510] (#4162)

### ISSUE THREAD

**Issue by spyropt** [RPCS3/rpcs3#4236]
@kd-11 After pr #4162  gow3 disc version BCES00510 stopped working it just show a black screen
fps goes from 60 to 0.96fps and stays there
There are other reports from users with the same problem, i did mention this on the pr.
GOW3 (demo) NPUA70080 works fine

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1772279/RPCS3.log.gz)

**Comment by jobs-git** [comment]
.Actually it was from another PR that was described here https://github.com/RPCS3/rpcs3/issues/4183 but they closed it anyway.

**Comment by spyropt** [comment]
nope tested and retested confirmed by other users...
the only thing missing is pinpoint the exact commit 
i think kd-11 mentioned that it was a race condition so probably its going to remain like this for a while, that's why i never "reported" this before and the game was barely "ingame" because in most of the cases it would hang on the cinematics even before this regression

**Comment by Josivan88** [comment]
@spyropt 
the same regression problem is occurring with me and many others that i see on the internet, all the developers are testing only the demo, which is OK, but the complete version [BCES00510] is suffering regression.
The game is very stable to me before this problematic PR, and very stable to other players for many hours playing:
https://www.youtube.com/channel/UCL1l0MaYA5rZb4ozhjsyzZQ

**Comment by FabioZumbi12** [comment]
@Josivan88 What's the latest build number is stable to run GOW 3?

I having the same issue: Black Screen at 0,99fps

**Comment by Josivan88** [comment]
@FabioZumbi12 the version with the name 
rpcs3-v0.0.4-2018-02-12-95c6ac69_win64

**Comment by Xcedf** [comment]
investigated this issue commit 89c548b5 caused this for the first time
removing lines 
if (!cached_dest->is_locked())
{
	lock.upgrade();

	cached_dest->reprotect(utils::protection::no);
	m_cache[get_block_address(cached_dest->get_section_base())].notify();
}
from texture_cache.h fixes this for recent versions
and returns higher fps in Beyond Two Souls Demo
![22](https://user-images.githubusercontent.com/7060586/37562954-07309278-2a86-11e8-9c91-90cdcb758a67.jpg)

kd-11 please take a look

**Comment by kd-11** [comment]
Thats not the problem, the hanging/slowdown is a side effect of the exception handler. That data area is constantly in use by both cell and rsx causing too many collisions that are not handled properly. Texture cache is correct to reprotect regions that are being read by cell.

**Comment by Zangetsu38** [comment]
yes, with remove this code game re works without cpu blit, and so can use scaling, but same with cpu blit, big slow speed on menu after few sec, passed 20 fps to 3 fps

**Comment by kd-11** [comment]
Retest with current master. Changes to mfc will have definately affected some unstable games like gow3

**Comment by Zangetsu38** [comment]
for moment, on laster master, game is broken, like glibality all

**Comment by Josivan88** [comment]
Same as @Zangetsu38, not crash but a black screen and 60fps forever with default settings, but with CPU blit is possible to go ingame.

**Comment by kd-11** [comment]
An update:
After investigating possible causes of this issue it was discovered to be caused by a timing bug. When the emulator enters a violation handler the faulting thread spends is seen by the game to have stalled and everything breaks down due to either a timeout or classic desynchronization. Stopping the virtual timers when modifying guest process memory works and allows the game to boot but a clean solution is needed.

**Comment by aakh1361** [comment]
For Me run  GODIII with build 0.0.5-6869
select CPU Blit + Set SPU Threads to 1

**Comment by Josivan88** [comment]
@aakh1361 the problem is different, with CPU blit always was possible to go ingame, but before certain PR CPU blit was not needed, as KD-11 said, this seems to be a synchronization problem that must be solved.

**Comment by kd-11** [comment]
It works without cpu blit now. Might still need WCB or it becomes extremely bright in some places.

**Comment by printedshelf13** [comment]
The game starts perfectly without any errors.....the cinematics would run at 30fps but as soon as the gameplay starts the fps fall down to 4-5 fps...
MY Graphic card details: nvidia geforce gtx 1050(4gb)
![screenshot 3](https://user-images.githubusercontent.com/39807346/40799845-51103d9a-652c-11e8-96b5-ac0327a48b18.png)
![screenshot 5](https://user-images.githubusercontent.com/39807346/40799847-51b3465c-652c-11e8-82ae-63b4a96958bd.png)
![screenshot 7](https://user-images.githubusercontent.com/39807346/40799849-52133f4e-652c-11e8-9522-f19d6f713714.png)

**Comment by Josivan88** [comment]
I can confirm partially what @spyropt  said, on last master 0.0.5-6880, and i7 4790 no TSX support I have a complex situation:
On the first try with default settings, the game goes up to the menu, hang for no reason.
[RPCS3.log1.gz](https://github.com/RPCS3/rpcs3/files/2060744/RPCS3.log1.gz)
And after that enabling WCB, for example, RPCS3 stops working at the shader load, without not even goes to the intro, and not generate a log file. trying many settings does not seem to increase the success.
My general conclusion is: the game now not require CPU blit for some users, but now, even with CPU blit the game seems very unstable. more than before.
@spyropt maybe try a clean install, with nothing precompiled like LLVM cache or shader Cache.

**Comment by Zangetsu38** [comment]
Like lot other games, now get hang if run on no tsx cpu

**Comment by spyropt** [comment]
@Zangetsu38  yes there are several regressions including dark souls 2 that hangs before going ingame
my cpu is a 6/12threads but without avx or tsx :(
im seeing performance regressions also :(
i haven't had the time to report all the regressions,

**Comment by Shoegzer** [comment]
Experiencing similar issues here.  On a system with no TSX, Demon's Souls recently starting consistently hanging on loading old saves (and in the training section of a new game), and Bioshock now consistently hangs on loading a new level.

**Comment by jobs-git** [comment]
isn't ssse just removed? I cant remember the pr, but it was just removed recently, so those cpu without at least an avx would slow down. I hope some experts in ssse could improve its speed at par with avx so it could be brought back.

**Comment by AniLeo** [comment]
SSSE3 isn't removed. This specific regression was fixed though, I think it's safe to close.

**Comment by jobs-git** [comment]
Oh, I thought it was, I will try to test the recent build and back with a report.

**Comment by jobs-git** [comment]
vulkan not geting into menu. black screen stuck without any errors or fatal.

**Comment by Josivan88** [comment]
This issue must not be closed, the problem Was not solved for all users, non TSX users still have problems.

**Comment by kd-11** [comment]
This tracker was for a regression in rsx though, not tsx vs no tsx regression. Needs a nee issue for the other problems.

**Comment by MSDawood7** [comment]
While paying the game fps is stuck in 3
Cinematics nd other option have no problem but
While playing the game fps is stuck
