### ISSUE TITLE
Demon's Souls Glitches

### ISSUE THREAD

**Issue by IbanPetrov** [RPCS3/rpcs3#4302]
<Bubble in world3-2 (second tower before boss)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1822180/RPCS3.log.gz)

**PS3**![11](https://user-images.githubusercontent.com/37421626/37560656-2e2833fe-2a45-11e8-809f-a44b484ce805.jpg)
**RPCS3**
![b02](https://user-images.githubusercontent.com/37421626/58505998-f7900880-8196-11e9-8e19-3e97b5fb107f.jpg)

boss cap/hood or what is
**PS3**
![b05](https://user-images.githubusercontent.com/37421626/38221805-13d7948e-36ea-11e8-8ebc-0c6c0ae0712c.jpg)
**RPCS3**
![b01](https://user-images.githubusercontent.com/37421626/58504576-9b77b500-8193-11e9-8c93-f14832c58070.JPG)

layer ground in world 4-2(begin)
![b02](https://user-images.githubusercontent.com/35437970/58509219-b26fd480-819e-11e9-8b2b-b01c684d3957.jpg)
![b01](https://user-images.githubusercontent.com/35437970/58509233-bb60a600-819e-11e9-9a6b-97082b0bca66.jpg)

Round shield
![b04](https://user-images.githubusercontent.com/37421626/58507364-47240380-819a-11e9-8810-d85d924b3716.jpg)

Weird effect(rare)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1826780/RPCS3.log.gz)

![31](https://user-images.githubusercontent.com/37421626/37619821-9d23b094-2bcb-11e8-8f20-90c97456fa96.jpg)
![demonsouls01](https://user-images.githubusercontent.com/37421626/45994178-26e7f600-c09b-11e8-9fff-2c6d1651e079.png)
>

**Comment by kd-11** [comment]
These look like some kind of memory corruption or something. I certainly have never encountered any of them, with the exception of the first one which I could have missed. It is known that sometimes the game is not sending geometry for drawing (like the invisible soldier shield) but the cause is still unclear. The last picture is definately memory corruption (there are no easy ways around the root cause, it is triggered by warping using archstones and the proper fix is currently very slow). Are any of these persistent across restarts of the emulator? i.e save and quit, shut down rpcs3, restart and load back the save

**Comment by isshininu** [comment]
For example, invisible bubble in world 3-2 (first screenshot) persistent between all versions of emulator.

**Comment by kd-11** [comment]
First screenshot looks like the game didn't even draw it at all. This may be a bug in cell where the game thinks the bubble isn't there, or generates the draw geometry outside the viewable area, or a vertex bug in rsx which is less likely since one shield is also affected, but all other shields render correctly). The corruption after warping isn't going away any time soon unfortunately. Requires some rewrites in the emulator's memory manager with features that are usually not exposed by the operating system.

**Comment by Parthorisian** [comment]
For this game[blus30443] this kind of distortion isnt persistent
kd-11 wrote
> save and quit, shut down rpcs3, restart and load back the save
After these actions image is completely normal

**Comment by YaPeL** [comment]
I'm closing #3088 in favour if this more broad issue

**Comment by kd-11** [comment]
Retest and update for all reported issues here.

**Comment by YaPeL** [comment]
with the master branch it hangs at the intro 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2172918/RPCS3.zip)

**Comment by isshininu** [comment]
I'm afraid "bubble" issue is not fixed.
Tested on RPCS3 v0.0.5-7177-9e380a4a4
![- - 1152](https://user-images.githubusercontent.com/6324523/44012044-6998a872-9ecd-11e8-843d-08191e24933c.jpg)

**Comment by dukenukemx** [comment]
I'm having the same issue.

**Comment by dunestorm333** [comment]
Any ETA's for a fix?

**Comment by Parthorisian** [comment]
Two years passed and still no fix for this bug(

**Comment by Asinin3** [comment]
If you want to see visual issues looked at then you should be providing Renderdoc captures and RRC captures (to take a RRC, just open RPCS3's debugger and click RSX capture when you see the issue ingame) make sure you compress the captures though e.g with 7zip LZMA2 Ultra, it makes the files much smaller. Are we even sure that all the issues are still there?

**Comment by dunestorm333** [comment]
[Here is my RRC](https://mega.nz/#!DvA1QQRA!k762E0Mu9EjNuMTlPxbn6PefX3hx4gtcIFqMeDrlY7k)

**Comment by RevenantX** [comment]
> 
> 
> If you want to see visual issues looked at then you should be providing Renderdoc captures and RRC captures (to take a RRC, just open RPCS3's debugger and click RSX capture when you see the issue ingame) make sure you compress the captures though e.g with 7zip LZMA2 Ultra, it makes the files much smaller. Are we even sure that all the issues are still there?

Yes. Tested on v0.0.6-8368 Alpha [2019-07-13] . Issue still here

**Comment by RevenantX** [comment]
my RRC.
[BLES00932_20190714181301_capture.zip](https://github.com/RPCS3/rpcs3/files/3390285/BLES00932_20190714181301_capture.zip)

**Comment by arkbg1** [comment]
@Parthorisian is this common for RCPS or indicative of a dead project? My gf and I just started DeS after I guided her through DaS, is there anything we could do to get RCPS3/DeS help?

**Comment by mavethee** [comment]
@arkbg1 RPCS3 is not dead :v Just head to RPCS3's discord, but if your problem will be solved depends on that if it's fixable ;)

**Comment by kd-11** [comment]
This bug happens very rarely and is not simple to fix. It is therefore not very high priority since most players will never even notice the missing blob in that one area. Compared to the other hundreds of bugs, instability and missing features, this is a relatively minor problem. Will it get fixed? Sure, but not before we have other more serious problems squared out.

**Comment by RevenantX** [comment]
@kd-11 well invisible soldier shield - is always invisible. 100% reproduce...

**Comment by kd-11** [comment]
Yea, its the only shield affected though. The problem is that it seems to not actually have been sent to the graphics card at all, the game considers the shield to be invisible but present. This means debugging as a visual bug hit a dead end early on in this game's emulation and disassembling the eboot to find the conditions that trigger this is not easy.

**Comment by YaPeL** [comment]
@kd-11 so the shield issue its unreated to this one?? I'm gonna re open the other ticket then.

**Comment by kd-11** [comment]
I think its related though. I think in all of these some check is happening and the game thinks the geometry is not there. Or there is some kind of glitch that happens to just work on retail PS3, the firmware for retail can vary quite a bit and some releases have per-game hacks in the sprx files. I'll self-assign this one and review in the next fortnight, the emulator has changed a lot since this game was worked on two years ago.

**Comment by Parthorisian** [comment]
**kd-11** wrote
> 
> happens very rarely
> Yea, its the only shield affected though

WtF? I can clearly see all these 3 missing textures(bubble, cave floor and boss hat) excluding round shield though, between all versions of "official" master builds, since december 2017! Why just not consider to reason of this bug as unfixable for now?

**Comment by kd-11** [comment]
> WtF? I can clearly see all these 3 missing textures...

How much time does a player spend in these areas? Does it really justify abandoning the other hundreds of issues to resolve this specific one? This is the balancing act when in the initial stages of development. The bug was looked into without a resolution a while back. I already said I'd revise it again during the next fix cycle (I'm already working on another issue).

**Comment by TheFallender** [comment]
> How much time does a player spend in these areas? Does it really justify abandoning the other hundreds of issues to resolve this specific one? This is the balancing act when in the initial stages of development. The bug was looked into without a resolution a while back. I already said I'd revise it again during the next fix cycle (I'm already working on another issue).

Is it still useful if we continue giving the RRC files? If that could help fixing it, I think it's worth it and everyone that wants to get it fixed could help.

I could try looking at the files but I don't think I'm that deep in C++ to code it.

**Comment by Realmantik** [comment]
I've experienced with issue "Weird effect" once, but in Resident Evil 4.

**Comment by Canzah** [comment]
Unfortunately the issue is still there as of v0.0.6-8568

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/64362775-c89bf500-d017-11e9-92a3-f8849a39ebdc.png)
The good news is that I figured out why some stuff isn't showing up. The bad news is that the "bad" data looks to be completely intentional.

**Comment by dunestorm333** [comment]
@kd-11 As in, they messed with the rendering techniques to make emulation harder?

**Comment by kd-11** [comment]
The blendweights for the missing geometry are missing for seemingly no reason. This causes their verts to converge to a single point, and the blendweight being 0 also has the "benefit" of introducing NaNs through division by 0. The blendweights may be stored per object since the glitches are model specific, so idk why they're set to all 0 which hides the object. Its likely some bounding volume math is incorrect somewhere. In this case I'm referring to the pieces of "clothing" which btw also includes weapons attached to the character. Checked on hardware, if you give RSX zeroes it reads zeroes, which means there is no rendering bug per se; the glitch happens long before the information is sent to RSX for drawing. Further debugging would require reversing the model loading routines and the accompanying math involved.

**Comment by dunestorm333** [comment]
@kd-11 Nice job! This is FromSoftware we're talking about, most of their games up to DS2 are very buggy. I can only imagine what goes on underneath the hood...

**Comment by YaPeL** [comment]
cool! I know hacks are a nono, but can we get a hacked version that makes the geometry appear? or does that fix have other side effects too?

**Comment by Zerowalker** [comment]
What more bugs are there than this, haven't played the game so no spoilers please;p
But this seems quite big, the shield i can live with, is it all round shields or just a specific round shield?
But the areas seems more problematic, if it's someplace you go through (say a village or whatever),
or if it's a place you visit often, it would be very annoying and lose immersion if it's like a blank void.

I am not a fan of hacks but if it's possible to solve it by one that i would have to do myself i would do be fine with that.
I wouldn't want it in the emulator itself (unless it was temporary), cause hacks are just workarounds and we know how pcsx2 looks like nowadays;P

**Comment by Asinin3** [comment]
It's only the starting shield for the soldier class. All other shields render properly. As for the graphical issues in the areas it's only affecting a very small amount of things afaik. Many people have finished the game, it definitely runs more than well enough to be considered playable. Just has a few minor issues.

**Comment by Zerowalker** [comment]
Ah that's great!

**Comment by jokoputera** [comment]
is it solved with the latest release ?

**Comment by javsp** [comment]
> is it solved with the latest release ?

No.

**Comment by SlippyGuy** [comment]
The projectiles that Storm King fires are also invisible, making the fight more frustrating.

You can see it in this video here at 3:20: https://youtu.be/2KBnPuncULY?t=200

Although it is old, the issue still persists in the current build like these other missing graphics and probably happens due to the same problems as the others. I'm surprised I've seen no one mention it before.

**Comment by kd-11** [comment]
I played through this game recently and the purple projectiles were visible if that is what you're talking about.

**Comment by kd-11** [comment]
Ok, I see it now, although I never noticed they were missing, I always hide in the broken room and snipe from there.

**Comment by SlippyGuy** [comment]
Haha fair enough. 

Are there any plans to fix these graphical issues currently? They are the last few things that are keeping this title from being basically perfectly emulated as far as playability goes, although I understand that they are low priority and time may be best spent elsewhere.

**Comment by kd-11** [comment]
Yea, the problem is that if it takes more than 3 days to figure out what's going on, I have to move on to something else. The main blocker for me last time was that the mod tools for DS1 could not properly open the DeS models, which I need to do to figure out why the soldier shield is different from the other shields. This would have given me a starting point, but all of them refused to render the 3D model or show me the model's attributes without crashing. I could get some basic info out of them but not much else which made it a dead end. From the emulator point of view the game is "intentionally" passing in values that indicate to scale the object to 0 which is obviously not right. Maybe the DeS modding has come along enough that I could in theory try again and maybe get different results, but I'm not very hopeful for improvements on that front.

**Comment by SlippyGuy** [comment]
Ah, shame it's such a tricky bug. 

Yeah, modding tools at the moment seem to be a very limited debug menu patch. Although if texture mods are available then it might be possible to make a hacky fix for this until the issue is properly solved on the emulator side, or would simple texture mods not fix the issue? The collision boxes are at least all there and work properly.

**Comment by theoldsport** [comment]
@kd-11 there have been model/animation swap mods for DeS, drop by the souls modding discord if you find the time!- https://discord.com/invite/mT2JJjx

Perhaps Dropoff#1639 can help you (he managed to port DeS models to the DaS engine)

**Comment by csando** [comment]
I will send money to the person who solves this.

No way I am paying for a PS5 just for this game

**Comment by griever-gf** [comment]
Invisible shield bug is still presents in November, 2020.

**Comment by daedrixxx2** [comment]
The Spiral Rapier dropped by the gargoyles in Latria 3-2 is also invisible :/....

Will these bugs ever be fixed?

**Comment by SJalltheway5** [comment]
I was able to track down the particular models that are failing to render and edit the problematic weight values of most of them.  The edited models seem to render perfectly in RPCS3.  I've released what I have so far as a mod for the game.  Feel free to check it out:
https://github.com/SJalltheway5/DeS_MissingGeometryFix
https://www.nexusmods.com/demonssouls/mods/39

**Comment by csando** [comment]
Wow nice work. Is there a way this could be integrated without needing a mod?
Well done well done

**Comment by daedrixxx2** [comment]
FINALLY! Great work SJalltheway5. Now only the big heart in 3-2 and the dead miners in the webs in 2-1 are left :)

**Comment by jokoputera** [comment]
Maybe a patch for this particular problem until developer figure it out?

**Comment by csando** [comment]
@SJalltheway5 when you complete this work, I will be putting my money where my mouth is, re: my earlier post saying I'll send money to who solves it. I'm no baller but I can afford to send you some hard earned beer money

**Comment by Zerowalker** [comment]
@SJalltheway5 
Yeah same as @csando , even though i already ran the game, i really wanted this fixed, better late than never!
It's very much appreciated, and i am quite interested in how you do it, finding the models and patching them so if you are willing to educate a bit on this it would be awesome;P

**Comment by Canzah** [comment]
According to @SJalltheway5 on his Nexus page, it seems he fixed all remaining issues.

**Comment by csando** [comment]
Wow they did. too. @SJalltheway5 is there a way to make this a patch in RPCS3? And are you prepared to take my money? lol

**Comment by AniLeo** [comment]
Just a heads up, the correct fix for this one is to fix the rendering code directly, not through game specific patch
Maybe @kd-11 knows what's wrong now that there's a mod that fixes it on the game side - even if it's a bug that works by chance on the original hardware, RPCS3 needs to replicate such a thing in order for these to render

**Comment by kd-11** [comment]
I had it narrowed down to one of the vertex attributes streaming in. Disabling it from streaming (as though the attribute were disabled by the game) completely fixed the issue, but this was obviously incorrect as other games don't expect this, and real PS3 disagrees with the workaround. I'll revisit this later when I have some time, but there are a few "Epic"-level bugs I need to close first.

**Comment by csando** [comment]
> Just a heads up, the correct fix for this one is to fix the rendering code directly, not through game specific patch
> Maybe @kd-11 knows what's wrong now that there's a mod that fixes it on the game side - even if it's a bug that works by chance on the original hardware, RPCS3 needs to replicate such a thing in order for these to render

Thank you. My knowledge of this stuff is somewhere between "none" and "almost none". All I know is I am very grateful to all you working on this.

**Comment by kd-11** [comment]
Looking at the mod information, it seems to replicate the findings I had about bad weights, and adds dummy value for the weights instead of having 0s which causes geometry to collapse like a black hole to an infinitesimal point. I get the feeling the game somehow identifies that the model is missing weights and disables the attribute for real PS3, but I have yet to identify how exactly it does this.

**Comment by Zerowalker** [comment]
Oh, well it seems like we might be closer to a real solution than we were before, very impressive and many thanks!

But so if i get it right, the models got some data which basically will make it invisible cause the size is just as close to none as possible.
But even though they have that the ps3 still doesn't act upon it, which it should, so something happens with that data before it's actually passed to the ps3 for rendering?
Did i get that somewhat correctly xd?

**Comment by SJalltheway5** [comment]
Thanks to everyone showing their appreciation, though I absolutely agree with @AniLeo that a mod is not an appropriate long term solution.  It was merely intended as a stopgap for players.  If it potentially helps in some tiny way to make RPCS3 more accurate, I'm all the happier.

@csando I really appreciate the offer, but I couldn't take any money.  I made the mod purely out of love for the game and for the emulator enabling me to play it, and I felt like not sharing would make me a bad person. If anyone has money they feel truly compelled to give away, I would rather see it go to the devs.

As far as creating an RPCS3 patch, I'm sure it's possible to visually yield a similar result by patching the game's executable rather than patching specific game assets, but it's probably not something I'm going to be looking into.  I do acknowledge a patch would be more convenient than a mod, but it's currently a bit beyond my capabilities.

**Comment by Puxirepublic** [comment]
I got the fullscreen artificial dots, it's super rare, when switching the scene and the loading screen ends, it suddenly appeared, only got 2 times by far (played 20+ hours). Thought you might be interested.
![screenshot-2021_07_31_19_08_46](https://user-images.githubusercontent.com/5261049/127738565-f3c6aeea-15e2-4d8f-a1ff-c9d7b3d2a7f1.png)
Also the log,
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6911105/RPCS3.log.gz)

**Comment by Puxirepublic** [comment]
Finally beat the game today, and got one last a little surprised for the one last glitch here in the rolling credits screen, it's only showing the fully white screen in the whole time.

![Annotation 2021-08-20 142446](https://user-images.githubusercontent.com/5261049/130193084-fcb31692-a88d-4401-84bf-a9cfc8af2c16.png)

log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7019677/RPCS3.log.gz)


It's the first game that I have finished in RPCS3, just want to say thanks to the all of RPCS3's devs work.

**Comment by Darkhost1999** [comment]
> Finally beat the game today
Do you Happen to have save files for this issue. Seeing as you gotta beat the game to get that far having save files can save a ton of time testing.
