### ISSUE TITLE
New app image is not working in linux

### ISSUE THREAD

**Issue by oangelo** [RPCS3/rpcs3#4427]
I have just downloaded rpcs3-v0.0.5-6649-7303f04b_linux64.AppImage, but this version is not running any game that I was running before, like Demon's Souls and Arm of two. I am using Archlinux and tried many different configurations...

**Comment by qm3ster** [comment]
Saem in :b:ubuntu

**Comment by hcorion** [comment]
GPU, CPU, open source or closed source drivers, driver versions etc.

**Comment by distinctV** [comment]
I think I've had the same issue since around 0.0.5-6642 on ubuntu linux with cpu 7700k gpu 1080TI (driver 390.48 from nvidia linux download page), appimage download.

**Comment by neilfromit** [comment]
I'm also getting black screen on: (0.0.5-6449)

And the error ([RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1897086/RPCS3.log.gz)):

`E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed"`

I'm just running Ubuntu Artful (on wayland) with the onboard intel chip using oibafs latest drivers:

Linux 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 520 (rev 07)
Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
mesa-vulkan-drivers:amd64                  18.1~git1804101930.e29fac~oibaf~a                          amd64        Mesa Vulkan graphics drivers

I've tried OpenGL as well as Vulkan, tried lower native resolution down to 720x438 also tried a few PPU / SPU interpreter combinations as well. Finally tried the latest PS3 firmware and recompiling all the LLVM and shader caches etc... All to no effect, most attempts should be in the attached log.

Can also confirm I've tried build 6553 from the 22nd March and its working for me there.

**Comment by ArnaudE** [comment]
Same on Arch, compiled from Git.

**Comment by qm3ster** [comment]
This is so true, very true. I absolutely confirm it.

**Comment by 7oxicshadow** [comment]
I was just going to raise this issue.

I also get the "{rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed" error.

Just to help with debugging I am using Nvidia propitiatory drivers 390.48.

Fedora 27
i7 6700k @ 4.5ghz
16gb Ram
GTX 1070

**Comment by kd-11** [comment]
`{rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed` is not a real error

**Comment by AniLeo** [comment]
This should be fixed in master, retest

**Comment by qm3ster** [comment]
Still a black screen for me in rpcs3-v0.0.5-6655-da6f98f3_linux64.AppImage
(based on the last commit to master at the moment of writing)

**Comment by Caliel666** [comment]
@sibradzic how  to repack the appimage after extracting ?

**Comment by 7oxicshadow** [comment]
No need to repack. Just run the AppRun file within the squashfs-root folder.

i have tried removing the libglapi.so.0 from the appimage file and re-run it and it still fails in the same way for me.

Is there anything we can do to debug where the execution fails?

**Comment by Caliel666** [comment]
when i open Apprun it says "Could not display "Apprun"

**Comment by hcorion** [comment]
Thanks for looking into the issue, I think I should be able to upstream this.

> Isn't it time to start building proper distro package releases for RPCS3?

It's just a lot of work, and the AppImages work well enough. We already have a community effort for some distros, like `rpcs3-git` on Arch Linux, there is rpcs3 on the OBS for OpenSUSE users. We have an issue for a PPA, https://github.com/RPCS3/rpcs3/issues/2746, and it looks like someone has made an unofficial one.

**Comment by 7oxicshadow** [comment]
I dont think this is library related. At least not in my situation anyway. I have just stripped the appimage down to a minimum library requirement consisting of:

> libicudata.so.52
> libicui18n.so.52
> libicuuc.so.52
> libQt5Core.so.5
> libQt5DBus.so.5
> libQt5Gui.so.5
> libQt5Network.so.5
> libQt5Qml.so.5
> libQt5Widgets.so.5
> libQt5XcbQpa.so.5
> libtinfo.so.5

It still hangs during loading. I have just noticed in the log that I get the following entry:

`
E {PPU[0x1000000] Thread (main_thread) [0x01d93e58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]`

Does that provide any useful information?

**Comment by 7oxicshadow** [comment]
From the debug window:

Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 1001
Stack: 0xd0001000..0xd0100fff
Joiner: detached
Commands: 0
Last function: sys_cond_wait
Waiting: 46.471070s



Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 0
Stack: 0xd0102000..0xd0111fff
Joiner: 
Commands: 0
Last function: sys_timer_usleep
Waiting: 0.013748s



Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 200
Stack: 0xd0113000..0xd011afff
Joiner: 
Commands: 0
Last function: sys_event_queue_receive
Waiting: 80.691567s



Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 1001
Stack: 0xd011c000..0xd0123fff
Joiner: 
Commands: 0
Last function: sys_event_queue_receive
Waiting: 92.746632s



Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 1001
Stack: 0xd0125000..0xd0128fff
Joiner: 
Commands: 0
Last function: sys_spu_thread_group_join
Waiting: 100.528492s

Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 1000
Stack: 0xd012a000..0xd0139fff
Joiner: 
Commands: 0
Last function: sys_timer_usleep
Waiting: 0.000100s


Type: 10ppu_thread
State: 0x24[s|mem]
Priority: 1
Stack: 0xd013b000..0xd013efff
Joiner: 
Commands: 0
Last function: sys_event_queue_receive
Waiting: 0.015837s

Type: 9SPUThread
State: 0[]

TX: 66528190; Fail: 100590169 (0x0)
Raddr: 0x01b93100; R: 0x935b9747a2a
Tag Mask: 0x80000000
MFC Stall: 0x00000000
MFC Queue Size: 0

Type: 9SPUThread
State: 0[]

TX: 73921068; Fail: 105991917 (0x0)
Raddr: 0x01b93100; R: 0x9449bb16854
Tag Mask: 0x80000000
MFC Stall: 0x00000000
MFC Queue Size: 0

Type: 9SPUThread
State: 0[]

TX: 77687699; Fail: 113818320 (0x0)
Raddr: 0x01b93100; R: 0x94f9edae554
Tag Mask: 0x80000000
MFC Stall: 0x00000000
MFC Queue Size: 0


Type: 9SPUThread
State: 0[]

TX: 86400828; Fail: 138722218 (0x0)
Raddr: 0x01b93100; R: 0x965a4d2ba5e
Tag Mask: 0x80000000
MFC Stall: 0x00000000
MFC Queue Size: 0

Type: 9SPUThread
State: 0[]

TX: 103359151; Fail: 139396877 (0x0)
Raddr: 0x01b93100; R: 0x97836cf4342
Tag Mask: 0x80000000
MFC Stall: 0x00000000
MFC Queue Size: 0

**Comment by hcorion** [comment]
Does it work if you compile it yourself @7oxicshadow ?
I'm on Arch Linux with a GTX 1070 and driver version 390.48, and both the AppImage and self-compiled work fine for me.

Does both OpenGL and Vulkan work?

**Comment by hcorion** [comment]
Just run
```
gpg --recv-keys 11E521D646982372EB577A1F8F0871F202119294
```
which should let llvm40 build. RPCS3 does not work with the latest version of LLVM, only 4.x.
I really need testing done with rpcs3-git from the AUR.
rpcs3-bin will work, because it's about a month old.

Do you also have libxnvctrl, mesa and nvidia-utils installed @oangelo ? What GPU, specifically.

**Comment by oangelo** [comment]
@hcorion, that command doesn't work... I have added to ".gnupg/gpg.conf" the line "keyserver-options auto-key-retrieve" and now I can compile the llvm40. Now I will try to compile the rpcs3-git and test it... My video card is: 01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 660 Ti] (rev a1).
I have  ibxnvctrl, mesa and nvidia-utils installed!

**Comment by sibradzic** [comment]
@7oxicshadow, @Caliel666 & co:
> No need to repack. Just run the AppRun file within the squashfs-root folder.

I didn't run **Apprun** binary, but **rpcs3** one, found in extracted *squashfs-root folder/usr/bin*. I think **Apprun** will actually force loading of every lib from *squashfs-root folder/usr/lib*. This is how I made it work on Ubuntu 18.04:
```
./rpcs3-v0.0.5-6655-da6f98f3_linux64.AppImage --appimage-extract

mkdir squashfs-root/usr/_lib
mv squashfs-root/usr/lib/* squashfs-root/usr/_lib/
mv squashfs-root/usr/_lib/libpng squashfs-root/usr/lib/
mv squashfs-root/usr/_lib/libQt5* squashfs-root/usr/_lib/libicu* squashfs-root/usr/_lib/libpng* squashfs-root/usr/lib/

ln -s squashfs-root/usr/plugins/platform
ln -s squashfs-root/usr/plugins/platforms
ln -s squashfs-root/usr/plugins/bearer
ln -s squashfs-root/usr/plugins/imageformats
ln -s squashfs-root/usr/plugins/platforminputcontexts
ln -s squashfs-root/usr/plugins/xcbglintegrations
mv squashfs-root/usr/bin/qt.conf squashfs-root/usr/bin/rpcs3 ./

LD_LIBRARY_PATH=squashfs-root/usr/lib ./rpcs3
```

**Comment by 7oxicshadow** [comment]
Building from source still fails in the same way.

After loading a game, a GL/Vulkan window opens with a black screen and freezes. All CPU cores locked to 100%

**Comment by 7oxicshadow** [comment]
Interrupted during the freeze using GDB and tried to do a BT. Not sure if the attached file will tell you anything?

[out.txt](https://github.com/RPCS3/rpcs3/files/1921289/out.txt)

**Comment by oangelo** [comment]
@hcorion, I have installed the rpcs3-git package, but even so, still, no candy for me! I tried OpenGL and Vulkan, both give me just a black screen. If you need any other tests, just tell me.

**Comment by hcorion** [comment]
If you still have issues with just a black screen on RPCS3, please reply to issue #4460 providing the following information:
- Linux Distro
- Graphics Card
- Graphics Driver version
- Does it happen on both the AppImage and with self-compiled version.
