### ISSUE TITLE
Memory Mirror commit regression

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4566]
Found a few regressions
in 5d15d64e
1) Heavy Rain Demo [NPUA70112]
F {PPU[0x1000009] Thread (Read Chunk Thread) [0x0056dc9c]} MEM: Access violation writing location 0xd00c08f0
2) AMY [NPUB30613]
F {PPU[0x10000c4] Thread (CInfoManagerPS3) [0x00705074]} MEM: Access violation writing location 0xd0330c50
3)Gran Turismo HD Concept [NPEA90002] Speed regression
before
![6](https://user-images.githubusercontent.com/7060586/39970259-ffe3374a-56f0-11e8-8719-0b46d1660c00.jpg)
after
![12](https://user-images.githubusercontent.com/7060586/39970232-cf764818-56f0-11e8-93e5-44a94f796547.jpg)
did some extra debugging work for this on, since in the RP there were many versions of "Memory Mirror" i found out that 374dd7cb has fine speed and b87d632b regressed, the reason in VirtualMemory.cpp changes between two versions
There're maybe other regressions, but other my games seems to work fine

**Comment by Kravickas** [comment]
Heavy Rain regressed like month ago but nvm

**Comment by AniLeo** [comment]
Can someone confirm this is an issue in latest master and provide games that actually regressed on that PR and not on previous ones?

**Comment by Xcedf** [comment]
The issue is still exist on the latest master

**Comment by kd-11** [comment]
Added a fix for the performance issues with https://github.com/RPCS3/rpcs3/pull/4876 which has now been merged. Should restore GT HD performance.

**Comment by Xcedf** [comment]
Confirm, the performance part fixed

**Comment by kroaton** [comment]
Fight Night Round 4 recently regressed with a "MEM Access Violation" warning as well though I'm not sure on what build it happened.

The game used to be fully playable (apart from broken audio and occasional stutter) in #4424.

Force Cpu Blit does bypass the memory access violation but the player models are gone now (it might be some other regression or side effect of Force Cpu Blit).

**Comment by jobs-git** [comment]
I can confirm that the issue on D3 has already been fix in master.

**Comment by Xcedf** [comment]
All cases i've reported fixed now, closing this.
Thanks

**Comment by Kravickas** [comment]
Heavy Rain still stucked before menu. I dont know how about u.

**Comment by HenningJW** [comment]
Log?

**Comment by ErackGamer** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2338530/RPCS3.log.gz)
Still not able to boot Heavy Rain Demo, PPU LLVM, SPU ASMJIT, OpenGL.

**Comment by AniLeo** [comment]
Of course you can't, you're using an older build...

**Comment by ErackGamer** [comment]
Sh*t, I was sure I updated. Guess I'll test it again

**Comment by ErackGamer** [comment]
And there it boots, I feel so dumb
