### ISSUE TITLE
All The Evil Within [BLES01916] issues.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#5423]
1. Wrong texture blending cause lens effect to appears ahead all other textures.
![1597](https://user-images.githubusercontent.com/6324523/49997993-88d63e80-ffac-11e8-9b43-08000e033b53.png)

~~2. Unusually low FPS after intro developer logo while RSX Guest utilization (PS3) also remains low. Long response to controller input.~~ - fixed by #5437 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2679716/RPCS3.log.gz)

**Comment by kd-11** [comment]
Its not wrong texture blending, its a wrong shader coeffecient being generated somewhere, I already debugged this a while back. Low fps is expected as the game does not work with ppu llvm (unless this was fixed recently)

**Comment by isshininu** [comment]
LLVM/ASMJIT Recompilers were fixed somehow.

**Comment by kd-11** [comment]
You mean it now works with PPU LLVM? It used to throw an "unregistered PPU function" error.

**Comment by isshininu** [comment]
Yes, it works now

**Comment by kd-11** [comment]
In that case I shall review the workaround I had in place for this issue; I'm fairly certain I know what was wrong with it.

**Comment by kd-11** [comment]
1. PPU LLVM still does not work. Still crashes with unregistered function (the log spam hides the message)
2. Super low fps seems from some trophy issue where it tries to get the trophies endlessly, likely a recent regression with trophy changes.

I can only look into the lens effect, but the other problems are more serious. Needs regression testing to identify the start of the second issue.

**Comment by isshininu** [comment]
OK, I'll do testing later today.

**Comment by isshininu** [comment]
So, it looks like slowdown might be caused by this error spam:
E {PPU[0x1000016] Thread (PS3Trophies) [0x002d8abc]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x1a17680, arg=*0x300026e0, options=0x0)
E {PPU[0x1000016] Thread (PS3Trophies) [0x012409c4]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x30002784, count=*0x30002794)

**Comment by isshininu** [comment]
Yes, thanks

**Comment by isshininu** [comment]
Game crash with exception for some time now
F {RSX [0x0026dd0]} RSX: class std::runtime_error thrown: [texture upload buffer] Working buffer not big enough, buffer_length=268435456 allocated=257315840 requested=8388616 guard=33554432 largest_pool=16777728
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\ring_buffer_helper.h:78)
Not really an issue since it's unplayable, just a catch
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3039037/RPCS3.log.gz)

**Comment by kd-11** [comment]
Problems fixed with https://github.com/RPCS3/rpcs3/pull/5785. Requires CPU blit to show correct visuals and the issue is not so easy to work around with GPU blit. I have a patch that fixes the glow on my rsx_volatile branch, but ingame lighting is still broken without CPU blit.

**Comment by kd-11** [comment]
I'll close this one since its fixed with options and the underlying problem is known.
