### ISSUE TITLE
Fatal Texture Cache error in ModNation Racers

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5478]
OpenGL results in the following error before reaching the title screen.
`F {RSX [0x0068778]} RSX: class std::runtime_error thrown: Assertion failed: !cached.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:942)`

And Vulkan results in this error before the title screen too, but only when Write Color Buffers is enabled.
`F {RSX [0x000587c]} RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexturecache.h:844)`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2717559/RPCS3.log.gz)
This is probably caused by https://github.com/RPCS3/rpcs3/pull/5276
Still possible to go ingame with vulkan, just need to keep write color buffers off.

Edit: The disc version of the game seems to behave differently. Instead of getting those fatal errors I had this spammed in my log at the same spot before the title screen.
`E {RSX [0x0018628]} RSX: FIFO error: possible desync event x10849`

**Comment by kd-11** [comment]
Pretty sure this is fixed.

**Comment by kd-11** [comment]
Retest

**Comment by kd-11** [comment]
Ping @Asinin3

**Comment by Asinin3** [comment]
So i can get ingame with OGL now, but it did hang shorty after starting a race with no error written to log. However the Vulkan issue with WCB still appears to be there, it hangs RPCS3 before reaching the title screen like i described in the OP. The difference being that no error is written to the log now so I'm unsure if it was fixed and its a different issue now, or the error is just not being written to the log due to it crashing differently.

**Comment by Asinin3** [comment]
Okay I figured out a few things so here's my findings.
OpenGL - Crashes when race starts after a few seconds, fatal cache error is gone.
Vulkan - Goes ingame fine, but graphics are broken without WCB
Vulkan+WCB - Goes ingame just fine
Vulkan+WCB+MT RSX - Crashes where the game used to crash (on loading screen right before the title-screen.
Vulkan+MT RSX - Goes ingame just fine except graphics are wrong due to no WCB.

So this makes me think, the deadlocks people are experiencing with MT RSX e.g https://github.com/RPCS3/rpcs3/issues/6351 are only apparent when using WCB. Maybe it's helpful to find the cause?

I tried https://github.com/RPCS3/rpcs3/pull/6377 but i get the same issue. Either way I'm going to close this and report my findings there since the original OP issue has been fixed.

**Comment by Asinin3** [comment]
Aand right after i close the issue i find a new texture cache fatal error with OpenGL shortly after booting.
```F {RSX [0x0021978]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.h:383)```
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3535305/RPCS3.zip)

**Comment by kd-11** [comment]
MTRSX deadlock happens if a page fault occurs from the offloader thread while the main rsx thread is waiting in a spinlock. WCB and GPU blit can trigger this condition and it is more prevalent when games are loading. I'll fix it correctly soon.

**Comment by kd-11** [comment]
Retest, GL crash has been fixed, MTRSX lockup has been fixed and any lingering region.is_locked() errors should be cleared by https://github.com/RPCS3/rpcs3/pull/6512

**Comment by Asinin3** [comment]
Yep seems fine, can get ingame in Vulkan and OpenGL fine now, Modnation Racers is probably playable now because of this so huge thanks!
