### ISSUE TITLE
Regression: Toy Story 3 - Flickering Graphics (#4973)

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#5526]
In Toy Story 3 a lot of 3d objects flicker between black and proper textures. Easily noticeable on the board. Just pause the game when it starts and exit back to the board to see it. 

Build that introduced this issue : rpcs3-v0.0.5-7216-7915dcb2 #4973

Screenshots :
![rpcs3_2019-01-08_17-15-05](https://user-images.githubusercontent.com/25664221/50829007-179a6900-1369-11e9-851f-84afc92792de.png)
![rpcs3_2019-01-08_17-17-37](https://user-images.githubusercontent.com/25664221/50829082-54666000-1369-11e9-8bdd-274aca4e06ef.png)

Log from latest master : [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2736573/RPCS3.log.gz)
Log from the last build which worked correctly : [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2736581/RPCS3.log.gz)

Specs
CPU:i5 6500 3.2Ghz
GPU:Nvidia GeForce 750 Ti
OS:Windows 7 Ultimate 64-bit SP1

**Comment by kd-11** [comment]
Some of the changes in that PR have been revised several times since then, making it a possibility that it got fixed again at some later point and then broke again. Its unfortunate that it took so long to find it as this complicates things quite a bit.

**Comment by incognitoh** [comment]
@kd-11  actually I reported the regression the day it happened in the #4973 thread and have been testing the game since. for what it's worth, it was never fixed on master and I've been testing your PRs ever since and it never was fixed from all my tests.

**Comment by kd-11** [comment]
The comments get lost in the sea of other comments, which is why I asked to add any remaining bugs to [this ticket](https://github.com/RPCS3/rpcs3/issues/5001). Working on another big task right now, but I should have some time to look at this immediately after.

**Comment by stachuATX7** [comment]
I am new to RPSC, downloaded 3 hours ago and...

Yup... I wanted to post same issue with Toy Story 3 Game. 

Gtx 1660
I5-9400F
Win 10 x64

btw. What is PR ?

**Comment by maximumxp** [comment]
Still happening in 0.6-8439-5bd17a44

Any news on this?

Thanks!

**Comment by l3rayden** [comment]
Same Problem here. i looked at a article that says it has something to do with kd11 which was introduced in one of the recent updates.

**Comment by stachuATX7** [comment]
![image](https://user-images.githubusercontent.com/50980362/68333347-a4709900-00d8-11ea-945b-61660bc707bf.png)

Still the same problem

**Comment by stachuATX7** [comment]
![image](https://user-images.githubusercontent.com/50980362/68333540-fdd8c800-00d8-11ea-81d1-f8b2bc38383d.png)

Still same in the newest version

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/7302 fixes this particular regression. However, this game was seemingly always flickery if you knew where to look.

**Comment by Krusher97** [comment]
![rpcs3_2020-02-21_18-49-02](https://user-images.githubusercontent.com/25664221/75037762-efbd8480-54da-11ea-81ce-8686dc7e1026.png)
![rpcs3_2020-02-21_18-49-24](https://user-images.githubusercontent.com/25664221/75037770-f51acf00-54da-11ea-8f9f-4a466fce565c.png)

The flickering is still happening for me @kd-11

**Comment by kd-11** [comment]
You must enable 'strict rendering mode'

**Comment by Gpinchon** [comment]
> You must enable 'strict rendering mode'

Nope, this does not fix flickering...

**Comment by Gpinchon** [comment]
The strict mode only works with OpenGL and gives very poor performance.
Also, strict mode with Vulkan still has flickering textures.

**Comment by kd-11** [comment]
Log?

**Comment by Gpinchon** [comment]
Sorry, there it is :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4914585/RPCS3.log.gz)
Also, I noted that it seems highly linked to the framerate. When setting vblank at 120Hz, the flickering is all over the place, but when setting it back to 60Hz, the texture flickering seems to happen whenever framerate changes (to 29 and then back to 30 for example)

**Comment by Gpinchon** [comment]
Here is a log with the latest version, and with a level which gives a lot more glitches, it must have to do with the scene's complexity, inducing more framerate variation :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4915177/RPCS3.log.gz)

**Comment by nolanhbk** [comment]
I'm having this issue as well. SRM with Vulkan isn't perfect but it's a lot better than without it. SRM with opengl fixes the flickering, but you lose a lot of performance and textures take a while to load in. After texture load, they don't seem to flicker at all though.

**Comment by Gpinchon** [comment]
> I'm having this issue as well. SRM with Vulkan isn't perfect but it's a lot better than without it. SRM with opengl fixes the flickering, but you lose a lot of performance and textures take a while to load in. After texture load, they don't seem to flicker at all though.

In fact, with Vulkan, anything that makes the framerate variate provokes flickering. That may be texture loading (hence the huge flickering when starting levels), or physics calculation, light effects... Anything realy. Also, I think that if your computer is fast enough, you won't notice the flickering because the framerate locks at 30.

**Comment by Gpinchon** [comment]
There was a HUGE regression since last version, now running with Vulkan gives this :
![ToyStoryFlicker](https://user-images.githubusercontent.com/8039212/88285322-2ba97f80-ccef-11ea-9793-87e852330f51.PNG)

**Comment by illusion0001** [comment]
Open a new issue + rsx capture and renderdoc capture

**Comment by Gpinchon** [comment]
> Find what pr broke it, Open a new issue + rsx and renderdoc capture

Funny because doing a renderdoc capture was the first thing I did 😁
I am on it.

**Comment by Gpinchon** [comment]
After investigating, I discovered that the issue was caused by setting Texture Filtering to High Performance in Nvidia control panel (that's unexpected though).

**Comment by stachuATX7** [comment]
version after version flickering seems to be worsening and on OpenGL game has very poor performance. I wouldn't put this game to Playable section since its not playable anymore.

**Comment by B00MST3R** [comment]
Toy Story 3 with the videos work fine, but in game it becomes very flickering in game with shaders possibly if that is what you call it, basically, the characters are fine, but all around the scenery becomes black and flickering around.

**Comment by Jonathan44062** [comment]
Enabling "Strict Rendering Mode" in GPU Tab of the settings fix the issue

**Comment by Gpinchon** [comment]
> Enabling "Strict Rendering Mode" in GPU Tab of the settings fix the issue

Not anymore, well, not with an RTX 3060 Ti anyway...

**Comment by vookhan** [comment]
SRM on
![image](https://user-images.githubusercontent.com/91951559/157148465-8a77a679-2f07-4f03-898d-afa8b2b41f4a.png)

**Comment by Jonathan44062** [comment]
Open a new ticket and report the problem
