### ISSUE TITLE
DS4 not being released after exiting RPCS3

### ISSUE THREAD

**Issue by IceLancerSR** [RPCS3/rpcs3#5692]
Start rpcs3 with Dualshock 4 V2 windows drivers. 
Click Pads.once. 
Close rpcs3

rpcs3 is still linked to gamepad, cant use it unless disconnected/reconnected (wifi)

win10 x64 all updates

v0.0.6-7809 Alpha [2019-02-23]

**Comment by AniLeo** [comment]
Did you check if rpcs3.exe is still open on taskmgr?

**Comment by IceLancerSR** [comment]
> 
> 
> Did you check if rpcs3.exe is still open on taskmgr?

I did. Its not in active memory

**Comment by IceLancerSR** [comment]
I just tested gamepad while steam is being ON, and steam takes over gamepad and i was insanely surprised to find out that rpcs3 still recognizes gamepad and is able to use it? i have no idea how u managed to do that, no other app atm that i know can, ur solution just might be solution ds4 users have been waiting for. And after closing rcps3 , steam can still use gamepad. I must congratulate you there

However, when gamepad is alone without anything taking it, starting rcps3 wont release.

**Comment by bevanweiss** [comment]
@IceLancerSR are you able to confirm that this is still a problem?
There were some code changes that I can see related to the DS4 handling that might have fixed this issue (it tidied up the release of the usb_hid interaction).

**Comment by IceLancerSR** [comment]
> 
> 
> @IceLancerSR are you able to confirm that this is still a problem?
> There were some code changes that I can see related to the DS4 handling that might have fixed this issue (it tidied up the release of the usb_hid interaction).

Yes its still the same. Gamepad keeps dark blue color in its lightbar. And i can't use it anymore. Untill turned off from bluetooth and reconected

**Comment by bevanweiss** [comment]
Ohh... you didn't mention bluetooth before (hence why I mentioned the usb_hid).
Are you using the latest DS4Windows release from here? https://github.com/Ryochan7/DS4Windows/releases

**Comment by bevanweiss** [comment]
And is it a genuine DualShock 4, or a clone?

**Comment by IceLancerSR** [comment]
> 
> 
> Ohh... you didn't mention bluetooth before (hence why I mentioned the usb_hid).
> Are you using the latest DS4Windows release from here? https://github.com/Ryochan7/DS4Windows/releases

There is no difference on USB either. It keeps being connected ,making it worse because i have to unplug gamepad

Its original V2 gamepad.

**Comment by IceLancerSR** [comment]
Connect to USB , then rcps3 , gamepad connects. ligthbar gets dark blue color. Meaning it connected to app and it took over. But nature of usb is that it can keep working with anything because nothing can exlusivly take over phisically connected gamepad
But problem still persist because even after turning of rpcs3 , lightbar stays same color. So original problem is still there. It just doesnt affect usb

**Comment by bevanweiss** [comment]
The light bar colour itself might be a bit misleading.  Since RPCS3.exe knows about the light bar, we write to the colour of it.
If disconnected, the device will keep the last colour that it had.  Other applications don't necessarily know about the light bar, and so don't write colours to it.
It does look like we're still fixed at a very old release of libhid... but I very much doubt that it would change this behaviour, and it's likely to be a painful change to upgrade this dependency (although I'll have a quick look into it).

**Comment by IceLancerSR** [comment]
> 
> 
> The light bar colour itself might be a bit misleading. Since RPCS3.exe knows about the light bar, we write to the colour of it.
> If disconnected, the device will keep the last colour that it had. Other applications don't necessarily know about the light bar, and so don't write colours to it.
> It does look like we're still fixed at a very old release of libhid... but I very much doubt that it would change this behaviour, and it's likely to be a painful change to upgrade this dependency (although I'll have a quick look into it).

Windows has its own device color, light blue , shouldnt it try to write that color back if it gained control ? I know that it does do that when ds4win is turned off
Main problem still persist tho. bluetooth use . my battery is very good so i dont bother to charge controler for very long time. But because of this issue i am reluctatnt to play rpcs3 when i decide to do gaming

**Comment by bevanweiss** [comment]
I'm not sure on the light blue that you're talking about.
On my Windows (without DS4Windows), if I connect via Bluetooth without RPCS3 or anything else running then I have no lights.
Ditto with the USB.  If I just connect it to Windows, then I get no lights.
Lights only start when I connect it to RPCS3 (either via Bluetooth / USB), in which case it gets the assigned controller colour (which defaults to blue).  I believe blue is also the default controller colour for DS4Windows unfortunately (I think it was the same for the PS3 from memory as well... likely the reason the others chose this).

I'll see about tidying up some of the light state 'stuff' for RPCS3, which should hopefully provide some leads on where any other problems might be.

**Comment by IceLancerSR** [comment]
> On my Windows (without DS4Windows), if I connect via Bluetooth without RPCS3 or anything else running then I have no lights.

?
my gamepad gets light blue light when connected to bluetooth on windows drivers
Maybe its different if you have V1 gamepad?
https://i.imgur.com/8CbqFtJ.jpg

**Comment by bevanweiss** [comment]
It would be great if this could be retested under the PR I just submitted.  It would be more luck that it solves it, and given it's just versioning up libusb, it may well introduce more problems than it solves.. but it's worth a try I think.
#8987

**Comment by IceLancerSR** [comment]
> 
> 
> It would be great if this could be retested under the PR I just submitted. It would be more luck that it solves it, and given it's just versioning up libusb, it may well introduce more problems than it solves.. but it's worth a try I think.
> #8987

PR? as public release or do i need to compile? I have no means to compile right now

**Comment by bevanweiss** [comment]
PR as in Pull Request.

It's not in mainline yet, it needs a little more varied testing.

Windows Build
https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQwMjcvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip

Linux Build
https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQwMjcvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitMaW51eA2/content?format=zip

**Comment by IceLancerSR** [comment]
> 
> 
> PR as in Pull Request.
> 
> It's not in mainline yet, it needs a little more varied testing.
> 
> Windows Build
> https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQwMjcvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip
> 
> Linux Build
> https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQwMjcvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitMaW51eA2/content?format=zip

tested. its the same. can't use gamepad anymore after rpcs3 exits

**Comment by Megamouse** [comment]
Please retest with the latest build

**Comment by IceLancerSR** [comment]
> 
> 
> Please retest with the latest build

Only new difference is that connected gamepad no longer becames dark blue (lightbar) instead it stays light blue , default connected color. 
Locked to rpcs3 bug still persist.

**Comment by Megamouse** [comment]
I honestly don't see the point of this.
