### ISSUE TITLE
SPU LLVM causes wrong pixel colors on several games

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5886]
Several games have an issue where numerous pixels get the wrong color rendered. Example: In Captain America, there's red/green dots over image only when using SPU LLVM. Fine with ASMJIT. I tried numerous SPU/GFX settings but nothing fixes it unless I switch to ASMJIT. 

**Games Impacted:**
- [ ] Captain America
- [ ] God of War 3 
- [ ] House of the Dead
- [ ] Motorstorm Apocalypse
- [ ] LittleBigPlanet 3
- [ ] Sly Cooper Thieves in Time 

**Captain America screenshots/log :**
LLVM:
![2019-04-25 19_52_33-Window](https://user-images.githubusercontent.com/20983844/56780601-cb96f700-6794-11e9-8320-73314c7b4dd5.png)

ASMJIT:
![2019-04-25 19_46_43-Window](https://user-images.githubusercontent.com/20983844/56780604-d3ef3200-6794-11e9-8389-1496e83d54d4.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3119553/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Asinin3** [comment]
Sly Cooper Thieves in Time suffers from the same issue except the dots are mostly white, and they only appear around foliage when using SPU LLVM.

**Comment by EnekoT2001** [comment]
Something similar happens with god of war III using SPU LLVM, it isn't as bad, and in gameplay is barely noticable with the latest build.
![Captura de pantalla (621)](https://user-images.githubusercontent.com/42989949/56848780-1461c380-68ed-11e9-82a5-696eb8cb4b05.png)

![Captura de pantalla (627)](https://user-images.githubusercontent.com/42989949/56848784-25aad000-68ed-11e9-8b73-8d1c1187984f.png)



This is the result with ASMJIT:
![Captura de pantalla (635)](https://user-images.githubusercontent.com/42989949/56848994-ff862f80-68ee-11e9-8d1d-89842c0b673a.png)


![Captura de pantalla (638)](https://user-images.githubusercontent.com/42989949/56848998-090f9780-68ef-11e9-8937-1acd5fd9b8d7.png)

(Btw, with LLVM i get twice the performance compared to ASMJIT)

**Comment by legend800** [comment]
Yep, that looks like the exact same issue. Added to list.

**Comment by JohnHolmesII** [comment]
Is there a difference between approximate and accurate xfloat?

**Comment by EnekoT2001** [comment]
> Is there a difference between approximate and accurate xfloat?

I tried now with the latest version (8056) and no difference with approx. and accurate :c (i tried just GoW 3)

**Comment by slashiee** [comment]
LittleBigPlanet 3 also has this issue
ASMJIT:
![2019-05-05_12-19-35](https://user-images.githubusercontent.com/15317421/57199109-1d2b4880-6f30-11e9-8b38-14f5da47f2f9.png)

SPU LLVM:
![2019-05-05_12-14-59](https://user-images.githubusercontent.com/15317421/57199107-16043a80-6f30-11e9-96cd-40765b7c792c.png)

**Comment by legend800** [comment]
Updated list.

**Comment by legend800** [comment]
Adding House of the Dead Overkill to the list.

![2019-08-21 23_09_44-Window](https://user-images.githubusercontent.com/20983844/63490726-35d15700-c46a-11e9-8962-c6de32d17660.png)

**Comment by legend800** [comment]
Motorstorm Apocalypse added. I think that's everything in my collection noted here now. 

![2019-08-22 20_28_05-Window](https://user-images.githubusercontent.com/20983844/63564878-aab09980-c51b-11e9-9116-148997632a75.png)

**Comment by elad335** [comment]
Should be fixed with #6864 on non-xfloat path.

**Comment by legend800** [comment]
@elad335 Sorry, no change with either of the SPU PRs referenced (https://github.com/RPCS3/rpcs3/pull/6864 & https://github.com/RPCS3/rpcs3/pull/6872), with or without Xfloat. Let me know if you need any more info for troubleshooting. 

![6872](https://user-images.githubusercontent.com/20983844/67585517-8aac7a80-f704-11e9-8b7a-a557fc659923.png)

![2019-10-25 08_49_31-FPS_ 18 91 _ Vulkan _ 0 0 7-ec7cced7-snr_mailbox _ Captain America™_ Super Soldi](https://user-images.githubusercontent.com/20983844/67585520-8d0ed480-f704-11e9-87af-46207d00f23e.png)

**Comment by elad335** [comment]
Ok, spu interpreter fast with xfloat works?

**Comment by legend800** [comment]
Same with SPU interpreter fast (w/ or w/o xfloat) on that PR:
![2019-10-25 09_19_31-SPU LLVM causes wrong pixel colors on several games · Issue #5886 · RPCS3_rpcs3](https://user-images.githubusercontent.com/20983844/67587364-95690e80-f708-11e9-8c5e-b22bcdd156ad.png)

Looks like it's only fixed with ASMJit.

**Comment by elad335** [comment]
Holy shit it's even an issue on precise interpreter.
![image](https://user-images.githubusercontent.com/18193363/67598308-e3682b80-f775-11e9-903f-d617c74da006.png)

**Comment by legend800** [comment]
@Xcedf Maybe you can post the custom build with the old tex cache you referenced here https://github.com/RPCS3/rpcs3/pull/6940#issuecomment-549268747 that didn't have this pixel issue for further root causing?

**Comment by Xcedf** [comment]
Still have some work to do on this build, will post it with GoW3 video tomorrow.

**Comment by Yahfz** [comment]
fixes gow with #6998

**Comment by Asinin3** [comment]
Fixes Sly Cooper Thieves in Time!
![image](https://user-images.githubusercontent.com/15137035/68992491-21132c80-08bc-11ea-98c1-b1f8b77298ba.png)

**Comment by Asinin3** [comment]
Just rechecked, the performance difference and it wasn't due to fluctuating fps or anything. There is a huge 9-13fps loss from this PR when using SPU LLVM atleast compared to master.

**Comment by Asinin3** [comment]
MotorStorm Apocalypse is fixed too (just take my word for it, it's hard to see in static screenshots) I don't have LBP2 or House of the Dead Overkill to test though.
