### ISSUE TITLE
The Simpsons the Game [BLES00142] - Broken Controller Input

### ISSUE THREAD

**Issue by web1018** [RPCS3/rpcs3#6093]
The controller inputs are not fully accepted.  it is not possible to navigate by analog stick or control pad (menus) and within gameplay is the same result. Only Input of the X or Start buttons has been accepted and trying to remove the controller and plugging it back in does not change anything. Elad mentioned before that it might have something to do with **pad thread rewrite and timing hacks/fixes**. This is the only issue I know so far thats preventing the game to be fully playable.

Tested Build :
rpcs3-v0.0.6-8254

Hardware Specs :
Nvidia GeForce GTX 960M
Intel Core i7 6700HQ
16GB of Ram
Windows 10
Xbox 360 Controller
![Capture1](https://user-images.githubusercontent.com/51851411/59550114-0d425380-8f35-11e9-9a6c-9893c3662ec1.PNG)

## Update
- Checking the Latest Master Version v0.0.10-10321-72bef8dd Alpha, The controller issue is fixed somehow. I can navigate through the menu options and in game options without any issues now. I am not sure which PR fixed this issue, but the controller Input problem no longer occurs. I have tested it using Xbox 360 controller. Unless the issue still stands, I am closing this Issue.

**Comment by Megamouse** [comment]
It is also worth mentioning here that you need to disconnect and reconnect the controller before you can press start at the main menu AFTER having pressed start in the splash screen.

(you can currently also do this by simply changing your pad configs)

**Comment by web1018** [comment]
> It is also worth mentioning here that you need to disconnect and reconnect the controller before you can press start at the main menu AFTER having pressed start in the splash screen.
> 
> (you can currently also do this by simply changing your pad configs)

I have tried this several times and unfortunately, there was no luck in getting it to work

**Comment by web1018** [comment]
Checking the Latest Master Version v0.0.10-10321-72bef8dd Alpha, The controller issue is fixed somehow. I can navigate through the menu options and in game options without any issues now. I am not sure which PR fixed this issue, but the controller Input problem no longer occurs. I have tested it using Xbox 360 controller. Unless the issue still stands, I am closing this Issue.

**Comment by Megamouse** [comment]
would you mind finding the build that fixed it?
I personally wanna know :)

**Comment by web1018** [comment]
Sure. i'll look into it and try to find which PR have fixed this, it could be useful for fixing other games controller issues.

**Comment by web1018** [comment]
I found the PR that fixed the controller issue. It appears to be Elads merged PR. Starting from v0.0.9-10079(#7874) to newer versions the controller works. From v0.0.9-10078(#7893) and older the controller input does not work. Unless there is other merged PRs in between the ones I mentioned, please let me know and I will check again.

**Comment by Megamouse** [comment]
This is still not working properly on my end. I'll reopen this issue

**Comment by web1018** [comment]
could it be perhaps you are using specific type of controller or settings? Maybe if you cleared all the cache and restarting it. It works without problem on my end. Perhaps we can get more people to test it.

**Comment by benderscruffy** [comment]
still an issue
![Capture](https://user-images.githubusercontent.com/2696404/135407741-79abb80a-c55c-4838-9808-f0f1be79d17a.PNG)

**Comment by eduazy** [comment]
> still an issue ![Capture](https://user-images.githubusercontent.com/2696404/135407741-79abb80a-c55c-4838-9808-f0f1be79d17a.PNG)

A bit late so you might already have found the solution, but for anyone that runs into this issue:

After it asks you to reconnect, go to RPCS3 window > Pads > Player 1 > Handlers > None > Save
Then go back and inside Handlers, choose whatever option you had previously (in my case XInput works)

This resets the controller and lets you play. You need to do this every time you launch the game.
