### ISSUE TITLE
[Regression] Silent Hill Downpour stopped loading savegames

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#6558]
From RPCS3 build ~8700 game stopped loading existing savegames.
Game starts as usual, savegame list displays correctly in the menu, but when I start to load one of the save, game shows loading screen infinitely. I have build 8637 and everything is fine on the same savegames (corruption files is excluded). Btw, newly started game load correctly.

**Comment by marsselluo** [comment]
I have the same issue.

**Comment by delorean007** [comment]
Megamouse broke several dozens of games with his destructive PR #6416 and this is just another one. That entire PR should have been reverted.  GoodLuck

**Comment by dio-gh** [comment]
Imagine putting a shitton of effort into REing stuff, PRing 6K lines, only to then be told off like this..

**Comment by AniLeo** [comment]
@delorean007 shut up if you don't have anything useful to add or you'll be blocked from the tracker. Most regressions were already fixed and new ones will be looked into and fixed as well. He rewrote a lot of code that was just stubbed to start proper implementations, this is completely normal after removal of hacky code, if you're just going to keep bashing at contributors because your games stopped working for a few days then you have no reason to be here at all.

**Comment by digitaldude555** [comment]
Well new saves have worked since september and will probably work in the future too, can close this issue.

**Comment by rodiape** [comment]
Same issue old saves doesnt laod anymore in recent builds

**Comment by maricelase** [comment]
same issue with last build in February 5, 2023

**Comment by ozzfreak** [comment]
Still happening as of 7/19/2024 with RPCS3 Version: 0.0.32-16689-a2534263 Alpha | master
