### ISSUE TITLE
Certain games crash on load [Possibly Linux Only]

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6589]
On Linux systems, some games such as  Dark Souls [BLUS30782] and TDU 2 [BLUS30527] crash RPCS3 entirely after the loading screen with exceptions thrown such as:

Dark Souls: 
![65264228-b59c2100-dafd-11e9-87dc-7feccc7735ac](https://user-images.githubusercontent.com/12475371/65266733-28f46180-db03-11e9-99e5-4ada04a4cf7e.png)

TDU 2:
![pic](https://user-images.githubusercontent.com/12475371/65263175-8b496400-dafb-11e9-89ad-bbf3e6d31fb3.png)

Note: TDU 2 seems to load on Windows systems, at least from [this](https://www.youtube.com/watch?v=JUWHZWM_A0I) recent video.

Tested against 0.0.7-8739.  Test system is Linux Mint 19.2 with kernel 5.0, Nvidia GTX 1070M and driver 435.21.

Logfiles: 

Dark Souls:[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3632497/RPCS3.log.gz)
TDU 2: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3632500/RPCS3.log.gz)

**Comment by kd-11** [comment]
Did you try with interpreters? I have seen similar random crashes in the past when using SPU LLVM.

**Comment by Shoegzer** [comment]
Thanks, I just tried but the game seems to freeze with a black screen at the same point that it normally crashes with recompiiler.  Also, the video above shows the RPCS3 settings and they are using LLVM recompilers for PPU and SPU.  

One other note, this isn't a "random" crash as the behavior is consistent - it crashes at exactly the same point after attempting to start the game at least five times.

**Comment by elad335** [comment]
Maybe just include this in one issue instead of opening possibly many different issues?

**Comment by Shoegzer** [comment]
@elad335 done, I was trying to keep them separated since they are somewhat different in some respects (haven't seen Dark Souls working okay in Windows for example) but you're right that it's probably better to track as one issue.

**Comment by toccata10** [comment]
I'm seeing something similar (I think) on Ultra Street Fighter 4 [BLUS31218]. Same on TekkenTagTournament 2. The regression seems quite recent: on rpcs3-v0.0.7-8642-08c12f4c_linux64, it's the last good one. On rpcs3-v0.0.7-8643-8de12391_linux64, it crashes. Looks like the culprit is #6393
The backtrace for Usf4:
```
#0  0x00000000009395fd in void std::__introsort_loop<__gnu_cxx::__normal_iterator<fs::dir_entry*, std::vector<fs::dir_entry, std::allocator<fs::dir_entry> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<savedata_op(ppu_thread&, unsigned int, unsigned int, vm::_ptr_base<char const, unsigned int>, unsigned int, vm::_ptr_base<CellSaveDataSetList, unsigned int>, vm::_ptr_base<CellSaveDataSetBuf, unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataListGet, unsigned int>, vm::_ptr_base<CellSaveDataListSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataListGet, unsigned int>, vm::_ptr_base<CellSaveDataFixedSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataStatGet, unsigned int>, vm::_ptr_base<CellSaveDataStatSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataFileGet, unsigned int>, vm::_ptr_base<CellSaveDataFileSet, unsigned int>), unsigned int>, unsigned int, unsigned int, vm::_ptr_base<void, unsigned int>, unsigned int, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataDoneGet, unsigned int>), unsigned int>)::$_32> >(__gnu_cxx::__normal_iterator<fs::dir_entry*, std::vector<fs::dir_entry, std::allocator<fs::dir_entry> > >, __gnu_cxx::__normal_iterator<fs::dir_entry*, std::vector<fs::dir_entry, std::allocator<fs::dir_entry> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<savedata_op(ppu_thread&, unsigned int, unsigned int, vm::_ptr_base<char const, unsigned int>, unsigned int, vm::_ptr_base<CellSaveDataSetList, unsigned int>, vm::_ptr_base<CellSaveDataSetBuf, unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataListGet, unsigned int>, vm::_ptr_base<CellSaveDataListSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataListGet, unsigned int>, vm::_ptr_base<CellSaveDataFixedSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataStatGet, unsigned int>, vm::_ptr_base<CellSaveDataStatSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataFileGet, unsigned int>, vm::_ptr_base<CellSaveDataFileSet, unsigned int>), unsigned int>, unsigned int, unsigned int, vm::_ptr_base<void, unsigned int>, unsigned int, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataDoneGet, unsigned int>), unsigned int>)::$_32>) ()
#1  0x000000000092ca57 in savedata_op(ppu_thread&, unsigned int, unsigned int, vm::_ptr_base<char const, unsigned int>, unsigned int, vm::_ptr_base<CellSaveDataSetList, unsigned int>, vm::_ptr_base<CellSaveDataSetBuf, unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataListGet, unsigned int>, vm::_ptr_base<CellSaveDataListSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataListGet, unsigned int>, vm::_ptr_base<CellSaveDataFixedSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataStatGet, unsigned int>, vm::_ptr_base<CellSaveDataStatSet, unsigned int>), unsigned int>, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataFileGet, unsigned int>, vm::_ptr_base<CellSaveDataFileSet, unsigned int>), unsigned int>, unsigned int, unsigned int, vm::_ptr_base<void, unsigned int>, unsigned int, vm::_ptr_base<void (vm::_ptr_base<CellSaveDataCBResult, unsigned int>, vm::_ptr_base<CellSaveDataDoneGet, unsigned int>), unsigned int>) ()
#2  0x000000000093c303 in cellSysutil_SaveData_init()::$_24::__invoke(ppu_thread&) ()
#3  0x000000000075ed4f in ppu_thread::exec_task() ()
#4  0x000000000075e758 in ppu_thread::fast_call(unsigned int, unsigned int) ()
#5  0x000000000075dca8 in ppu_thread::cpu_task() ()
#6  0x00000000009cd61b in cpu_thread::operator()() ()
#7  0x000000000075b63e in named_thread<ppu_thread>::entry_point(void*) ()
#8  0x00007ffff6dd357f in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff4ba70e3 in clone () from /usr/lib/libc.so.6

```

**Comment by RipleyTom** [comment]
Sadly I introduced a bug that may lead to corrupted saves if you used #6393 build.
It was fixed shortly after.

Does the games crash if you use clean saves?

**Comment by Shoegzer** [comment]
@RipleyTom Hmm.. well I thought you were on to something because I deleted my Dark Souls game save (which I believe WAS changed per #6393) and it went further, letting me create a character and enter the game.  However, when the character died at the beginning, RPCS3 crashed.  From this point on now loading that game results in a crash.

I couldn't test TDU 2 because there was no game save for it at all.

**Comment by RipleyTom** [comment]
I tested Ultra SFIV and I didn't have any issues on starting the game after a save.

**Comment by RipleyTom** [comment]
And I just tested Dark Souls 1, New Game, saved at first bonfire, reloaded and everything was fine.
So it's unrelated to #6393 if you still have a problem.

**Comment by Shoegzer** [comment]
Okay thanks.  I did exactly as you did, though deleting not just the game save but also the trophy folder, and all caches.  The first time I restarted after saving at the bonfire, RPCS3 immediately crashed.  I tried restarting it though, and it seems to work fine now for all successive loads.  So I'd say we're in the same place on that one.

TDU 2 is still an issue though - not sure what's wrong there but it's not save game related as I had mentioned.  So I'll keep this open.

**Comment by Shoegzer** [comment]
@toccata10 can you please confirm saving is fixed with Ultra SFIV and TTT 2?  I'd like to close this one, as TDU 2 is now fixed (at least as of 0.0.7-8801) and @RipleyTom reports no issues with SFIV.  Thanks.

**Comment by toccata10** [comment]
Deleting trophies, saves and caches make the games playable again. You can close.

**Comment by Shoegzer** [comment]
Great, thanks for letting me know (and thanks @RipleyTom for the nice fix).  Closed.
