### ISSUE TITLE
[BLUS31159] NCAA Football 14 Random Graphical Glitches

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#6981]
RPCS3 v0.0.7-9112-7519e363
i9 9900K
RTX 2080
Windows 10

Have been playing this game for a while and haven't seen this before, so I am unsure if this is a regression or a one-off graphical glitch, but as I'm sure you will see in the RSX captures, some weird artifacts started appearing midway through a game. Let me know if there is any more information you need.

[RSX Capture Files](http://www.mediafire.com/file/3kfxklyay1ha6o9/RSX_Captures.rar/file)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3829072/RPCS3.log.gz)

**Comment by connorwalks** [comment]
Here is another example of the issue happening on RPCS3 v0.0.7-9128-8e39c778
An example of what the issue looks like:  ![NCAA 14 RSX issues](https://user-images.githubusercontent.com/48158481/68901871-d56a5280-0704-11ea-96cc-2821b1d4c091.png)

The issue is only resolved with a reboot of the game and is not visible in between games while in the menu system.

Log from the run: [RPCS3_1.log.gz](https://github.com/RPCS3/rpcs3/files/3848954/RPCS3_1.log.gz)

[RSX Capture from the run]https://www.mediafire.com/file/gg6t6280h1pf8p1/BLUS31159_20191113220203_capture.rrc/filel)

I also countered another possibly related issue on the same build on a separate run. In this instance, audio and gameplay continued on as normal (I could verify through audio cues that my controller inputs were working) but the screen was hung up, bouncing back and forth between two frames.

Log from that run: [RPCS3_2.log.gz](https://github.com/RPCS3/rpcs3/files/3848974/RPCS3_2.log.gz)

[RSX Capture from that run](https://www.mediafire.com/file/28e8fbqk9ucm3dh/BLUS31159_20191114005753_capture.rrc/file)


Again let me know if any further information is needed to help fix this

**Comment by connorwalks** [comment]
Just adding that I also experienced this particular issue in Madden NFL 25 [BLUS31178]. It's really "Madden 14", which came out in late 2013, so the same time as NCAA 14.

The emulator bugged out and crashed when I tried to take an RSX capture but I was able to capture video, screenshots and a log:

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4194525/RPCS3.log)

[Video of issue](https://www.youtube.com/watch?v=ojKN3Ao7y4E)

Here are some screenshots since video is probably compressed to shit:

![screenshot-2020_02_12_14_03_42](https://user-images.githubusercontent.com/48158481/74369036-b1211f00-4da2-11ea-8fa9-e06a95587161.png)
![screenshot-2020_02_12_14_03_26](https://user-images.githubusercontent.com/48158481/74369039-b2eae280-4da2-11ea-8f39-14fbe82a282a.png)

**Comment by AniLeo** [comment]
Needs retesting with master

**If** the issue still happens, then try with Accurate XFloat enabled

**Comment by Asinin3** [comment]
Closing as no update + haven't seen anyone mention this issue lately.
