### ISSUE TITLE
Kingdom Hearts II Final Mix Roxas Slowdown

### ISSUE THREAD

**Issue by Jay2008p** [RPCS3/rpcs3#7338]
It seems somewhere in between the build 0.0.5-7091 and now 0.0.8-9454 Roxas has begun to slowdown extremely on anything past that. I'm testing this on 0.0.8-9454. 0.0.6-8272 has the slowdown present but it's not as bad, it makes combat sluggish. After some trial and error 0.0.7-9188 seems to be the worst build with flickering textures and the Roxas slowdown anything before that for me crashes after the cinematic and so does anything after. Log below is from the 0.0.7 build.

System specs are:
 i5-6400
GTX 970
8gb ram
Windows 10
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4126936/RPCS3.log.gz)

**Comment by Asinin3** [comment]
What do you mean by 

> in between the commit 4876 and now

What is the build number? But really, before posting an issue you should go through https://rpcs3.net/compatibility?b and try builds in-between the date it regressed until you find it. Don't test every build, just try and quickly narrow it down first. Developers can't be expected to narrow down regressions like this for you when it may not appear on their system, and it's the responsibility of the person who reports the issue to provide a detailed break-down.

You're also missing a log file.

**Comment by Jay2008p** [comment]
Added log and changed the build numbers I used the number on the left side previously instead of saying the builds directly.

**Comment by Asinin3** [comment]
Is the bug the same as this old issue? https://github.com/RPCS3/rpcs3/issues/4274#issuecomment-449844136 The game used to run slow whenever roxas was in his attack stance/animation. But it was fixed.

**Comment by darkash** [comment]
last known good build
0.0.5-7772
when in stance or atking
![image](https://user-images.githubusercontent.com/2842880/73386673-d4a78c80-4301-11ea-9609-db6c81b60da2.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4129997/RPCS3.log.gz)

slowdown on 0.0.6-7773
when in stance or atking
![image](https://user-images.githubusercontent.com/2842880/73386922-4384e580-4302-11ea-9c93-f5abcc1ea623.png)
when idle
![image](https://user-images.githubusercontent.com/2842880/73386972-5b5c6980-4302-11ea-87f3-1564d58aa910.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4130029/RPCS3.log.gz)

**Comment by darkash** [comment]
on 9xxx build, the dips is even more grave that my fps drops to single digit when using 300% scaling, probably thanks to the anti-alias that it's more noticeable.

**Comment by Jay2008p** [comment]
Yes it's the same as the old issue but like darkash mentioned it is significantly worse when attacking or in the attack stance.

**Comment by Asinin3** [comment]
> slowdown on 0.0.6-7773 (#5587)
So that's the right pr and build number, but.. how the hell does that pull request to change where game configs are located break this 🤔 

> Yes it's the same as the old issue but like darkash mentioned it is significantly worse when attacking or in the attack stance.
But that's quite literally what the old issue was.

**Comment by darkash** [comment]
> > slowdown on 0.0.6-7773 (#5587)
> 
> So that's the right pr and build number, but.. how the hell does that pull request to change where game configs are located break this 🤔
> 
> > Yes it's the same as the old issue but like darkash mentioned it is significantly worse when attacking or in the attack stance.
> 
> But that's quite literally what the old issue was.

not sure how it is related either, from the commit diff, it only adds 1 parameter to the function and the 1 more if branching
pretty sure it's for loading config before loading the game too

is capture needed for this as well?

**Comment by Puremin0rez** [comment]
I'm experiencing the same issue. Whenever attacking with Roxas, the game will slow down to a very low frame rate and immediately pick back up again afterwards. Game runs at full speed in every other situation.

Willing to help however I can - I am new to RPCS3.

Windows 10, i7-4790K, GTX 1080 TI

**Comment by D-TurboKiller** [comment]
Can confirm, this issue persists as of the current build (0.0.10-10451). However, it's _not_ exclusively when attacking; it also happens if Roxas blinks his eyes, for example. Possibly related to facial animations? Didn't really notice it during cutscenes if that's the case, could just be during gameplay. And I just recently finished KH1 FM from the 1.5 ReMix release without any major issues. 

Also, a moderator [previously mentioned](https://forums.rpcs3.net/thread-165130-post-299790.html#pid299790) that 0.0.5-7096 didn't have such an issue, however I'm going to have to disagree there; besides the fact that this buggy build barely maintains 30 fps on Vulkan with default settings, the framerate cuts in literal half (14-15 fps) whenever attacking. On current builds, I have a stable 30 fps but it dips to 10 fps when attacking.

Specs:
OS: W10 64-bits
CPU: AMD A10-7850k (4 cores)
GPU: AMD RX470 (4 GB)
RAM: 8 GB

**Comment by mumia7575** [comment]
Having exactly the same drop of frames when roxas attack or blinks his eyes. Any workaround? Like an older build that can run the game without stuttering. Finished today KH1 from KH1.5 Remix and was flawless (except not loading the Chain of Memories, but thats another problem).

**Comment by jezuzo** [comment]
Having the same problem. Any solution yet?

**Comment by pyr0ball** [comment]
Been a few months since this issue was last updated. Just wanted to mention that the same issue is still present on the current build as of today (0.0.12-10820). I'm working on getting through the intro to see if the issue is persistent with both Sora and Roxas (as that wasn't specifically mentioned in this issue). At all other times this game runs smooth as butter.

I'm running on:
i7-9750H
RTX-2060 (Laptop)
32gb DDR4 3200

**Comment by Asinin3** [comment]
> Also, a moderator [previously mentioned](https://forums.rpcs3.net/thread-165130-post-299790.html#pid299790) that 0.0.5-7096 didn't have such an issue, however I'm going to have to disagree there; besides the fact that this buggy build barely maintains 30 fps on Vulkan with default settings, the framerate cuts in literal half (14-15 fps) whenever attacking. On current builds, I have a stable 30 fps but it dips to 10 fps when attacking.

I tested it back then and confirmed it though, see: https://github.com/RPCS3/rpcs3/pull/4876#issuecomment-406509121
I'm very confused on where this broke but someone needs to investigate it properly.

**Comment by D-TurboKiller** [comment]
> If anything maybe you forgot to clean shader cache when testing between builds which caused the problem to persist on the old build.
Nope, I actually read the instructions. I made doubly sure by deleting the *entire* cache so there wouldn't be any inconsistencies. The cache was rebuilt from scratch in both the old and new versions.
As I've mentioned previously, I think the issue isn't exclusively related to his attacking animation. Perhaps it's a combination between his facial animations (most notably the eyes blinking, causing massive frame drops) and his attack effects (the swooshing color effect, perhaps?). Personally from my experience, fixing such things usually benefits by ending up solving other, seemingly unrelated bugs in the process.

Degrading the bug reporter for his assumed incompetence instead of looking at the issue doesn't solve the problem, but... eh, I get it. Last I checked, the server's help channel was flooded with reports of things already fixed or circumvented, by people looking to play a pirated version on their crappy computer. That's to be expected for emulation in general.
The moderators were clearly uninterested on most of it, for good reason. I posted as much detail as possible there, but it quickly got buried. I'm like to figure things out myself unless it's absolutely uncircumventable, which leads me to either find an alternative myself, or just wait for it to get patched up.
That being said, if it was indeed fixed before, then it's unfortunate, but reoccurring bugs are an inevitable part of programming.
Not a personal attack or anything, just annoyed that there isn't a better way to go about the bug-fixing process... but it is what it is.

As for KH2FM, I ended up replaying it on an english-patched PS2 version of Final Mix, which apart from the low-res videos and some textures, was just as playable as the PS3 version of KH1FM. I don't feel like retrying yet again (far too busy IRL at any rate), so I'll leave it to someone else to test the PS3 version if it ever gets fixed.

**Comment by Asinin3** [comment]
> Degrading the bug reporter for his assumed incompetence instead of looking at the issue doesn't solve the problem, but... eh, I get it.

I get being upset, but how's that any different than you saying that I incorrectly presumed it was fixed because of a performance improvement? It went from 3FPS to 30, and was also fixed for another user. Something else is at play here.  I confirmed another user in our discord an hour ago that it's not caused by 0.0.6-7773 as well. However the user above could reproduce it happening on 7773, which makes no sense due to what the pull-request entails.

I really think something strange is going on, needs investigation.

**Comment by pyr0ball** [comment]
I've got a decent amount of debugging experience and I'm no stranger to coding, but I lack experience in graphics and emulation software specifically, however I'd be happy to put in some time trying to reproduce issues and provide bugreports if it would help @Asinin3 

If you let me know what kind of testing is needed to narrow this down, I can get started

**Comment by kd-11** [comment]
The most important thing here is to find a way to consistently trigger the issue for everyone. A big problem with performance issues (and other issues such as heap corruption, etc) is that unless you can observe it happening in front of you it becomes near impossible to fix, which is the scenario here. The underlying cause could be a combination of hardware configuration, emulator configuration, OS version, 3rd party software, etc.

**Comment by pyr0ball** [comment]
@kd-11 well you're in luck because my setup consistently reproduces the issue right now and I can provide a lot of that info

**Comment by Asinin3** [comment]
@pyr0ball The problem is if other users can reproduce it as well, not just you. For me back then I could reproduce it every run. For the other user in this thread he could reproduce it not working on 7773, but working on 7772. Basically it needs to be confirmed where the cause is across multiple people's systems.

**Comment by darkash** [comment]
> @pyr0ball The problem is if other users can reproduce it as well, not just you. For me back then I could reproduce it every run. For the other user in this thread he could reproduce it not working on 7773, but working on 7772. Basically it needs to be confirmed where the cause is across multiple people's systems.
> 
> Try using old builds: https://rpcs3.net/compatibility?b - go back months at a time, and narrow down where it broke. Maybe start at the middle of 2019 and use the old build with rpcs3 after clearing cache's (right-click the game and remove them). Then see if it's broken. If it's working then you need to use a newer build, if it is broken then you need to use an older one. Basically just narrow it down quickly by jumping through multiple months of builds at a time, should be able to nail it down faiirly easily since it's easy to reproduce, just make sure to jump like ~4 months at a time when you first start trying to narrow it down.

since you bring this up again, I decided to test it once again, you can ignore my previous report since it indeed was a mistake
perhaps thermal throttle kicks in since I spent like 4 or 5 hours testing random build at the time

**Comment by MojoJojoDojo** [comment]
Is this about the stutter issue that happens all the time ?
I also get it but I use a laptop .
It runs everything else on 1.5 and 2.5 well its only KH2 that gives me that issue.

**Comment by Skooz** [comment]
Did some testing, using Vulkan and the help of a 60fps tweak, and I've narrowed down a **_"culprit"_** build. I put emphasis on that because, even though I've found an obvious performance regression between these builds, this issue is still present and results in a slowdown on _both_ builds. It just becomes a lot more intense and noticeable between these _particular_ builds.

Build **0.0.7-8952** seems to be the last "working" build, with fps dropping to around 45 at the lowest while attacking. Since the game is typically locked to 30fps, I doubt most people will ever notice the issue is present.

Build **0.0.7-8956** the slowdown becomes much more intense, with fps dropping to around 20 while attacking. For those running at the standard 30fps, this issue becomes once again becomes obvious.

So while I seem to have tracked down a culprit build, it seems like this issue was never actually fixed, just made less noticeable.

I did not test the builds between **0.0.5-7096** and **0.0.6-7773**, despite there being an evident performance improvement, as I wanted to narrow down where the sudden regression had occurred. I could start going through those, if needed.

**Comment by FatheredPuma81** [comment]
> Build **0.0.7-8952** (rpcs3-v0.0.7-8952-c16319f9_win64) seems to be the last "working" build, with fps dropping to around 45 at the lowest while attacking. Since the game is typically locked to 30fps, I doubt most people will ever notice the issue is present.
Would just like to say thanks. Reverted to that build for until I finish with Roxas. Would also like to say the issue still persists in 10965. Drops to around 80 FPS FPS in 8952 vs 25 FPS in 10965. 
According to another post apparently the cause is his facial animations. When he blinks and when he opens his mouth while swinging.

**Comment by pyr0ball** [comment]
I tested Build **0.0.7-8952** with the 60fps patch (using CheatEngine) and the drop is still severe (60fps down to 18-20)

![image](https://user-images.githubusercontent.com/8482805/94856359-b93ad700-03e4-11eb-927a-6bcd78b4b7ac.png)
![image](https://user-images.githubusercontent.com/8482805/94856386-c35cd580-03e4-11eb-83d7-dbcb1fdc2531.png)

**Comment by FatheredPuma81** [comment]
> I tested Build **0.0.7-8952** with the 60fps patch (using CheatEngine) and the drop is still severe (60fps down to 18-20)

Don't use OpenGL. Just tested in Axel fight outside of Usual Spot and OpenGL gets 25 FPS while Vulkan gets 45FPS. Pretty sure in most other area's it stays above 60.

**Comment by Skooz** [comment]
After reviewing the commits & pull request related to build **0.0.7-8956**, it seems that enabling **"Force CPU blit emulation"** under the **Debug** tab will alleviate this issue, even on the most recent **0.0.12** build; I was not really dropping below 60fps while attacking, which is a tremendous performance improvement. However, it does cause various graphical bugs, and so when enabling **"Write Color Buffers"** under the **GPU** tab (as suggested by the CPU blit setting), performance does take a hit, and it drops back down to 40fps or so while attacking. You will still encounter some messed up graphics though, but enabling "**Read Color Buffers"** under the **Advanced** tab should solve them.

I suppose I should also note that _disabling_ all of these settings still results in worse performance than having them all on, so it definitely seems related to forcing CPU blit emulation. 

Oh, and if you see the sun\lens-flare appearing through buildings\geometry in Twilight Town, that is not because of these settings. It's an upscaling issue with the latest builds. It's unrelated, but I figured I should mention it here so people don't get the wrong idea and assume it's because of this "workaround".

**Comment by pyr0ball** [comment]
@FatheredPuma81 Right forgot about that bit. Confirmed on Vulkan the issue is a lot less pronounced:
![image](https://user-images.githubusercontent.com/8482805/94950817-1348a480-0498-11eb-81f6-c6310c021000.png)
![image](https://user-images.githubusercontent.com/8482805/94950841-1d6aa300-0498-11eb-93fc-3b2efa40219f.png)

The lowest I see it dipping is about 43fps with this build (without applying the changes suggested by Scooz)

@Skooz I did also try 0.0.12 (latest that downloaded yesterday) while enabling those three options I still get the same drop in performance if the read/write buffers, but about the same as 0.0.7-8956 if I ONLY enable "Force CPU blit emulation"

**Comment by LiLENZO1101** [comment]
first comment here, made this account so i can help with this issue.

i tested both 0.0.5-7772 and 0.0.6-7773, they both have this issue on openGL but not on vulkan. the confusion was caused since darkash assumed the default setting would be vulkan while it was openGL. i will test other versions and see what i can find.

also CPU blit Emulation worked for me (sorta). i was running KH on 60 FPS and with CPU blit i had it running at 30 fps, with the other fixes the performance went to 20 fps only. these readings where taken during combat stance, the game was running at 60 FPS in every other scenario, with or without the CPU blit and the fixes. i'll try to run CPU blit only (without the fixes) and run it without the patch, see if that's playable.

BTW, the issue still remains on build 0.0.13-11371.

tell me what else i should test.

my build is a dell Inspiron 7000 gaming laptop
intel I7-7700HQ
8GB ram
GTX 1050Ti 4GB Vram

**Comment by LiLENZO1101** [comment]
update

i tried both 0.0.7-8956 and the one that came before it (0.0.7-8952), and here is what i found

0.0.7-8952 did not have this issue in vulkan
0.0.7-8956 had this issue in vulkan

that, CPU blit test, say that its is a gpu blit issue. (or at least part of it is)

i also tested the newest build, 0.0.13-11371 with only the 30 FPS (60 FPS patch disabled) & CPU blit config (without the fixes) and it gave me playable frame rates. exactly as the 0.0.7-8952 did. they also shared the same FPS fluctuation during an attack animation, it was a steady 30 FPS on the combat stance though. The fluctuation was mostly between 25-30 FPS, and rarely dropped to 20 FPS.

**Comment by FatheredPuma81** [comment]
Would just like to drop in with a video of the issue and confirm that **CPU Blit Emulation _helps_ but doesn't fix the issue.**
Ryzen 5 3600, 16GB 3600MHz CL16, GTX 1080

https://youtu.be/9r40nS4_P8I

**Comment by LiLENZO1101** [comment]
> Would just like to drop in with a video of the issue and confirm that **CPU Blit Emulation _helps_ but doesn't fix the issue.**
> Update: Would just like to say I tested OpenGL, Interpreter (Precise), Interpreter (Fast), disabled Multithreaded RSX, and all "Additional Settings" and nothing made a difference.
> 
> Ryzen 5 3600, 16GB 3600MHz CL16, GTX 1080
> 
> https://youtu.be/9r40nS4_P8I

hope they see it

**Comment by Vandalizar** [comment]
But now is there something that works better than others?
I tried both 0.0.7-8952 and 8956 following @Skooz and @LiLENZO1101, but didn'd work at all, still having a huge drop of fps.
![normal](https://user-images.githubusercontent.com/76944857/103526879-d10d7580-4e81-11eb-96bc-c4e58b3af23b.JPG)
![combact](https://user-images.githubusercontent.com/76944857/103526905-d5d22980-4e81-11eb-9073-2a0bd5f27afb.JPG)

**Comment by Skooz** [comment]
I specifically said that using build 0.0.7-8952 or forcing CPU blit emulation ***ALLEVIATES*** the issue. Never said it fixes the issue! Obviously, if your base hardware\performance isn't good enough then you may still drop below 30fps. 

At this point, it is up to the RPCS3 devs\contributors to investigate further. I guess they haven't checked in on this thread, so someone will have to nudge them.

**Comment by Vandalizar** [comment]
Skooz i wasn't expecting to fix the issues with this way, I thought I would have had better performances. I think i'll just speed the roxas part to get to use Sora.

**Comment by moutorde** [comment]
Force CPU blit emulation seems to have 99% fixed the issue for me. At least to a point where the drops aren't noticeable anymore. As mentioned previously, I also had to enable Write Color Buffers to avoid some black screens.
You can see on the video that something is indeed happening when roxas blinks and when he attacks but it doesn't happen everytime and it is very light (sometimes noticeable when it drops to 56fps). It also seemed like the more I tested, the less it happened, probably just placebo effect.

My config : i5 8600k, RTX 2060 SUPER (driver 460.89), 16GB DDR4 3000MHZ C15, RPCS3 0.0.14-11709-78811b88 Alpha

https://toutu.be/Z5bcRgAQ7Gw

**Comment by Sirius902** [comment]
Can confirm this is still an issue in ad49c545.

**Comment by MojoJojoDojo** [comment]
Do you think that the soon to be released PC port will shed some light on this issue ? would be interesting to know.

**Comment by Jay2008p** [comment]
> Do you think that the soon to be released PC port will shed some light on this issue ? would be interesting to know.
> Unless its something PS3 specfic.

No not at all but since that's coming out i think it would be fair to delete this thread entirely.

**Comment by RainbowCookie32** [comment]
The issues of a game on the emulator don't go away because it gets released on PC.

**Comment by MojoJojoDojo** [comment]
> Do you think that the soon to be released PC port will shed some light on this issue ? would be interesting to know.
> Unless its something PS3 specfic.

lol looks like I was right and KH2FM is also the problematic game on the PC release... the framerate is all over the place there.
The game drops from 60 to 30 and vice versa on the PC release.

**Comment by Darkhost1999** [comment]
What information is still needed for this issue if any?

**Comment by Skooz** [comment]
> What information is still needed for this issue if any?

Nothing really. My previous posts have laid out the issue as clear as it can be laid out for someone without any experience working on the emulator. It's up to a dev to use this information to see if they can resolve the issue. Of course, it's still possible my findings are totally unhelpful, but there's really nothing else that I or anybody else lacking experience can do at this point. That, and the fact that the 'Force CPU Blit Emulation' setting alleviates the issue could be considered a fix in itself - we may not get any better than that.

That all said, with the franchise now being natively supported on PC, this issue's priority has dropped tenfold. You could try poking one of the devs on Discord or something to look into the issue if you're that desperate, but I'd recommend not bothering with the emulator to begin with if all you're trying to do is play Kingdom Hearts.

**Comment by Darkhost1999** [comment]
This issue is fixed on latest master I'm obtaining "proof"

**Comment by Darkhost1999** [comment]
Issue is barely even noticeable on latest master that I was entirely unaware of the issue even exisiting at all during my gameplay because I do not hawk eye the FPS counter. 
https://youtu.be/2mreBQdfTGM
Clip (below) is already uploaded and processing the HD version. Video (above) says another hour until uploaded.
https://youtu.be/mqz8p8PfkVc
Some time before on same PC if I did not enable Force CPU Blit the dip was below 12fps with noticeable consequence to speed and performance where it would make reversals and the struggle match a real struggle.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7686675/RPCS3.log.gz)

**Comment by kd-11** [comment]
Let's keep it open for another 48-72h just in case someone is still affected by this one. There have been some major performance optimizations in the past few weeks, it may have been improved by that.

**Comment by Megamouse** [comment]
I guess the time's up

**Comment by FatheredPuma81** [comment]
Oops I missed kd-11's post. The Roxas blinking lag seems to be pretty much fixed and only drops to 200FPS from 360 for me with and without blit enabled. The fighting animation lag persists though and drops to 45FPS without cpu blit and 100FPS with cpu blit. 
I "uncapped" the FPS to see if it's 100% gone or not. Should probably get someone with low end hardware that can play the game at like 100 FPS to see how it is.

Video: https://odysee.com/@FatheredPuma81/roxaslag

**Comment by Darkhost1999** [comment]
I see these values as above 30fps which is native to the game without patches. Patches aren't exactly tracked on the issue tracker.
In my video using a Ryzen 5 3600 which is at the recommended specs for RPCS3. There are still dips from 30 to 20-22 fps. Which without using the fps overlay would make playing the game look totally normal as it does on real PS3 hardware with no noticeable slowdown to games speed.
Technically what I'm saying is yes issue still exists. But it has improved well enough to be comparable to real hardware.

**Comment by darkash** [comment]
From my test just now it just drops to 22~25 fps when roxas is attacking while 30 fps while in stance.

I got i7-8550U laptop which is weak and the framedrop is still reasonable, so yea it's fixed :D

**Comment by FatheredPuma81** [comment]
@Darkhost1999 My point was that the issue is still there and effects the few players that want to play the PS3 version of KH2 instead of the PC version for some reason. If they believe it's fixed enough and want to close it that's up to them.

Also please don't use Recommended specs as a reason why a performance issue isn't an issue. If the performance hit is tied to specs (it doesn't seem to be from @darkash's post) and makes an otherwise playable game unplayable it should still be seen as an issue. Using it to say whether a game is playable, sure, but whether a bug is a bug? No. Not saying you are but I'd just like to point that out.
