### ISSUE TITLE
dantes inferno graphical errors

### ISSUE THREAD

**Issue by asp0909** [RPCS3/rpcs3#7741]
hello. I just want to contribute these graphic errors in comparison to the real hardware. I hope you have a solution. and thank you very much for your great work

![vs](https://user-images.githubusercontent.com/29218473/76239446-95713300-61ff-11ea-8bd9-ef8612b31038.PNG)

![vs 2](https://user-images.githubusercontent.com/29218473/76239461-9d30d780-61ff-11ea-8196-88ec6a283deb.PNG)

**Comment by jokoputera** [comment]
Logfiles please

**Comment by MarioSonic2987** [comment]
Enabling WCB/WDB/RCB/RDB and Accurate xfloat doesn't change anything:
![image](https://user-images.githubusercontent.com/20027681/76303000-45f33b80-62c1-11ea-8029-4f402b95cb8b.png)
![image](https://user-images.githubusercontent.com/20027681/76303130-82269c00-62c1-11ea-8602-f05ac7297b9d.png)

[RSX Captures](https://drive.google.com/open?id=1egDpW6B6PvWuYuXm4ySKEhtyFJqJ5cCg)

**Comment by asp0909** [comment]
you can't do anything ... it's emulator problem

**Comment by web1018** [comment]
These graphical differences are nothing major. The cut-scene issues are more noticeable, which an opened issue can be found here #7308

**Comment by asp0909** [comment]
All reports are important when informed with respect

**Comment by Dimi-link** [comment]
these are old known issues, but they are not corrected in any way...perhaps the reason is funding
https://forums.rpcs3.net/thread-197132-post-309199.html#pid309199
https://forums.rpcs3.net/thread-177907-post-309322.html#pid309322

**Comment by asp0909** [comment]
> estos son problemas conocidos, pero no se corrigen de ninguna manera ... tal vez la razón es la financiación
> [https://forums.rpcs3.net/thread-197132-post-309199.html#pid309199 ](https://forums.rpcs3.net/thread-197132-post-309199.html#pid309199)
> [https: //forums.rpcs3 .net / thread-177907-post-309322.html # pid309322](https://forums.rpcs3.net/thread-177907-post-309322.html#pid309322)

Maybe you're right,

**Comment by RainbowCookie32** [comment]
The issues might be old, but they were just reported in March. You can't expect developers to check every video, thread, and other random site looking for issues. If they are not properly reported here, chances are it won't get fixed.

Things are not always simple fixes either, and developers might be working on other things. It's easy to just sit and point that an issue is not fixed.

**Comment by web1018** [comment]
Check with @kd-11 latest PR #8367 to see if any changes or improvements made to the graphical bugs.

**Comment by jokoputera** [comment]
And disable Thread Scheduler

**Comment by asp0909** [comment]
That dev has not been released to the public ..... I think

**Comment by asp0909** [comment]
![Captura](https://user-images.githubusercontent.com/29218473/83959758-b3722200-a846-11ea-9a0e-0e4d2c26121f.PNG)
there is no change

**Comment by JohnHolmesII** [comment]
It looks like you are using master, not the PR build.

**Comment by JohnHolmesII** [comment]
Just double checked tho, and both issues remain.

**Comment by web1018** [comment]
I checked it. There was no Difference or changes to graphics.

**Comment by arcadee1977** [comment]
The latest version does not solve this problem

**Comment by arcadee1977** [comment]
The latest version does not solve this problem

**Comment by useresuser** [comment]
Still the same on 0.0.14-11506 no skybox at all, tried both interpreters, w color buffers, cpu blit, strict rendering, etc :(

**Comment by asp0909** [comment]
> Still the same on 0.0.14-11506 no skybox at all, tried both interpreters, w color buffers, cpu blit, strict rendering, etc :(

maybe they don't fix it..my friend

**Comment by kd-11** [comment]
This PR should solve the issue: https://github.com/RPCS3/rpcs3/pull/10823
Please test with the PR build.

**Comment by marcoluc97** [comment]
@asp0909 @MarioSonic2987

**Comment by Emulator-Team-2** [comment]
@kd-11 
Tested with the PR build: https://github.com/RPCS3/rpcs3/pull/10823.
The `ZCULL Accuracy: Precise` setting only fixes the black skybox.
![1](https://user-images.githubusercontent.com/38318848/132142092-4d7a667f-c59a-4932-8d81-4f527402ed83.png)

----------------------------------------------------------------------------------------------------------------------------------------------
This character still has the missing `blue highlight` as in the console screenshot above.
![2](https://user-images.githubusercontent.com/38318848/132142102-30d96d26-8e68-40e2-9220-d8130a6fbab1.png)
