### ISSUE TITLE
GRAN TURISMO HD Concept crashes upon changing camera view (Vulkan only)

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#7891]
Gran Turismo HD Concept (NPUA800119) always crashes upon changing camera view when using the Vulkan backend.
To reproduce the crash simply launch the game, select time trial and then when time trial begins change the camera view (from in-car to behind the car)...the game always crashes with the following violet error message:

·F 0:01:22.755624 {PPU[0x1000018] Thread (PDI:1000000:30b80400) [0x00147fa4]} sig_log: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKHelpers.cpp:942)

Attached log:

[RPCS3_log.zip](https://github.com/RPCS3/rpcs3/files/4397007/RPCS3_log.zip)

Using OpenGL the game doesn't crash but the frame rate is very low (half game speed, while Vulkan is full speed)

Win10
Rtx 2060 super 8gb
Intel i7 7700

**Comment by solarmystic** [comment]
Using build 0.0.9-10059, with Vulkan backend, unfortunately I cannot reproduce this error. Perhaps this is another one of those Turing specific issues?

PC Specs:-
Intel i7-7700
NVIDIA GTX 1070ti 8GB on 442.59 drivers.
Windows 7 x64 SP1

**Comment by kd-11** [comment]
There are some crashes that are only happening on turing cards. It's a known issue with possible fixes coming in the next bugfix cycle.

**Comment by PixelPickaxe** [comment]
This was happening for me to, I only have a GTX 1050 and an AMD R3 1200. Although, it's fixed with this configuration.
[config_NPUA80019.zip](https://github.com/RPCS3/rpcs3/files/4425088/config_NPUA80019.zip)

**Comment by psennermann** [comment]
Yes, with your configuration it works on my system too...so I tried to find out what's the setting that is causing the problem and to my surprise found out that it is the "Default Resolution" setting in the "GPU" tab that if it is set at "1280x720 (Recommended)" makes the game crash when switching view, while when set at "1920x1080" the game works ok and also notice that very very strangely in the menu at 1280x720 the game is slow as hell (10-15 fps), while at 1920x1080 is 60 fps (?!?)

**Comment by jacob1218** [comment]
so i'm going to post what i've found, so far about this issue
-720p default: crashes
-720p aa disabled: works
-1080p default: works

**Comment by Satan86** [comment]
GT HD enables MSAA in 720p, hence the drop in performance, and disabling AA fixes the issue. 1080p works normally.

**Comment by psennermann** [comment]
On my system (rtx 2060 super) disabling anti aliasing doesn't fix the issue, the only way is to set default resolution to 1920x1080:

- 1280x720 AA auto: crash

- 1280x720 AA disabled: crash

- 1920x1080 AA auto: works

**Comment by kd-11** [comment]
How consistent is this crash? Will it crash at start line with no input other than just changing view?

**Comment by psennermann** [comment]
Yes, it will always crash when changing view by pressing the joypad "select" button...now that I managed to change view using 1080p, at 720p it doesn't even get in game anymore because external view setting has been saved so the game crashes with a black screen (the error message is always the same)

**Comment by TonyAMG** [comment]
No crash on NPEA90002 and NPUA80019
Build 10220
i5 8400, Radon RX580 8GB

**Comment by kd-11** [comment]
This MSAA crash in GT5 was fixed a while back, no idea why we didn't mark this as duplicate. Request to reopen if issue persists.
