### ISSUE TITLE
[BLES01298] NFS The Run has behaviour and rendering issues

### ISSUE THREAD

**Issue by jenci8888** [RPCS3/rpcs3#8387]
## Quick summary
NFS The Run has some weird behaviour and rendering issues, due to using a Frostbite 2 Engine.

## Details
**Describle issue:**
- If I enable "SPU Loop Detection" completely halts game while before or shows ups "HDD save icon" message, PPU "LLVM" can't do anything with "SPU Loop Detection" same situation as before, Only PPU Interpreter.
- Some buildings are invisble in some during cutscenes.
- The beginning cutscene has some framerates the display became overlapped display, as soon disappear frames after long period, when starts ingame, while I am unable to see anything due to black vertex explosion, which it is massive, other race stages some do appear or not.

**Describe regression:**
-  ~~Character almost like T-Pose but not moving animation (yet and went gone after 1 seconds the began cutscene) and appears vertex explosion, the regression introduced in 10401-201d54ee the master build, PR: #8218~~ 
**FIXED BY** #8393 

**Note:** This game has weird behaviour, everyone else has tried to run this game for used my configuration but unable to past main menu, expect me.

**Build:** 0.0.10-10477-b75af69c Alpha

**Screenshots:**
<details>
 <summary>"regression" MARKED SOLVED</summary>

Before:
![image](https://user-images.githubusercontent.com/40495799/84020562-4adc8f80-a983-11ea-934b-b4448af3035b.png)
After:
![image](https://user-images.githubusercontent.com/40495799/84008310-f846a780-a971-11ea-8a71-f3c7f91739b2.png)

</details>

![image](https://user-images.githubusercontent.com/40495799/84007035-0bf10e80-a970-11ea-964d-cb599cb06144.png)
![image](https://user-images.githubusercontent.com/40495799/84006768-96853e00-a96f-11ea-9438-e8a5544a0501.png)

**RDC:**  https://drive.google.com/file/d/1pZaNJgJ_Zdz02DuhXW5G_hKh9_rp8unH/view?usp=sharing
**Log:**  [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4744667/RPCS3.log.gz)

System config: i5-4690k, Nvidia GTX 1050Ti 442.19 driver, Windows 10 1903 build

**Comment by jenci8888** [comment]
Please re-open again on this issue, the one "regression" was fixed, but other "Issues" aren't fixed, I'm waiting for kd-11 look into this render issue. In the future if game gets fixed freezes with PPU/SPU with SPU Loop Detection and I'll close this issue

**Comment by jenci8888** [comment]
1 year after... The game is now able to in-game further with the clock scale, which is already implemented. The terrain render fixes with WCB. 
It appears unstable with emulation timings and rare fatal errors. (The "RSXIO memory not mapped" is very commonly at 10% to 60% clock scale, the 70% clock scale and above are unable to the past main menu) The game can be stable maximum 20fps. (The more lower framerate and better stable game) 
- Light renders aren't corrected with WCB, and the headlight appears bit too bright. Without WCB doesn't work light just barely visible surface light.
![image](https://user-images.githubusercontent.com/40495799/126811879-3cedce9d-b32c-4948-83a1-89ea953c6651.png)
![image](https://user-images.githubusercontent.com/40495799/126860687-300eea4c-ed2c-4f5e-ab24-90b6a6b0ce41.png)

- Terrains aren't corrected with WCB (see left-side)
![image](https://user-images.githubusercontent.com/40495799/126812440-b8181411-7e91-46ea-965c-84e70ba9acb3.png)

But I am unable to provide RDC capture :( (Because It FIFO desyncs, after I used 7000us maxed out on the RPCS3 custom config)
RRC: https://drive.google.com/file/d/13x8Q6s9qMOhO72HmfhIyBj6766St60vK/view?usp=sharing
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6870084/RPCS3.log.gz) ("RSXIO memory not mapped")

And this is a rare error "Unknown transfer source format 0x1b"
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6869991/RPCS3.log.gz)

**Comment by Megamouse** [comment]
please test again

**Comment by Ordinary205** [comment]
the ghosting and black vertex explosion is still not fixed
Log: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/10712768/RPCS3.log.zip)

![Capture](https://user-images.githubusercontent.com/125112932/218243347-a5ae6468-5bed-456b-815f-d1c89788d42a.PNG)

![Capture 2](https://user-images.githubusercontent.com/125112932/218243809-dda11d25-56a1-492a-94f6-cf6f97b994d9.PNG)

**Comment by Ordinary205** [comment]
and here is the results for enabling the write color buffers + strict rendering mode

Log: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/10712947/RPCS3.log.zip)

![Capture 3](https://user-images.githubusercontent.com/125112932/218248173-f1339e7c-6b7e-4339-a61d-aa0a614ef555.PNG)

![Capture 4](https://user-images.githubusercontent.com/125112932/218248187-07465169-8ec1-4fcd-b203-c4206cbc0a04.PNG)

**Comment by Ordinary205** [comment]
The ghosting and black vertex explosion still exists

![ghosting](https://user-images.githubusercontent.com/125112932/219742193-c6630d2c-9009-42fc-82e9-4b71f56fc358.PNG)

![black vertex explosion](https://user-images.githubusercontent.com/125112932/219742268-d512a654-177e-48f8-a0e8-a9c9ea37a61c.PNG)

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10769789/RPCS3.log.gz)

**Comment by Ordinary205** [comment]
when I'm using Recompiler (LLVM) it creates a loud audio during gameplay. However when I enabled Recompiler (ASMJIT) it fixes the audio but makes the game less stable.

**Comment by Ordinary205** [comment]
The game now runs further with higher clock scales after LLVM 16.0.0 update (14846 Build).

![rpcs3 exe 2023 04 16 - 22 43 43 05 - frame at 1m5s (2)](https://user-images.githubusercontent.com/125112932/232335871-45af521e-496c-4063-b179-e9e6e6abe69a.jpg)
![rpcs3 exe 2023 04 16 - 22 43 43 05 - frame at 11m5s (2)](https://user-images.githubusercontent.com/125112932/232335874-c6f33c3d-408d-4ca1-8973-56e4327697e2.jpg)

But sadly there are still some random freezes like when getting busted by the cops, it freezes when trying to trigger a quicktime event gameplay.

![rpcs3 exe 2023 04 16 - 22 43 43 05 - frame at 15m18s (2)](https://user-images.githubusercontent.com/125112932/232335973-844c1f76-a94f-491d-b5d0-d9f5eca8286d.jpg)

**Comment by Ordinary205** [comment]
I decided to show a comparison between RPCS3 and a real PS3, so that it would be easier to tell the difference.

RPCS3 without WCB:
![NFS the run 2 (2)](https://user-images.githubusercontent.com/125112932/232582396-8ada0991-493e-461f-87e6-bf4465843ff6.jpg)

RPCS3 with WCB:
![NFS the run (2)](https://user-images.githubusercontent.com/125112932/232582452-c4fb5dfb-fe2a-4254-beac-44f7a650d3df.jpg)

Real PS3:
![NFS the run 3](https://user-images.githubusercontent.com/125112932/232583473-c90f7925-5e7f-4463-8b86-55475606e4c8.PNG)

Without WCB: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11254840/RPCS3.log.gz)
With WCB: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11254836/RPCS3.log.gz)

**Comment by Ordinary205** [comment]
I've added a list for this game that no longer contains bugs or still has one.

Bugs that has been fixed:
- [x] ~~SPU loop detection halts the game.~~ (Fixed)
- [x] ~~Vertex explosions on NVIDIA drivers.~~ (Fixed, requires WCB to fix this issue)
- [x] ~~Some buildings are invisible during cutscenes.~~ (Fixed)
- [x] ~~Ground/mountains are invisible.~~ (Requires WCB+RCB to fix this issue)
- [x] ~~The lighting appears very dark.~~ (Requires WCB+RCB+RSX tiled memory to fix this issue)

Bugs that are still NOT fixed:
- [ ] RSX crashes commonly occurs when WCB is enabled.
- [ ] Lighting appears incorrect with RCB.
- [ ] Artifact reflections occurs on vehicles, mountains, and characters.
- [ ] Mountain textures appears incorrectly at far distances.
- [ ] Trees/bushes spawns on the road or midair. (Still exists after shaders gets compiled)
- [ ] Ghosting.

**Comment by Ordinary205** [comment]
The Need for Speed UI sometimes flickers or gets messed up the more you progress the campaign mode.
Notice where the UI on top of the screen where it shows "CLEAN PASS" corrupted:
![Broken NFS UI](https://github.com/RPCS3/rpcs3/assets/125112932/2b91efe1-f474-43e1-b3e6-faf375e3e5c5)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13544088/RPCS3.log.gz)
I also added this bug on the list.

**Comment by matheuswillder** [comment]
It's been almost two years since the last tests/comments above. Has anything changed here? I decided to do some testing, but the configs listed in the Wiki caused me random crashes before going in-game, but I don't have time to test with other configs right now (I need some sleep, lol).

Log:

[RPCS3.log.gz](https://github.com/user-attachments/files/23046220/RPCS3.log.gz)

**Comment by Triticum0** [comment]
@matheuswillder read https://github.com/RPCS3/rpcs3/issues/8387#issuecomment-1761749281try turning of wcb. and with your question properly not, alot work is still need be done to this game to be playable. Note: I haven’t test the game recently but my guess.

**Comment by matheuswillder** [comment]
I see. I started following RPCS3 just a few months ago and just was curious if anything had changed for this game, but since I couldn't find anything updated, I decided to test it for myself.

Thanks, I'll take a look at that.

**Comment by Darkhost1999** [comment]
The meta tracker comment with the tick boxes is current and up to date

**Comment by digant73** [comment]
please an update on current build

**Comment by rleonever** [comment]
Hello, can someone test again? recent RSX fixes may fix some issues of this game
