### ISSUE TITLE
Multiple Guitar/DJ Hero controllers cannot be used

### ISSUE THREAD

**Issue by ualtinok** [RPCS3/rpcs3#8666]
This is to reopen the old issue that has been closed without a fix:

https://github.com/RPCS3/rpcs3/issues/7898

**Comment by bevanweiss** [comment]
@ualtinok if you could try again with the latest RPCS3 version and repost your log it would be greatly appreciated.
I don't believe this release will have a 'fix', but I'm hoping it provides some info to narrow down the problem.

**Comment by ualtinok** [comment]
Hi @bevanweiss, I was just had time to test here's the log:

RPCS3 v0.0.11-10742-4ce2ad54 Alpha | HEAD | Firmware version: 4.85
AMD Ryzen 9 3950X 16-Core Processor | 32 Threads | 127.93 GiB RAM | TSC: 3.500GHz | AVX+ | FMA3
S ppu_loader: PPU executable hash: PPU-b70a9965638aa43c4edec58683cf0f2dfed8071b (<- 0)
S ppu_loader: SPU executable hash: SPU-928a10fa930853ebba6bb010068309e8375bbec4 (<- 0)
Segment: p_type=0x1, p_vaddr=0x3000, p_filesz=0x1b2a0, p_memsz=0x1b2a0, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x1e300, p_filesz=0xe0, p_memsz=0x20980, p_offset=0x1b400
Segment: p_type=0x1, p_vaddr=0x3ec80, p_filesz=0x40, p_memsz=0x40, p_offset=0x1b500
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x1b540
SPUNAME: '../../../Lib/spu_net_9-0/release'
S ppu_loader: SPU executable hash: SPU-c1d2180a70be4fbc1e288eb3b71b780be326b8be (<- 0)
Segment: p_type=0x1, p_vaddr=0x3000, p_filesz=0x18590, p_memsz=0x18590, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x1b600, p_filesz=0x20, p_memsz=0x360, p_offset=0x18700
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x18720
SPUNAME: 'PS3_Release/PS3_BINK_SPU.elf'
S ppu_loader: SPU executable hash: SPU-5f1faae019b28664ffa44871805dcf0fb432fa2e (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x10a0, p_memsz=0x10a0, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x1180, p_filesz=0x0, p_memsz=0x30, p_offset=0x1180
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x11a0
SPUNAME: 'Output/BitReductionDsp_SPU/Relea'
S ppu_loader: SPU executable hash: SPU-113534d28de5653f20bcfa42934c47947e05d251 (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x4f0, p_memsz=0x4f0, p_offset=0x80
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x570
SPUNAME: 'Output/RingModDsp_SPU/Release PS'
S ppu_loader: SPU executable hash: SPU-89e088218a2128e4830e20b22841aa246381625e (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x1970, p_memsz=0x1970, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x1a00, p_filesz=0x0, p_memsz=0x80, p_offset=0x1a00
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x1a70
SPUNAME: 'Output/BeatRollDsp_SPU/Release P'
S ppu_loader: SPU executable hash: SPU-33965d871fd361f1df7e2590bd3809ca7467492f (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0xd50, p_memsz=0xd50, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0xe00, p_filesz=0x0, p_memsz=0x10, p_offset=0xe00
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0xe50
SPUNAME: 'Output/StutterDsp_SPU/Release PS'
S ppu_loader: SPU executable hash: SPU-29f83f40947eb4122984c35260e4d896294fc313 (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x29e0, p_memsz=0x29e0, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x2a80, p_filesz=0x0, p_memsz=0x80e0, p_offset=0x2a80
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x2ae0
SPUNAME: 'Output/DelayDsp_SPU/Release PS3/'
S ppu_loader: SPU executable hash: SPU-b001cb7f99055ae9b6703a9ab11477e45a2e4a93 (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x1b00, p_memsz=0x1b00, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x1b80, p_filesz=0x0, p_memsz=0x20, p_offset=0x1c00
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x1c00
SPUNAME: 'Output/BiquadDsp_SPU/Release PS3'
S ppu_loader: SPU executable hash: SPU-70e7c6ea4e18c277469502a1577b0770e44ce0c1 (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x790, p_memsz=0x790, p_offset=0x80
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x810
SPUNAME: 'Output/VolumeAnalysisDsp_SPU/Rel'
S ppu_loader: SPU executable hash: SPU-ba07926d53682567bfe57fc3961955d1eea0b677 (<- 0)
Segment: p_type=0x1, p_vaddr=0x3000, p_filesz=0x11100, p_memsz=0x11100, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x14100, p_filesz=0x200, p_memsz=0x25e70, p_offset=0x11200
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x11400
SPUNAME: 'PS3_SPURS_Release/fmodex_spurs.e'
S ppu_loader: SPU executable hash: SPU-1f240815b9a2b5e206e87b52f30c709f73b1e4d8 (<- 0)
Segment: p_type=0x1, p_vaddr=0x3000, p_filesz=0x9b40, p_memsz=0x9b40, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0xcb80, p_filesz=0x60, p_memsz=0x26a40, p_offset=0x9c80
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x9ce0
SPUNAME: 'PS3_SPURS_Release_NeuralTHX/fmod'
S ppu_loader: SPU executable hash: SPU-912f570fc8270b6c38b0449660e54c292cd6668e (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x6590, p_memsz=0x6590, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x6680, p_filesz=0xb0, p_memsz=0x2b0, p_offset=0x6700
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x67b0
SPUNAME: 'PS3_codec_adpcm_Release/fmod_cod'
S ppu_loader: SPU executable hash: SPU-d6ef9b1cfb4b0e0337dbacd702e48ba82fd77ba4 (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x2d20, p_memsz=0x2d20, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x2e00, p_filesz=0xb0, p_memsz=0x2b0, p_offset=0x2e80
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x2f30
SPUNAME: 'PS3_codec_raw_Release/fmod_codec'
S ppu_loader: SPU executable hash: SPU-d052989cf247e4f6fcd39fa17e5a05c81c751fbd (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x2740, p_memsz=0x2740, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x2800, p_filesz=0x30, p_memsz=0xc0, p_offset=0x2880
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x28b0
SPUNAME: 'PS3_dsp_lowpass_Release/fmod_dsp'
S ppu_loader: SPU executable hash: SPU-1314db58e42d4c6cf3ab1d606f362ce4c65b49ed (<- 0)
Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x13a0, p_memsz=0x13a0, p_offset=0x100
Segment: p_type=0x1, p_vaddr=0x1480, p_filesz=0x20, p_memsz=0xb0, p_offset=0x1500
Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x0, p_offset=0x1520
SPUNAME: 'PS3_dsp_parameq_Release/fmod_dsp'
S ppu_loader: PRX library hash: PRX-aba8af845072f7dc2664b5a958a9a4f2496f59a8 (<- 0)
S sys_usbd: Found device: DJ Hero Turntable x2
E RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.
S GUI: Boot successful.
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-rR1fSwSskfb51Kg4G1xb32-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-bfytsaCVSrw4osM9i40Rz1-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-pfVUenLZUy9LwUKLpjGL7c-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-s82pS8ngdLsCiwuhXu4Zqq-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-SnX4wrUvVFaQ7RzjkxiurL-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-bd2YdAi3ACEtGQ6HR53uk0-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-7xRsA4ncfiWsn9n3yGCRxb-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-pwRCaUJX6vMoPfkrcySWUM-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-q8kHxFyaz8yJ0MxZ5kwaCt-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-Fnn0id4SomQFdAPEWWW4Lw-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-aKG2gYEv63uczcgfVSHNnF-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-VuAutqw9c2S5LK7gRiy1my-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-6bhijZvU5Fz38z5aQFzgru-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-0vdStSHzuPrmEhXK2xPQR9-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-SZti5ygX4eKJUo8x5M5QPQ-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-KwKAT3Sf5s28e9XpFjnUcV-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-MtJeqE5UrbVZxXVmprxhU8-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-P9Fa3W4jbaYA6mAGRv3VZj-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-c51xvJLot8sWEPkZo0obs0-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-Giha7J6r4jJEme8YesMMn4-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-aAFxgrpN2SdTnHUFLEX0xb-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-8ePGXzPAEMs5eEUhwk2CUY-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-5HWq0uS5ZYbYp8R4T6eecJ-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-KrTiuqH4sk5RmGr64UoQCJ-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-RschUHWQdRSk6pghXW0r1c-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-GkQv6JdU7CKmWWWZdgeony-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-aeJ0U9xbPZV9skUMJqmHmY-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-Gn0JPgyytS84tbsPdR76Hh-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-kWPYVyAvyUNPZE1aqUTd0j-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-tE0UuXkzV16ko65uNy42j2-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-sr8mHyfHM8oZLHVv4m1k6z-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-VMu00f9eQ8RZ69uE3e9Qnb-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-6rmNdxiRoKHehWfhTFku2s-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-s3e7y4Mb3FP0RTohpm8C48-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-XUnSS0LwrYSJNWruo5iPTx-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-i9hRa1rTUnQH5Lg33XsFVj-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-TLWjQNy0AYXLW6awgfEvmW-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-T8JeGc64Xyf96kzNc5EKCm-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-0xRFdk9wxC6p8SARrmeKTg-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-A2e3A7s0nW42bT3EiwPen6-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-gFowhH7vezQGJUGHGwTsff-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-NhuTgcb72AJ5K8jYjb4E9g-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-V4nruhaH4LzNVxhxfiy67C-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-HhU8S7RS5qhXZfdzAGeWNa-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-qaw6P5WHuMZA6ydR5oNhqf-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-May7i0PXASA5sx9YgcCFdV-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-jUyH1rgUd17k44hWazYC57-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-N0pLoduCdVoQQsKtFrkMbs-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-G7YPTVsSLhT0YACHmbJJYS-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-6vYg28WU5CzbpWAaawWVJ0-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-eUspiYHG83CadrXmSeZHf1-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-TupqnKwEyHpQUuSRQCEMf3-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-RHyjus40XHFfnVLPPUXNQ4-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-iTdwhzSLeSyM1pgvwmKgCh-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-HMp90rkk7C5NhrVb2jH3NF-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-d7Eo3n7fFH0qyUnPmeJFhT-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-2wiVFbztCJnSKhPGcsvVfR-00000G-znver2.obj
S UPDATER: RPCS3 is up to date!
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-Gn8jJs1r0Tk4TT5FbmcySP-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-SncRgLYitoUmaQWtQ7y3rA-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-p1a62xM5mw8cmgyr8n0uPj-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-UReoK9d9pyXQtkXHt1bsAw-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-nqTvectPi6Q1TsotzJS6eV-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-6kTXfeCtqf0sf5duh6rHPs-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-AsU6mfMkyjmCJcn3TzAKP0-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-Utc53C1ZJkaNxMGNRP2QQ3-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-U8yW22fM0ZrW0Fjf8rCiXY-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-mGx1diF8FnasTjrRG4sbtr-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-TJJCx9Wpefi8Gt6mkQ1LuZ-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-HCC7y0oPeFzZJaaZzEhUs5-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-YHMTv1tSgEKGKLp6Cdkzrs-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-Sj8bLLScbFpaCd4mQ5ak0H-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-7zg0RkCNPNyHeVPQkGKwcy-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-tq9L2P8QJ9TFeCrKPkjSed-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-V7mNZ2KM775r1SHC7c7p6p-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-o8uYexrxTzzYz4bmi0tSW6-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-E4mPytRnKraMqGWcN5eZQe-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-b3KRMaL5rKQG8ezaNn699M-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-E3i5kfeXW5YE2HWMsfeAtG-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-YmFCvEmcSSJhfxoqWpLMMb-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-mis5vvcxJWCh5UtsWoSY3g-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-VpwooNxGWQuPC2vyxdfNGC-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-1cT6TU4jwZW4nbXzyzAnsN-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-WWcpt1FmuK1i5kkWKohrP2-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-H8XdmtsFsunMk0MWC4kubS-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-9guXVTZi1F8cTpKqr2Cgc3-00000G-znver2.obj
S {PPU[0x1000000] main_thread } PPU: LLVM: Loaded module v3-tane-KCXPzQvyKS0TkKaAdvtP8r-00000G-znver2.obj
S {PPU[0x1000000] main_thread } SPU: SPU Runtime: Built the interpreter.
S {PPU[0x1000000] main_thread } SPU: SPU Runtime: Built 2457 functions.
U {PPU[0x1000000] Thread (main_thread) [0x0107fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x010800bc]} sys_prx TODO: _sys_prx_register_library(library=*0x10826a0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-6bf437f05980eee0257bc1d29d8ec0fec0f166f5 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-1z3Pyu8YVnnorJiQ2hfu1e-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U {PPU[0x1000000] Thread (main_thread) [0x010c3d8c]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E {PPU[0x1000000] Thread (main_thread) [0x010c3d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U {PPU[0x1000000] Thread (main_thread) [0x010c3d24]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} ppu_loader: PRX library hash: PRX-f50c4616d91abb2d4c167950dade5df60ddce6ab (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} PPU: LLVM: Loaded module v3-tane-XCgQWMc1s99n1WTwrpWvw4-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} ppu_loader: PRX library hash: PRX-49a41053603b857224ff832b37d42f5e5ebe0b99 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} PPU: LLVM: Loaded module v3-tane-TP3c8YsdNggjaG5WRjcboe-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} PPU: LLVM: Loaded module v3-tane-LWAKW9c35vXJad6uHkwzhK-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} ppu_loader: PRX library hash: PRX-4b754af5b92c5cc0603a0d11b63aa8dad1f3ca27 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} PPU: LLVM: Loaded module v3-tane-fLV79QqHgPi90UziTsWrHo-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010814d0]} sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001200)
U {PPU[0x1000000] Thread (main_thread) [0x0108061c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-9fc37c5f831aaf88330290bd0e4fe79d965e4278 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-ZAhea3FFhakpfMa36ZvaNx-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/librtc.sprx” (id=0x23004100)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-02037caece9b2868642a9f6900f2c23b7c724d07 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-3dt5v1GUnYtexdcZ9VmbTW-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-cWzq9SFVhqTQTWZ7swxd0Y-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libpngdec.sprx” (id=0x23004200)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-8d91093a0cc059a359ef53594337171b367a2152 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-2my7r7Nd2rncZdtcuT9g60-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-aaAKL9HJRRAWFrQ1t0vFNk-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23004400)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-b008f05d2caa41ba0f08885eeef084dcfa94c738 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-Fw28ZLYjrm28jGkCjyP0Ew-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-SqhVEw8Eg0UcRMfygtcfjd-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-FotbZ1TdsVMNYskb7W12s6-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libssl.sprx” (id=0x23004800)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-4eed735eb723acaa5f244772c6dbdb2e6ae53d56 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-95r7Juhw7niQj6t9SAfNTR-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-XuGVy2wEHwt3xmazyhQcgn-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-Azvpte0puqKSeF3SPfQ5z5-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libhttp.sprx” (id=0x23004900)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-34a22ed90a70371179b907d01f77209f792a15c3 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-jJoZ07PrzerYWWhZciLzhv-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libl10n.sprx” (id=0x23004d00)
U {PPU[0x1000000] Thread (main_thread) [0x0107ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0107ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x0107ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0107ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
S {PPU[0x1000000] Thread (main_thread) [0x00e50770]} cellSysutil: Mounted existing cache at C:/Users/ufuka/Desktop/ps3/dev_hdd1//caches/BLES00896_BLES00896/
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} ppu_loader: PRX library hash: PRX-b27af372108595645a9342053f2e115686b945bf (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} PPU: LLVM: Loaded module v3-tane-GidnR56pzgun0Z5aqipN0L-00000G-znver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x010809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libusbd.sprx” (id=0x2300a300)
S {PPU[0x1000000] Thread (main_thread) [0x014c6e2c]} sys_usbd: Ldd device matchup for <USBInterface>, assigned as handled_device=0x1
S {PPU[0x1000000] Thread (main_thread) [0x014c6e2c]} sys_usbd: Ldd device matchup for <USBInterface>, assigned as handled_device=0x2
U {PPU[0x100000d] Thread (libusbd_usbd_thread) [0x014c2b44]} sys_usbd TODO: sys_usbd_attach(handle=0x115b) x2
U {PPU[0x1000000] Thread (main_thread) [0x00e55868]} sceNp TODO: sceNpBasicRegisterHandler(context=*0xac8a20, handler=*0x9bcf58, arg=*0x32d9ee0c)


Let me know if you need any other information.  As I mentioned on the other issue, this sometimes works:

Plug single dongle, start the game, quit the game, go the pads, disable player1 and player 4, plug second controller and start the game. This sometimes works, most of the time does not. 

Thanks for taking time.

**Comment by dio-gh** [comment]
For the love of god, remove that and upload it in file form instead. RPCS3 saves its logs into `RPCS3.log` and `RPCS3.log.gz`, latter only exists if the emulator doesn't crash. Either of these files would be nice.

Never copy from the log window, not every log message is shown and it's super spammy.

**Comment by ualtinok** [comment]
Unfortunately it does crash so here's the zip file, sorry for the clutter. 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5047752/RPCS3.zip)

**Comment by ualtinok** [comment]
@bevanweiss Is there a way I can help you debug this? I can setup a test machine with dongles plugged in and dev env is prepared and maybe you can remote debug?

**Comment by bevanweiss** [comment]
Sorry, I didn't even look in depth at the log until now.
I can't see any USB issue from the log.
It's enumerating both of the USB devices, the first as 'handle 1', the second as 'handle 2', which makes sense.
Then it uses sys_usbd_open_pipe successfully on both of the device handles.
And then it seems to go happily for a little while until:
·E 0:02:23.354325 {VBlank Thread} SYS: 'Unknown function' failed with 0x00000000 : 0 [1]
and then a few more
·E 0:02:23.355473 {PPU[0x100000c] Thread (libusbd_callback_thread)...} SYS: 'sys_usbd_receive_event' failed with 0x00000000 : 0
·E 0:02:23.355462 {PPU[0x1000008] Thread (CArchiveFilesystemThread)...} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0
·E 0:02:23.355462 {PPU[0x1000009] Thread (CDLCFilesystemThread)...} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0
·E 0:02:23.355476 {PPU[0x1000012] Thread (hkSpuUtil Helper)...} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0
·E 0:02:23.355456 {PPU[0x1000001] Thread (FSGSpuSpursHdlr1)...} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0
·E 0:02:23.355471 {PPU[0x100000f] Thread (_gcm_intr_thread)...} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0

It might be worth playing with the vblank/vsync, just to see if there's any difference.
I'll have another look at that libusbd function to see if there's anything apparent that might get 'triggered' by two devices.

**Comment by ualtinok** [comment]
Hi @bevanweiss, there wasn't any change with vblank/vsync configs. Let me know if I can do anything to help debug this.

**Comment by bevanweiss** [comment]
It would be worth you testing out the PR I have for the libusb update. I think the problem is in the rpcs3 handling. But it's worth a try.

**Comment by bevanweiss** [comment]
@ualtinok it would be great if you could have a quick test with the latest PR that I have #9096 
[Windows](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQ0MDEvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip)
[Linux](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQ0MDEvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitMaW51eA2/content?format=zip)

**Comment by Crafty-The-Fox** [comment]
also, rpcs3 doesn't crash. for me it just ignores the second one and only works with the first dongle.

**Comment by ualtinok** [comment]
Hi @bevanweiss, thanks for the update. Now, as @Crafty-The-Fox also mentioned it doesn't crash when both dongles are connected but both controllers shows P1 indicator and only one controller works. If I disconnect the active dongle game starts rotating menu items in a loop. (as if you turn the turntable constantly). I've tried to start with 1 dongle plugged and plugging the other one after the game starts but still it connects as P1 also. Good thing is I couldn't make it crash in any combination. 

Let me know if you want me to try anything.

**Comment by bevanweiss** [comment]
I think I've identified the issue with multiple devices.  I've only got two devices to test with (guncon3 and skylander portal), but given that both of these appear to be reported by libusb as having serial numbers of 0x0000, then I suspect that libusb (at least under Windows) is reporting all devices as having a serial number of 0x0000... which would be confusing the PS3 applications.

It might be worth if you could try to use something like the application here:  http://www.usblyzer.com/
To just enumerate your USB devices, and see for each of the items you have if the iSerialNumber is reported as non-zero for any of them.
![image](https://user-images.githubusercontent.com/2055446/97016797-e8360a00-1598-11eb-8cad-61d301acc944.png)

The other potential 'hack' will just be to fake in an incrementing number for each device attached if the serial number is 0.

**Comment by Crafty-The-Fox** [comment]
i just use winUSB, not libUSB. should i use libUSB instead?

**Comment by bevanweiss** [comment]
> i just use winUSB, not libUSB. should i use libUSB instead?

WinUSB is the driver, libusb is the library that we use for the platform independent access to USB.
So if you use RPCS3, and your devices work in Windows, then you're using both already :)  WinUSB for your driver, and LibUSB as bundled in rpcs3 for our USBing.
I've been digging through the libusb code we use also, and it's not even libusb's fault (directly).  The Windows DeviceIO function call that libusb uses isn't returning anything meaningful for the serial number.
The proper fix is probably going to involve trying to get something upstream into libusb... which is tough.

**Comment by ualtinok** [comment]
It is indeed 00h for both dongles. Is there any workaround?

**Comment by bevanweiss** [comment]
@ualtinok does having two controllers connected definitely work on the PS3 itself?
I've looked more into this under linux, and it does appear that the devices themselves (the Skylander portal at least) also doesn't report any serial number.  So I'm unsure how the PS3 would be determining the difference between them.

If you could provide logs of connecting the two devices (to rpcs3) it would be appreciated.
And if you could enable the logging of trace level info it would be great.

**Comment by ualtinok** [comment]
Yes it does work on PS3 itself, also I was able to run on RPCS3 with weird hacky way sometimes: https://github.com/RPCS3/rpcs3/issues/7898#issuecomment-615884323

I will get you trace level logs. I think increment method would work, maybe even original PS3 does that way for same product ids.

**Comment by ualtinok** [comment]
@bevanweiss I just had time to get the logs. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5482036/RPCS3.log.gz)

**Comment by ualtinok** [comment]
Is there any more data I can give to help this resolved?

**Comment by Crafty-The-Fox** [comment]
Theres a check in RPCS3 to stop 2 tables from working, or connecting. @shockdude removed this check and i tested, it just hanged RPCS3. atm i dont have a log but il get one eventually.

**Comment by shockdude** [comment]
> Theres a check in RPCS3 to stop 2 tables from working, or connecting. @shockdude removed this check and i tested, it just hanged RPCS3. atm i dont have a log but il get one eventually.

Btw I was wrong and misremembered, there never was a check stopping 2 real tables from attempting to connect, both before and after my emulated DJH table changes. So this issue is still present in master for DJH tables, and probably for all other USB devices currently whitelisted.

**Comment by Crafty-The-Fox** [comment]
issue is still present in master, heres the log 
[RPCS3 2 table 2 dongle.zip](https://github.com/RPCS3/rpcs3/files/7585264/RPCS3.2.table.2.dongle.zip)

**Comment by MarcusRivet** [comment]
I'm not sure but this sounds like the same issue that I have stated here: https://github.com/RPCS3/rpcs3/issues/11174 But with buzz controllers instead. Cuz if you wanna connect more than 4 buzz controllers, you need to connect 2 usb-recievers which just doesn't work and or crashes RPCS3.

**Comment by RipleyTom** [comment]
https://github.com/RPCS3/rpcs3/pull/11193 may fix, please test :).

**Comment by Crafty-The-Fox** [comment]
Tested, still the same crash. however, it does know that there are 2 tables plugged in. 
`S sys_usbd: Found device: DJ Hero Turntable x2`
 is what it said in the log, and as always heres the log file
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7591377/RPCS3.log)
.

**Comment by RipleyTom** [comment]
Updated the PR it should be fixed now :).

**Comment by ualtinok** [comment]
Hey! 

I'd love to test this also, is there an automated build system for pull reqs or do I need to compile myself?

**Comment by Darkhost1999** [comment]
> Hey! 
> 
> I'd love to test this also, is there an automated build system for pull reqs or do I need to compile myself?

Just go to the PR. Click checks -> cirrus Windows (or Linux) depending on your OS.
Then click view more details on cirrus CL then click artifacts and download the .zip extract it and rename rpcs3.exe to anything.exe (name doesn't matter as long as it's not rpcs3.exe)
Drag the .exe to your current RPCS3 folder and launch the executable.
Should launch as the test build with all your games and settings.

**Comment by ualtinok** [comment]
It seems the problem still persists. It works only with single dongle, when 2nd dongle is plugged it's frozen at game load.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7592569/RPCS3.log)

**Comment by shockdude** [comment]
2 real turntables works in PR #11202, confirmed by another DJH2 player
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7610945/RPCS3.log.gz)

**Comment by RipleyTom** [comment]
I'll assume multiple guitars now work too, feel free to reopen if that's not the case.
