### ISSUE TITLE
Silent Hill Downpour - No Audio

### ISSUE THREAD

**Issue by xVxXPrinceXxVx** [RPCS3/rpcs3#9061]
Audio doesn't seem to be working on newer builds, changing Vulkan to OpenGL or XAudio2 to OpenAL doesn't fix the issue, the game starts entirely mute.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5362626/RPCS3.log.gz)
<img width="1864" alt="no audio" src="https://user-images.githubusercontent.com/19231635/95698853-3fdb8980-0c19-11eb-9004-56d54e558e90.png">

Sorry for posting this issue in the wrong place.

**Comment by Realmantik** [comment]
I tried v0.0.12-11002-95c1443e build and the game works fine.

**Comment by elad335** [comment]
Need information on how to reproduce as other testers couldn't reproduce.

**Comment by X0Reactor** [comment]
I found that setting Vblank to 120 Hz is what causes the audio to cut off randomly. Anywhere between the start screen to 10 or 15 minutes after starting the game will cause this to happen. RPCS3 v0.0.12-11119-f03d4cf8 Alpha

**Comment by pokevania** [comment]
I too upscaled to 120 VB / 4K, but the problem persists even at default settings. Only PPU Interpreter seems to fix it.

**Comment by digitaldude555** [comment]
There is sound now.

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by pokevania** [comment]
@digitaldude555 There always was sound. It cuts out after several minutes, hence this thread. The problem persists with the current build.

**Comment by xVxXPrinceXxVx** [comment]
@pokevania even with the PPU interpreter the issue persists

**Comment by singh787** [comment]
I've tried every setting combination, best thing was disabling SPU loop but even with that only got few mins audio then completely silent, Though playable

**Comment by urbanorush** [comment]
OK, we need a fix, i tried all configs, but sound just dissapear in random points, or what emu version can be works?

**Comment by urbanorush** [comment]
Any fix?

**Comment by elad335** [comment]
When something changes I'm sure someone will update this thread.

**Comment by singh787** [comment]
Hopefully in the next few updates the Sound Bug is fixed

**Comment by Goddess-Bastet** [comment]
Sound problematic for me too.
It can work from anything to a few seconds to a few minutes then cuts out.

**Comment by idruzhinin** [comment]
Disabling TSX alone fixed the problem for me. Before that nothing I change had any effect - the sound disappeared after about 5 min.

**Comment by Goddess-Bastet** [comment]
This also improves on the constant crashing. Although it still happens on occasions it doesn’t happen as often as it did.

**Comment by pokevania** [comment]
Played ~3 hours and it's nearly perfect. There was a brief screen-wide instance of flickering sprites. Switched to ASMJIT. A portrait flickered once afterwards, nothing significant. Ran 4K with 120hz vblank for 60 fps. So awesome!

**Comment by urbanorush** [comment]
Hey guys, problem it´s completly fixed using the debugger to stop unnecessary SPU threats at game starts. Game works perfectly whit this metod, another way its a lucky trys.

**Comment by RainbowCookie32** [comment]
> Hey guys, problem it´s completly fixed using the debugger to stop unnecessary SPU threats at game starts. Game works perfectly whit this metod, another way its a lucky trys.

That's not really a fix, just a hacky workaround.

**Comment by urbanorush** [comment]
> > Hey guys, problem it´s completly fixed using the debugger to stop unnecessary SPU threats at game starts. Game works perfectly whit this metod, another way its a lucky trys.
> 
> That's not really a fix, just a hacky workaround.

call it what you prefer, it works

**Comment by nitroos-ai** [comment]
There were changes to TSX in #11265. Retest please with latest master.

**Comment by Megamouse** [comment]
closing due to inactivity
