### ISSUE TITLE
CRYSIS 1 both game versions not booting up

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#9280]
In game compatibility, it showing "Ingame", but in testing it is not booting up and only white screen appears with 0 fps for both VULKAN and OPEN GL. After testing both game versions with two different RPCS3 version give same result.

1. RPCS3 v11240 - Log files for both game versions NPEB00575 & NPUB30302.
[NPEB00575 VULKAN.gz](https://github.com/RPCS3/rpcs3/files/5545879/NPEB00575.VULKAN.gz)
[NPEB00575 OGL.gz](https://github.com/RPCS3/rpcs3/files/5545885/NPEB00575.OGL.gz)
[NPUB30302 VULKAN.gz](https://github.com/RPCS3/rpcs3/files/5545886/NPUB30302.VULKAN.gz)
[NPUB30302 OGL.gz](https://github.com/RPCS3/rpcs3/files/5545887/NPUB30302.OGL.gz)

2. RPCS3 v10984 - Log file for NPUB30302.
[Rpcs3 v10984 NPUB30302 VULKAN .gz](https://github.com/RPCS3/rpcs3/files/5545895/Rpcs3.v10984.NPUB30302.VULKAN.gz)

**Comment by Yahfz** [comment]
Crysis has worked fine before so this seems to be a regression. Try looking for the version that broke it and report back, that will increase the chances of it being fixed a lot more.

**Comment by Krishster** [comment]
i again tested with three random earlier versions before v10984 and found simmilar result of white screen with 0 fps

**Comment by Yahfz** [comment]
You may have to test even older versions.

**Comment by xddxd** [comment]
Crysis 3 is also affected, it's regressed by #8620, last working build is 10680.

**Comment by elad335** [comment]
ok I know why thanks for testing

**Comment by elad335** [comment]
should be fixed by #9290 (didnt test).

**Comment by Krishster** [comment]
download link for your new #9290 build ?

**Comment by elad335** [comment]
wait a few days then you wont need a link.

**Comment by Krishster** [comment]
elad335 - did not solve issues for crysis 1 game with #9290.... kindly look into the log files....

log file - 
[NPEB00575.gz](https://github.com/RPCS3/rpcs3/files/5561905/NPEB00575.gz)
[NPUB30302.gz](https://github.com/RPCS3/rpcs3/files/5561908/NPUB30302.gz)

**Comment by elad335** [comment]
try disabled SPU loop detection with latest master

**Comment by Krishster** [comment]
ok... after disable spu loop, game now boots but failed to pass after menu. also game booting rate is 3 out of 10. means every 7 time it is freezing at random point at intro and 3 times passed the intro or menu or starting cut scene then freeze.

**Comment by elad335** [comment]
random freezing was always a known issue, possibly with another issue thread on it.

**Comment by elad335** [comment]
maybe RSX wakeup delay helps it not sure.

**Comment by Krishster** [comment]
rsx wake up delay set to 200.... ok i will test it till further with permutation combination.

**Comment by RainbowCookie32** [comment]
Crysis games and SPU LLVM have always been a problematic match on the stability field. ASMJIT has always been a lot better for me on them.
