### ISSUE TITLE
Armored Core Verdict Day (Rendering and stability issues)

### ISSUE THREAD

**Issue by dulsan** [RPCS3/rpcs3#9697]
## Quick summary
When in game the ACs dont have proper textures and they are extremely glossy, in addition to this, the performance of the game is horrible with all kinds of memory access violations happening randomly.

## Details
1. Textures incorrect (rainbow flicker textures), and the textures are very glossy.
2. Unstable performance (lots of stutter), 14-30fps (drops frames when in cities or in densly packed areas)
3. Random memory access violations (From observation: when missions are completed, in the hanger and during the mission.)
[Memory access violation: u32]
4. I've also noticed flickering environment graphics and the sun being very bright. 
5. There is alot of audio stutter (This happens in ACV aswell)

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5901415/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/13959909/106407443-25f7d800-6490-11eb-819d-9cab716ea2bd.png)
(Dont know how to get a render doc)

#### 3. Please attach screenshots of your problem.
![Screenshot 2021-01-30 094606](https://user-images.githubusercontent.com/13959909/106404684-a239ed80-6487-11eb-8a9b-744b2b25766b.png)
![Screenshot 2021-01-30 151649](https://user-images.githubusercontent.com/13959909/106404692-a534de00-6487-11eb-8c23-3677637876da.png)
![Screenshot 2021-01-30 094621](https://user-images.githubusercontent.com/13959909/106404694-a6fea180-6487-11eb-9069-d4a581a3535d.png)

#### 4. Please provide comparison with real PS3.
https://www.youtube.com/watch?v=WH9StiL72G0&ab_channel=gocalibergaming

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: i7 9700 3.00GHz
* GPU: Nvidia 1660 Ti (Driver Version: 461.40)

**Comment by Gael2433** [comment]
Armored Core titles require Write Color Buffers enabled for proper shading on the mechs.

**Comment by dulsan** [comment]
> Armored Core titles require Write Color Buffers enabled for proper shading on the mechs.

I tried that and this happened:
![image](https://user-images.githubusercontent.com/13959909/106524155-45e1d700-6536-11eb-8ac5-985061724a2d.png)

The rainbow effect is still there, but this time more problems occured. 

I turned on write colour buffers and read colour buffers.

**Comment by dulsan** [comment]
After some testing, ive found that this play through is currently the most stable.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5907212/RPCS3.log.gz)

**Comment by dulsan** [comment]
ACVD seems to be playable with FAST interpreter (PPU), there are some random hangs here and there, but stable. The only issue here is the performance.
I've  also noticed that turning off accurate xfloat gives a significant performance boost. 

The settings i used were:
FAST interpreter (ppu)
Recompiler (LLVM)
Vulkan render
Enabled SPU loop detection
Disabled Accurate xfloat
Enabled SPU Cache
Disabled TSX
SPU block size: Mega
Anti-aliasing: Disabled 
Framelimit: 30
Async Shader mode
Write color butters: enabled

**Comment by jupiterbjy** [comment]
- `BLAS50618` (Korean released ACVD Blu-ray disc) 
- Win11 Education 21H2 22000.1165
- Ryzen 5800X / RAM 32GB / RTX 3070 (Not LHR)
- RPCS3 Version: 0.0.25-14358-a00f9e42 Alpha | master

Just to add a few update on previous issue:
- Even with *Write Color Buffers* & *Read Color Buffers* on, it still does not shade properly in Assembly & Paint Menus but do render properly in missions.
![image](https://user-images.githubusercontent.com/26041217/199370910-339a8a92-4c8b-4277-9131-dbaa49e57252.png)

- PPU Recomplier(LLVM) Significantly increase chance of crashing the game while starting and finishing each Mission.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9915187/RPCS3.log.gz)

---

After hours of testing, with my system, stable & desirable configuration was as follows:
- Settings changed over default:
  - CPU
    - SPU Block Size - Mega
    - PPU Decoder - Interpreter (static)
  - GPU
    - Write Color Buffers - On
    - Multithreaded RSC - On
    - Enable FSR Upscaling - On
  - System (Just my language)
    - Console Language - Korean
    - Console Region - Korea
    - Enter Button Assignment - Enter with circle
    - Keyboard Type - Korean Keyboard

[Test play with above configuration](https://www.youtube.com/watch?v=x1qismE7GeI)

**Comment by digant73** [comment]
is that still an issue?

**Comment by wxvu** [comment]
1. No longer an issue on latest RPCS3. (Write Color Buffers)
2. Poor performance likely not relevant for an issue report.
3. Duplicate of #13546.
4. No longer an issue on latest RPCS3.
*Flickering geometry is still present on Armored Core V, but not Verdict Day.
5. No longer an issue on latest RPCS3.
6. No longer an issue on latest RPCS3.
7. Still an issue on latest RPCS3.

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by wxvu** [comment]
@digant73 My report remains the same on latest RPCS3.
The texture and reflection issues have been fixed by Write Color Buffers for a long time.
The game still looks as broken without the setting.
The only issue remaining in this report that is not a duplicate issue is the flashing corrupted textures, also reported on the RPCS3 wiki.

https://github.com/user-attachments/assets/d191a938-a10f-4727-92ce-b70fa3dc14a3
<img width="1919" height="1046" alt="Image" src="https://github.com/user-attachments/assets/376441e8-e998-4214-8fe8-c36e4c160142" />

**Comment by wxvu** [comment]
Half-screen bug fixed by improvements with **Async Recompiler with Shader Interpreter** as of this month.
Only graphical issue remaining in Verdict Day is the blue square bug.

https://github.com/user-attachments/assets/257c7a2d-e421-489b-af19-c7a9b2ea30bc

https://github.com/user-attachments/assets/f9305f93-ff76-4a83-8a1c-90a14d44a1c8

**Comment by ShadowH69** [comment]
> Half-screen bug fixed by improvements with **Async Recompiler with Shader Interpreter** as of this month. Only graphical issue remaining in Verdict Day is the blue square bug.
> RPCS3.mp4
> PS3.mp4

try enabling Force CPU blit emulation in debug settings and see if the blue square issue still occurs

**Comment by BeezBumba** [comment]
> > Half-screen bug fixed by improvements with **Async Recompiler with Shader Interpreter** as of this month. Only graphical issue remaining in Verdict Day is the blue square bug.
> > RPCS3.mp4
> > PS3.mp4
> 
> try enabling Force CPU blit emulation in debug settings and see if the blue square issue still occurs

where is debug settings at?

**Comment by wxvu** [comment]
Thank you for the suggestion!
Unfortunately it does not fix the issue.

https://github.com/user-attachments/assets/0cc48fd1-6075-4d2a-9a89-4757ce65065b

**Comment by kd-11** [comment]
What is the blue square bug? I don't see anything in the clip that looks off, but then again I've never played an AC title.

**Comment by wxvu** [comment]
> What is the blue square bug? I don't see anything in the clip that looks off, but then again I've never played an AC title.

Transparent blue squares fill portions of the screen when moving.
It's an issue with how the dynamic light interacts with surfaces. The bug will seemingly only happens if you're near or touching terrain, and it's fixed entirely if you delete the file from gamedata responsible for rendering that effect.



Video compression masks the issue pretty well.
Should be more obvious on a darker map like this one.

https://github.com/user-attachments/assets/710f4f20-d866-4abd-ba7a-c8522cf2c575

**Comment by wxvu** [comment]
> What is the blue square bug? I don't see anything in the clip that looks off, but then again I've never played an AC title.

Created a dedicated issue page #19555 

Due to the rest of the issues in this thread being either duplicates or resolved (See [here](https://github.com/RPCS3/rpcs3/issues/9697#issuecomment-3494293006)), this thread can likely be closed.


### Remaining issues with Armored Core: Verdict Day -
- #13546 - Title crashes on SPU LLVM when booting from install data
- #19555 - 'Blue Squares' visual corruption
